package repo

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/Sam-Lam/PAIM/internal/db"
	"github.com/Sam-Lam/PAIM/internal/domain"
	"gorm.io/gorm"
)

// newTestDB opens a fresh temp-dir SQLite database with the full schema.
func newTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	path := filepath.Join(t.TempDir(), "paim_test.db")
	gdb, err := db.Open(path)
	if err != nil {
		t.Fatalf("open test db: %v", err)
	}
	return gdb
}

func ptr[T any](v T) *T { return &v }

// mustCreateAsset inserts a minimal valid asset and returns it.
func mustCreateAsset(t *testing.T, r *AssetRepo, quickHash string, size int64, mt domain.MediaType) *domain.Asset {
	t.Helper()
	a := &domain.Asset{
		OriginalFilename:   "IMG_" + quickHash + ".jpg",
		OriginalExtension:  "jpg",
		QuickHash:          quickHash,
		FileSize:           size,
		MediaType:          mt,
		VerificationStatus: domain.VerificationStatusVerified,
		BackupStatus:       domain.BackupStatusNone,
	}
	if err := r.Create(context.Background(), a); err != nil {
		t.Fatalf("create asset: %v", err)
	}
	if a.ID == "" {
		t.Fatal("expected asset ID to be generated by BeforeCreate hook")
	}
	return a
}
