// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DB,
    Statement
} from "./models.js";

import * as $models from "./models.js";

/**
 * ConnPool db conns pool interface
 * @typedef {$models.ConnPool} ConnPool
 */

/**
 * Dialector GORM database dialector
 * @typedef {$models.Dialector} Dialector
 */

/**
 * Plugin GORM plugin interface
 * @typedef {$models.Plugin} Plugin
 */
