// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Pipeline is the import engine. Construct it with New; the zero value is not
 * usable. It is safe for sequential use; a single Pipeline should run one
 * import at a time.
 */
export class Pipeline {
    /**
     * Creates a new Pipeline instance.
     * @param {Partial<Pipeline>} [$$source = {}] - The source object to create the Pipeline.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pipeline instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Pipeline}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pipeline(/** @type {Partial<Pipeline>} */($$parsedSource));
    }
}
