// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../Sam-Lam/PAIM/internal/services/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "analyze:completed": services$0.AnalyzeCompleted;
            "app:quit-requested": services$0.QuitRequested;
            "backup:backfill-completed": services$0.BackupBackfillCompleted;
            "backup:backfill-progress": services$0.BackupBackfillProgress;
            "backup:progress": services$0.BackupProgress;
            "backup:provider-failing": services$0.BackupProviderFailing;
            "backup:queue-changed": services$0.BackupQueueChanged;
            "cleanup:completed": services$0.CleanupCompleted;
            "cleanup:progress": services$0.CleanupProgress;
            "duplicate:progress": services$0.DuplicateProgress;
            "import:completed": services$0.ImportCompleted;
            "import:progress": services$0.ImportProgress;
            "library:progress": services$0.LibraryProgress;
            "log:export-progress": services$0.LogExportProgress;
            "reorganize:plan-progress": services$0.ReorganizePlanProgress;
            "source:cleared": services$0.SourceCleared;
            "source:evaluated": services$0.SourceEvaluated;
            "source:identified": services$0.SourceIdentified;
            "source:progress": services$0.SourceProgress;
            "thumbs:progress": services$0.ThumbsProgress;
            "volume:mounted": services$0.VolumeEvent;
            "volume:unmounted": services$0.VolumeEvent;
        }
    }
}
