//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../../../../Sam-Lam/PAIM/internal/services/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "analyze:completed": $$createType0,
        "backup:progress": $$createType1,
        "backup:queue-changed": $$createType2,
        "import:completed": $$createType3,
        "import:progress": $$createType4,
        "source:identified": $$createType5,
        "volume:mounted": $$createType6,
        "volume:unmounted": $$createType6,
    }));
}

// Private type creation functions
const $$createType0 = services$0.AnalyzeCompleted.createFrom;
const $$createType1 = services$0.BackupProgress.createFrom;
const $$createType2 = services$0.BackupQueueChanged.createFrom;
const $$createType3 = services$0.ImportCompleted.createFrom;
const $$createType4 = services$0.ImportProgress.createFrom;
const $$createType5 = services$0.SourceIdentified.createFrom;
const $$createType6 = services$0.VolumeEvent.createFrom;

configure();
