//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../../../../Sam-Lam/PAIM/internal/services/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "analyze:completed": $$createType0,
        "app:quit-requested": $$createType1,
        "backup:progress": $$createType2,
        "backup:queue-changed": $$createType3,
        "cleanup:completed": $$createType4,
        "cleanup:progress": $$createType5,
        "duplicate:progress": $$createType6,
        "import:completed": $$createType7,
        "import:progress": $$createType8,
        "library:progress": $$createType9,
        "log:export-progress": $$createType10,
        "reorganize:plan-progress": $$createType11,
        "source:cleared": $$createType12,
        "source:evaluated": $$createType13,
        "source:identified": $$createType14,
        "source:progress": $$createType15,
        "thumbs:progress": $$createType16,
        "volume:mounted": $$createType17,
        "volume:unmounted": $$createType17,
    }));
}

// Private type creation functions
const $$createType0 = services$0.AnalyzeCompleted.createFrom;
const $$createType1 = services$0.QuitRequested.createFrom;
const $$createType2 = services$0.BackupProgress.createFrom;
const $$createType3 = services$0.BackupQueueChanged.createFrom;
const $$createType4 = services$0.CleanupCompleted.createFrom;
const $$createType5 = services$0.CleanupProgress.createFrom;
const $$createType6 = services$0.DuplicateProgress.createFrom;
const $$createType7 = services$0.ImportCompleted.createFrom;
const $$createType8 = services$0.ImportProgress.createFrom;
const $$createType9 = services$0.LibraryProgress.createFrom;
const $$createType10 = services$0.LogExportProgress.createFrom;
const $$createType11 = services$0.ReorganizePlanProgress.createFrom;
const $$createType12 = services$0.SourceCleared.createFrom;
const $$createType13 = services$0.SourceEvaluated.createFrom;
const $$createType14 = services$0.SourceIdentified.createFrom;
const $$createType15 = services$0.SourceProgress.createFrom;
const $$createType16 = services$0.ThumbsProgress.createFrom;
const $$createType17 = services$0.VolumeEvent.createFrom;

configure();
