// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the Wails-bound application-lifecycle service backing the quit
 * guard. ActiveOperations exposes the running long operations (for the guard
 * dialog and future UI); ConfirmQuit cancels them, waits a bounded grace period,
 * then quits through the normal graceful-shutdown path.
 * 
 * The quit function and clock are injected so ConfirmQuit is unit-testable
 * without a running Wails app or real time: main.go assigns a quit closure that
 * flags the interception hook and calls app.Quit; tests assign a fake. Quit is an
 * exported field (not a setter method) deliberately — the Wails binding generator
 * binds exported methods but not fields, so this stays off the frontend API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveOperations returns the long operations currently running across the app.
 * It is bound to the frontend so the quit dialog (and future activity UI) can
 * read live progress on demand, independent of the app:quit-requested event.
 * @returns {$CancellablePromise<$models.OperationInfo[]>}
 */
export function ActiveOperations() {
    return $Call.ByID(3808902125).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ConfirmQuit is invoked by the guard dialog's "Quit anyway" action. It cancels
 * every active operation via its existing cancel path, waits up to the grace
 * period for the operations to drain (so the current per-file transaction can
 * settle), and then quits. It quits even if the grace period elapses with work
 * still in flight — that is a safe controlled crash the next launch recovers
 * from. It returns nil once the quit has been triggered.
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmQuit() {
    return $Call.ByID(4258269976);
}

// Private type creation functions
const $$createType0 = $models.OperationInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
