// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService inspects and controls the SQLite-persisted backup queue via the
 * backup Manager. State-changing methods emit backup:queue-changed so the UI can
 * refresh; per-upload progress is emitted as backup:progress by the Manager's
 * ProgressFn (wired in main.go, see NewBackupProgressEmitter).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BackfillStatus returns the current backfill state so a re-attaching UI can
 * resume showing inline progress.
 */
export function BackfillStatus(): $CancellablePromise<$models.BackfillStatusDTO> {
    return $Call.ByID(44538794);
}

/**
 * Bind wires the BackupService to an open library's catalog in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(1108989621, core);
}

/**
 * Cancel cancels a job from any non-terminal state.
 */
export function Cancel(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3236091820, jobID);
}

/**
 * CancelAllPending cancels every pending or paused backup job in one transition
 * and returns the number cancelled, mirroring RetryAllFailed's shape. Jobs
 * currently running (uploading) are NOT touched — an in-flight upload finishes
 * normally. It emits backup:queue-changed on success. Cancellation is a soft status
 * flip (rows are never hard-deleted); the archived originals are untouched and
 * backups can be re-queued later.
 */
export function CancelAllPending(): $CancellablePromise<number> {
    return $Call.ByID(3440620150);
}

/**
 * CancelBackfill cancels the active backfill (if any). It is a no-op when nothing
 * is running. The partially-enqueued jobs are kept (they are valid work); a later
 * StartBackfill enqueues the remainder.
 */
export function CancelBackfill(): $CancellablePromise<void> {
    return $Call.ByID(4186152798);
}

/**
 * ListJobs returns a page of backup jobs (optionally filtered by status), joined
 * with each job's asset filename and archive path. An empty statusFilter lists
 * all statuses.
 */
export function ListJobs(statusFilter: string, page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.BackupJobDTO>> {
    return $Call.ByID(1737606034, statusFilter, page, pageSize);
}

/**
 * Pause pauses a pending job.
 */
export function Pause(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3536245888, jobID);
}

/**
 * PauseAll pauses every pending job.
 */
export function PauseAll(): $CancellablePromise<void> {
    return $Call.ByID(3325548243);
}

/**
 * PauseBackupsDuringForeground reports the per-machine "Pause backups while
 * imports run" preference (default true). Read from the live gate so it reflects
 * any in-session toggle immediately.
 */
export function PauseBackupsDuringForeground(): $CancellablePromise<boolean> {
    return $Call.ByID(563609707);
}

/**
 * PreviewReconcile reports what a "recalculate queue" would do for the provider,
 * without changing anything: ToCancel counts its pending/paused jobs now out of
 * scope, ToEnqueue counts its in-scope eligible assets missing a job. It is the
 * count behind the inline "Scope changed — recalculate? (X to remove, Y to add)"
 * prompt. An empty ("all kinds") scope has nothing out of scope, so ToCancel is 0.
 */
export function PreviewReconcile(providerID: string): $CancellablePromise<$models.ReconcilePreviewDTO> {
    return $Call.ByID(3578253622, providerID);
}

/**
 * QueueSummary returns the count of jobs in each status.
 */
export function QueueSummary(): $CancellablePromise<$models.QueueSummaryDTO> {
    return $Call.ByID(3240464335);
}

/**
 * RequeueOptedOut reverses a per-import provider opt-out: it flips opted-out
 * backup jobs for the given provider back to pending so they upload ("Queue
 * anyway"). When sessionID is non-empty the reversal is scoped to the assets
 * imported under that session; an empty sessionID requeues every opted-out job
 * for the provider. It returns the number of jobs requeued and emits
 * backup:queue-changed so the queue and provider cards refresh. Per-session
 * scoping from the UI is deferred to the coming Coverage view; the plumbing is in
 * place here.
 */
export function RequeueOptedOut(providerID: string, sessionID: string): $CancellablePromise<number> {
    return $Call.ByID(814362798, providerID, sessionID);
}

/**
 * Resume resumes a paused job.
 */
export function Resume(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(1523895361, jobID);
}

/**
 * ResumeAll resumes every paused job.
 */
export function ResumeAll(): $CancellablePromise<void> {
    return $Call.ByID(470287800);
}

/**
 * Retry requeues a failed job immediately.
 */
export function Retry(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(2080218012, jobID);
}

/**
 * RetryAllFailed requeues every failed backup job to pending in one transition
 * and returns the number requeued. It emits backup:queue-changed on success. It
 * composes with provider cooldowns and the foreground yield gate naturally (those
 * gate claiming, not status): requeued jobs wait pending until claiming resumes.
 */
export function RetryAllFailed(): $CancellablePromise<number> {
    return $Call.ByID(4113057650);
}

/**
 * SessionBackupStatus reports how many of a session's backup-eligible assets are
 * fully backed up, so the import completion panel can show live progress and
 * enable evaluation once backups drain.
 */
export function SessionBackupStatus(sessionID: string): $CancellablePromise<$models.SessionBackupStatusDTO> {
    return $Call.ByID(3411884294, sessionID);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(2196210049, gate);
}

/**
 * SetPauseBackupsDuringForeground persists the per-machine preference to
 * library.Config and applies it to the live backup yield gate immediately
 * (mirroring how thumbnail parallelism is live-applied). It returns the stored
 * value.
 */
export function SetPauseBackupsDuringForeground(on: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(389188675, on);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 */
export function SetSleepGuard(g: $models.SleepGuard | null): $CancellablePromise<void> {
    return $Call.ByID(3763771882, g);
}

/**
 * StartBackfill enqueues a backup job for every eligible asset that does not yet
 * have one for the given (enabled) provider — closing the gap left when a provider
 * is added AFTER a library is already populated (import-time enqueue only covers
 * assets imported while the provider existed). It runs in the background: activity-
 * tracked (quit-guard aware), sleep-guarded, cancellable, and resumable — a
 * cancelled run re-scans from the start next time and skips what it already
 * enqueued (Enqueue is idempotent). Only one backfill runs at a time
 * (ErrBackfillInProgress otherwise).
 * 
 * Eligibility mirrors the importer exactly: non-deleted, verified assets with an
 * archive copy (CurrentArchivePath <> ”). Copy-mode duplicate placeholders (empty
 * path) are excluded; adopt-flagged duplicates (which carry a path) are included.
 * Each backfilled job is stamped with the same capture/import-date SortKey the
 * importer uses (backup.SortKeyForAsset) so it honors the provider's upload order.
 */
export function StartBackfill(providerID: string): $CancellablePromise<$models.BackfillStatusDTO> {
    return $Call.ByID(618161832, providerID);
}

/**
 * StartReconcile brings the provider's queue into line with its current scope in
 * the background: it (a) cancels its pending/paused jobs whose asset is now out of
 * scope (batch transition, stamping outOfScopeNote), then (b) runs the scope-aware
 * backfill path to enqueue every in-scope eligible asset that lacks a job. It
 * reuses the backfill single-instance guard, so a reconcile and a backfill can
 * never run concurrently (ErrBackfillInProgress otherwise). Progress reuses the
 * backup:backfill-progress events (so a re-attaching UI shows the same inline
 * bar); completion emits a backup:reconcile-completed event carrying {cancelled,
 * enqueued} for the toast, plus backup:queue-changed.
 * 
 * The out-of-scope cancel is a DERIVED reconciliation of jobs enqueued under a
 * wider scope — it is NOT a per-import opt-out (those durable opted_out rows are
 * left untouched; only pending/paused jobs are reclaimed). This mirrors the
 * enqueue path, where scope exclusion is likewise derived, never recorded.
 */
export function StartReconcile(providerID: string): $CancellablePromise<$models.BackfillStatusDTO> {
    return $Call.ByID(410631250, providerID);
}
