// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService inspects and controls the SQLite-persisted backup queue via the
 * backup Manager. State-changing methods emit backup:queue-changed so the UI can
 * refresh; per-upload progress is emitted as backup:progress by the Manager's
 * ProgressFn (wired in main.go, see NewBackupProgressEmitter).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BackfillStatus returns the current backfill state so a re-attaching UI can
 * resume showing inline progress.
 * @returns {$CancellablePromise<$models.BackfillStatusDTO>}
 */
export function BackfillStatus() {
    return $Call.ByID(44538794).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Bind wires the BackupService to an open library's catalog in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(1108989621, core);
}

/**
 * Cancel cancels a job from any non-terminal state.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(jobID) {
    return $Call.ByID(3236091820, jobID);
}

/**
 * CancelBackfill cancels the active backfill (if any). It is a no-op when nothing
 * is running. The partially-enqueued jobs are kept (they are valid work); a later
 * StartBackfill enqueues the remainder.
 * @returns {$CancellablePromise<void>}
 */
export function CancelBackfill() {
    return $Call.ByID(4186152798);
}

/**
 * ListJobs returns a page of backup jobs (optionally filtered by status), joined
 * with each job's asset filename and archive path. An empty statusFilter lists
 * all statuses.
 * @param {string} statusFilter
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.BackupJobDTO>>}
 */
export function ListJobs(statusFilter, page, pageSize) {
    return $Call.ByID(1737606034, statusFilter, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Pause pauses a pending job.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Pause(jobID) {
    return $Call.ByID(3536245888, jobID);
}

/**
 * PauseAll pauses every pending job.
 * @returns {$CancellablePromise<void>}
 */
export function PauseAll() {
    return $Call.ByID(3325548243);
}

/**
 * PauseBackupsDuringForeground reports the per-machine "Pause backups while
 * imports run" preference (default true). Read from the live gate so it reflects
 * any in-session toggle immediately.
 * @returns {$CancellablePromise<boolean>}
 */
export function PauseBackupsDuringForeground() {
    return $Call.ByID(563609707);
}

/**
 * QueueSummary returns the count of jobs in each status.
 * @returns {$CancellablePromise<$models.QueueSummaryDTO>}
 */
export function QueueSummary() {
    return $Call.ByID(3240464335).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RequeueOptedOut reverses a per-import provider opt-out: it flips opted-out
 * backup jobs for the given provider back to pending so they upload ("Queue
 * anyway"). When sessionID is non-empty the reversal is scoped to the assets
 * imported under that session; an empty sessionID requeues every opted-out job
 * for the provider. It returns the number of jobs requeued and emits
 * backup:queue-changed so the queue and provider cards refresh. Per-session
 * scoping from the UI is deferred to the coming Coverage view; the plumbing is in
 * place here.
 * @param {string} providerID
 * @param {string} sessionID
 * @returns {$CancellablePromise<number>}
 */
export function RequeueOptedOut(providerID, sessionID) {
    return $Call.ByID(814362798, providerID, sessionID);
}

/**
 * Resume resumes a paused job.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Resume(jobID) {
    return $Call.ByID(1523895361, jobID);
}

/**
 * ResumeAll resumes every paused job.
 * @returns {$CancellablePromise<void>}
 */
export function ResumeAll() {
    return $Call.ByID(470287800);
}

/**
 * Retry requeues a failed job immediately.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Retry(jobID) {
    return $Call.ByID(2080218012, jobID);
}

/**
 * RetryAllFailed requeues every failed backup job to pending in one transition
 * and returns the number requeued. It emits backup:queue-changed on success. It
 * composes with provider cooldowns and the foreground yield gate naturally (those
 * gate claiming, not status): requeued jobs wait pending until claiming resumes.
 * @returns {$CancellablePromise<number>}
 */
export function RetryAllFailed() {
    return $Call.ByID(4113057650);
}

/**
 * SessionBackupStatus reports how many of a session's backup-eligible assets are
 * fully backed up, so the import completion panel can show live progress and
 * enable evaluation once backups drain.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.SessionBackupStatusDTO>}
 */
export function SessionBackupStatus(sessionID) {
    return $Call.ByID(3411884294, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(2196210049, gate);
}

/**
 * SetPauseBackupsDuringForeground persists the per-machine preference to
 * library.Config and applies it to the live backup yield gate immediately
 * (mirroring how thumbnail parallelism is live-applied). It returns the stored
 * value.
 * @param {boolean} on
 * @returns {$CancellablePromise<boolean>}
 */
export function SetPauseBackupsDuringForeground(on) {
    return $Call.ByID(389188675, on);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 * @param {$models.SleepGuard | null} g
 * @returns {$CancellablePromise<void>}
 */
export function SetSleepGuard(g) {
    return $Call.ByID(3763771882, g);
}

/**
 * StartBackfill enqueues a backup job for every eligible asset that does not yet
 * have one for the given (enabled) provider — closing the gap left when a provider
 * is added AFTER a library is already populated (import-time enqueue only covers
 * assets imported while the provider existed). It runs in the background: activity-
 * tracked (quit-guard aware), sleep-guarded, cancellable, and resumable — a
 * cancelled run re-scans from the start next time and skips what it already
 * enqueued (Enqueue is idempotent). Only one backfill runs at a time
 * (ErrBackfillInProgress otherwise).
 * 
 * Eligibility mirrors the importer exactly: non-deleted, verified assets with an
 * archive copy (CurrentArchivePath <> ''). Copy-mode duplicate placeholders (empty
 * path) are excluded; adopt-flagged duplicates (which carry a path) are included.
 * Each backfilled job is stamped with the same capture/import-date SortKey the
 * importer uses (backup.SortKeyForAsset) so it honors the provider's upload order.
 * @param {string} providerID
 * @returns {$CancellablePromise<$models.BackfillStatusDTO>}
 */
export function StartBackfill(providerID) {
    return $Call.ByID(618161832, providerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BackfillStatusDTO.createFrom;
const $$createType1 = $models.BackupJobDTO.createFrom;
const $$createType2 = $models.PageResult.createFrom($$createType1);
const $$createType3 = $models.QueueSummaryDTO.createFrom;
const $$createType4 = $models.SessionBackupStatusDTO.createFrom;
