// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService inspects and controls the SQLite-persisted backup queue via the
 * backup Manager. State-changing methods emit backup:queue-changed so the UI can
 * refresh; per-upload progress is emitted as backup:progress by the Manager's
 * ProgressFn (wired in main.go, see NewBackupProgressEmitter).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the BackupService to an open library's catalog in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(1108989621, core);
}

/**
 * Cancel cancels a job from any non-terminal state.
 */
export function Cancel(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3236091820, jobID);
}

/**
 * ListJobs returns a page of backup jobs (optionally filtered by status), joined
 * with each job's asset filename and archive path. An empty statusFilter lists
 * all statuses.
 */
export function ListJobs(statusFilter: string, page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.BackupJobDTO>> {
    return $Call.ByID(1737606034, statusFilter, page, pageSize);
}

/**
 * Pause pauses a pending job.
 */
export function Pause(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3536245888, jobID);
}

/**
 * PauseAll pauses every pending job.
 */
export function PauseAll(): $CancellablePromise<void> {
    return $Call.ByID(3325548243);
}

/**
 * QueueSummary returns the count of jobs in each status.
 */
export function QueueSummary(): $CancellablePromise<$models.QueueSummaryDTO> {
    return $Call.ByID(3240464335);
}

/**
 * Resume resumes a paused job.
 */
export function Resume(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(1523895361, jobID);
}

/**
 * ResumeAll resumes every paused job.
 */
export function ResumeAll(): $CancellablePromise<void> {
    return $Call.ByID(470287800);
}

/**
 * Retry requeues a failed job immediately.
 */
export function Retry(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(2080218012, jobID);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(2196210049, gate);
}
