// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService powers the read-only asset browser: a filtered, paginated grid
 * of what is archived, plus full provenance for a single asset. It is strictly
 * read-only — PAIM is an integrity tool, not a DAM — and exposes no mutating
 * methods. Every method is gated on an open library.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssetDetail returns the full provenance record for one asset: original
 * identity, resolved archive path, both hashes, all camera/exposure/GPS
 * metadata, its source and session, its per-asset backup jobs, and its duplicate
 * and Live Photo relationships (as slim refs for in-drawer navigation).
 * @param {string} id
 * @returns {$CancellablePromise<$models.AssetDetailDTO>}
 */
export function AssetDetail(id) {
    return $Call.ByID(3317079299, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Bind wires the BrowserService to an open library's catalog in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(3501756837, core);
}

/**
 * ListAssets returns a page of slim asset tiles matching filters, sorted
 * capture-date DESC (assets without a capture date sort last). Total is the true
 * match count so the grid can page correctly.
 * @param {$models.BrowseFilters} filters
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.BrowseAssetDTO>>}
 */
export function ListAssets(filters, page, pageSize) {
    return $Call.ByID(2494688543, filters, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Months returns distinct capture months with counts (newest first) for the
 * filter dropdown and grid section headers.
 * @returns {$CancellablePromise<$models.MonthCountDTO[]>}
 */
export function Months() {
    return $Call.ByID(1742568889).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(911157745, gate);
}

// Private type creation functions
const $$createType0 = $models.AssetDetailDTO.createFrom;
const $$createType1 = $models.BrowseAssetDTO.createFrom;
const $$createType2 = $models.PageResult.createFrom($$createType1);
const $$createType3 = $models.MonthCountDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
