// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService powers the read-only asset browser: a filtered, paginated grid
 * of what is archived, plus full provenance for a single asset. It is strictly
 * read-only — PAIM is an integrity tool, not a DAM — and exposes no mutating
 * methods. Every method is gated on an open library.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssetDetail returns the full provenance record for one asset: original
 * identity, resolved archive path, both hashes, all camera/exposure/GPS
 * metadata, its source and session, its per-asset backup jobs, and its duplicate
 * and Live Photo relationships (as slim refs for in-drawer navigation).
 * @param {string} id
 * @returns {$CancellablePromise<$models.AssetDetailDTO>}
 */
export function AssetDetail(id) {
    return $Call.ByID(3317079299, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Bind wires the BrowserService to an open library's catalog in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(3501756837, core);
}

/**
 * ListAssets returns a page of slim asset tiles matching filters, sorted
 * capture-date DESC (assets without a capture date sort last). Total is the true
 * match count so the grid can page correctly.
 * @param {$models.BrowseFilters} filters
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.BrowseAssetDTO>>}
 */
export function ListAssets(filters, page, pageSize) {
    return $Call.ByID(2494688543, filters, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListFolder returns one level of the archive tree derived from the catalog
 * (never a filesystem walk): the immediate subfolders of relDir (each with a
 * recursive asset count and cover thumbnail) plus the assets sitting directly in
 * relDir, paged. relDir is a root-relative forward-slash directory; "" lists the
 * year folders at the root. The returned RelDir is the cleaned, breadcrumb-safe
 * path.
 * @param {string} relDir
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.FolderListingDTO>}
 */
export function ListFolder(relDir, page, pageSize) {
    return $Call.ByID(3269834490, relDir, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Months returns distinct capture months with counts (newest first) for the
 * filter dropdown and grid section headers.
 * @returns {$CancellablePromise<$models.MonthCountDTO[]>}
 */
export function Months() {
    return $Call.ByID(1742568889).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * RenameEventFolder renames a date-event folder's human label. relDir must be a
 * "YYYY/YYYY-MM-DD*" folder under the library root; the new folder name is the
 * date prefix plus the sanitized newLabel (an empty label yields the bare
 * "YYYY-MM-DD"). It refuses when the target folder already exists, when relDir is
 * not a date folder, when the resolved path would escape the root, and when any
 * long operation is running. It renames the directory on disk, then rewrites the
 * CurrentArchivePath prefix of every contained asset (RAW/ subpaths ride along)
 * in ONE transaction; on a DB failure it best-effort renames the directory back
 * and returns the error. This is the ONLY sanctioned way to rename an archive
 * folder — doing it in Finder would strand the catalog.
 * @param {string} relDir
 * @param {string} newLabel
 * @returns {$CancellablePromise<$models.FolderListingDTO>}
 */
export function RenameEventFolder(relDir, newLabel) {
    return $Call.ByID(1543151500, relDir, newLabel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RevealAsset reveals one of an asset's files in Finder (`open -R`). The path is
 * resolved SERVER-side from the asset row — the frontend never passes a raw
 * filesystem path across the bridge. which selects the archived copy
 * (RevealArchive) or the original source file (RevealOriginal). The file must
 * exist; a missing file (e.g. the SD card was ejected) returns an error the
 * frontend surfaces as a toast — the reveal button is normally disabled when the
 * file is already known to be absent.
 * @param {string} assetID
 * @param {string} which
 * @returns {$CancellablePromise<void>}
 */
export function RevealAsset(assetID, which) {
    return $Call.ByID(2877423165, assetID, which);
}

/**
 * RevealFolder reveals an archive folder in Finder (`open -R`). relDir is a
 * root-relative forward-slash directory resolved SERVER-side; the frontend never
 * passes an absolute path. The directory must exist under the library root.
 * @param {string} relDir
 * @returns {$CancellablePromise<void>}
 */
export function RevealFolder(relDir) {
    return $Call.ByID(1662728479, relDir);
}

/**
 * SetActivity injects the shared activity tracker so RenameEventFolder can refuse
 * while any long operation is in flight. Called once by main.go.
 * @param {$models.activitySnapshotter} a
 * @returns {$CancellablePromise<void>}
 */
export function SetActivity(a) {
    return $Call.ByID(2613221987, a);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(911157745, gate);
}

// Private type creation functions
const $$createType0 = $models.AssetDetailDTO.createFrom;
const $$createType1 = $models.BrowseAssetDTO.createFrom;
const $$createType2 = $models.PageResult.createFrom($$createType1);
const $$createType3 = $models.FolderListingDTO.createFrom;
const $$createType4 = $models.MonthCountDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
