// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService powers the read-only asset browser: a filtered, paginated grid
 * of what is archived, plus full provenance for a single asset. It is strictly
 * read-only — PAIM is an integrity tool, not a DAM — and exposes no mutating
 * methods. Every method is gated on an open library.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssetDetail returns the full provenance record for one asset: original
 * identity, resolved archive path, both hashes, all camera/exposure/GPS
 * metadata, its source and session, its per-asset backup jobs, and its duplicate
 * and Live Photo relationships (as slim refs for in-drawer navigation).
 * @param {string} id
 * @returns {$CancellablePromise<$models.AssetDetailDTO>}
 */
export function AssetDetail(id) {
    return $Call.ByID(3317079299, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Bind wires the BrowserService to an open library's catalog in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(3501756837, core);
}

/**
 * Cameras returns the distinct cameras (make + model) present in the library
 * with per-camera asset counts, most-used first, for the Camera filter dropdown.
 * Label is the display "Make Model" (collapsed whitespace); the frontend filters
 * on the exact Make/Model pair.
 * @returns {$CancellablePromise<$models.CameraCountDTO[]>}
 */
export function Cameras() {
    return $Call.ByID(711760930).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CoverageProviders lists every destination ever referenced by a backup job
 * (including removed providers, resolved Unscoped) for the coverage table's
 * column set and the per-provider status filter dropdown. Live destinations sort
 * first, then removed ones; within each group, by name — so the primary columns
 * are the destinations still in use.
 * @returns {$CancellablePromise<$models.CoverageProviderDTO[]>}
 */
export function CoverageProviders() {
    return $Call.ByID(739639758).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListAssets returns a page of slim asset tiles matching filters, sorted
 * capture-date DESC (assets without a capture date sort last). Total is the true
 * match count so the grid can page correctly.
 * @param {$models.BrowseFilters} filters
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.BrowseAssetDTO>>}
 */
export function ListAssets(filters, page, pageSize) {
    return $Call.ByID(2494688543, filters, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListCoverage returns a page of the Backup Coverage table: one row per asset
 * (matching the same Batch-B filters ListAssets accepts) with its provenance and
 * its per-destination backup state. When providerStatus is set, the page is
 * restricted to assets whose backup state for that destination matches the given
 * coverage status (composed as an EXISTS/NOT EXISTS predicate on the jobs table,
 * AND-ed with every other filter).
 * 
 * Query shape / scale: the page of assets is fetched first via AssetRepo.List
 * (the same filtered, capture-date-ordered, indexed query the grid uses). Then a
 * SINGLE query loads every non-deleted backup job for that page's asset IDs (an
 * IN clause over the indexed asset_id), grouped in Go into asset -> destination
 * -> newest job. Provider metadata (mirror/name/removed) is resolved with one
 * Unscoped query over the destinations seen on the page, and per-row source
 * labels are memoized by session. So a page costs O(1) queries regardless of page
 * size — no per-asset or per-provider round-trips in the row loop.
 * @param {$models.BrowseFilters} filters
 * @param {$models.CoverageProviderFilter | null} providerStatus
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.CoverageRowDTO>>}
 */
export function ListCoverage(filters, providerStatus, page, pageSize) {
    return $Call.ByID(1693375104, filters, providerStatus, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListFolder returns one level of the archive tree derived from the catalog
 * (never a filesystem walk): the immediate subfolders of relDir (each with a
 * recursive asset count, cover thumbnail, and newest capture date) plus the
 * assets sitting directly in relDir, paged. relDir is a root-relative
 * forward-slash directory; "" lists the year folders at the root. The returned
 * RelDir is the cleaned, breadcrumb-safe path. sortBy ("name"|"date") and
 * sortDir ("asc"|"desc") order the directly-contained assets; unknown values
 * default to date/desc (newest first). Subfolders are always returned in name
 * order and re-sorted client-side.
 * @param {string} relDir
 * @param {number} page
 * @param {number} pageSize
 * @param {string} sortBy
 * @param {string} sortDir
 * @returns {$CancellablePromise<$models.FolderListingDTO>}
 */
export function ListFolder(relDir, page, pageSize, sortBy, sortDir) {
    return $Call.ByID(3269834490, relDir, page, pageSize, sortBy, sortDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * Months returns distinct capture months with counts (newest first) for the
 * filter dropdown and grid section headers.
 * @returns {$CancellablePromise<$models.MonthCountDTO[]>}
 */
export function Months() {
    return $Call.ByID(1742568889).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * QueueAssetsForProvider queues the given assets for one destination, returning
 * how many were newly queued. Per asset: an existing opted_out job for the
 * destination is un-skipped (opted_out -> pending); an asset with NO job for the
 * destination gets a fresh pending job; an asset that already has a
 * pending/running/completed job is left untouched (and not counted). It emits
 * backup:queue-changed when anything was queued. assetIds is capped at
 * coverageQueueCap per call.
 * 
 * Seam decision: the fresh-enqueue path reuses the exported, idempotent
 * BackupRepo.Enqueue (owned elsewhere; called, not modified). There is no
 * asset-scoped un-skip primitive — RequeueOptedOut is provider/session-scoped —
 * so the opted_out -> pending flip is a guarded direct update in this file
 * (WHERE destination = ? AND status = opted_out AND asset_id IN ?), mirroring
 * RequeueOptedOut's transition exactly. TODO: consolidate the asset-scoped
 * requeue into repo/backup.go once ownership allows.
 * @param {string} providerID
 * @param {string[]} assetIds
 * @returns {$CancellablePromise<number>}
 */
export function QueueAssetsForProvider(providerID, assetIds) {
    return $Call.ByID(135690922, providerID, assetIds);
}

/**
 * RenameEventFolder renames a date-event folder's human label. relDir must be a
 * "YYYY/YYYY-MM-DD*" folder under the library root; the new folder name is the
 * date prefix plus the sanitized newLabel (an empty label yields the bare
 * "YYYY-MM-DD"). It refuses when the target folder already exists, when relDir is
 * not a date folder, when the resolved path would escape the root, and when any
 * long operation is running. It renames the directory on disk, then rewrites the
 * CurrentArchivePath prefix of every contained asset (RAW/ subpaths ride along)
 * in ONE transaction; on a DB failure it best-effort renames the directory back
 * and returns the error. This is the ONLY sanctioned way to rename an archive
 * folder — doing it in Finder would strand the catalog.
 * @param {string} relDir
 * @param {string} newLabel
 * @returns {$CancellablePromise<$models.FolderListingDTO>}
 */
export function RenameEventFolder(relDir, newLabel) {
    return $Call.ByID(1543151500, relDir, newLabel).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * RevealAsset reveals one of an asset's files in Finder (`open -R`). The path is
 * resolved SERVER-side from the asset row — the frontend never passes a raw
 * filesystem path across the bridge. which selects the archived copy
 * (RevealArchive) or the original source file (RevealOriginal). The file must
 * exist; a missing file (e.g. the SD card was ejected) returns an error the
 * frontend surfaces as a toast — the reveal button is normally disabled when the
 * file is already known to be absent.
 * @param {string} assetID
 * @param {string} which
 * @returns {$CancellablePromise<void>}
 */
export function RevealAsset(assetID, which) {
    return $Call.ByID(2877423165, assetID, which);
}

/**
 * RevealFolder reveals an archive folder in Finder (`open -R`). relDir is a
 * root-relative forward-slash directory resolved SERVER-side; the frontend never
 * passes an absolute path. The directory must exist under the library root.
 * @param {string} relDir
 * @returns {$CancellablePromise<void>}
 */
export function RevealFolder(relDir) {
    return $Call.ByID(1662728479, relDir);
}

/**
 * SetActivity injects the shared activity tracker so RenameEventFolder can refuse
 * while any long operation is in flight. Called once by main.go.
 * @param {$models.activitySnapshotter} a
 * @returns {$CancellablePromise<void>}
 */
export function SetActivity(a) {
    return $Call.ByID(2613221987, a);
}

/**
 * SetEmitter injects the shared event emitter so the coverage view's bulk queue
 * action can emit backup:queue-changed. Called once by main.go (mirrors how the
 * backup services receive their emitter at construction).
 * @param {$models.Emitter} e
 * @returns {$CancellablePromise<void>}
 */
export function SetEmitter(e) {
    return $Call.ByID(2242600140, e);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(911157745, gate);
}

/**
 * Years returns distinct capture years with counts (newest first) for the Date
 * filter's year level. It is the CaptureMonths data rolled up to years, so years
 * and months share one capture-date basis (undated assets excluded).
 * @returns {$CancellablePromise<$models.YearCountDTO[]>}
 */
export function Years() {
    return $Call.ByID(2940347496).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AssetDetailDTO.createFrom;
const $$createType1 = $models.CameraCountDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.CoverageProviderDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.BrowseAssetDTO.createFrom;
const $$createType6 = $models.PageResult.createFrom($$createType5);
const $$createType7 = $models.CoverageRowDTO.createFrom;
const $$createType8 = $models.PageResult.createFrom($$createType7);
const $$createType9 = $models.FolderListingDTO.createFrom;
const $$createType10 = $models.MonthCountDTO.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.YearCountDTO.createFrom;
const $$createType13 = $Create.Array($$createType12);
