// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CleanupService runs the read-only Cleanup Assistant analysis over a folder.
 * 
 * v1 is advisory only: there is deliberately NO server-side delete method. The
 * Analyze result carries a recommendation the UI presents; any actual deletion
 * is the user's responsibility in Finder. A DeleteAnalyzedFolder method is
 * intentionally not implemented.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Analyze performs a strictly read-only classification of every media file under
 * root against the archive and returns the report plus its delete-safety
 * recommendation. It is synchronous but honors ctx cancellation between files.
 * @param {string} root
 * @returns {$CancellablePromise<$models.CleanupReportDTO>}
 */
export function Analyze(root) {
    return $Call.ByID(2471023610, root).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Bind wires the CleanupService to an open library's analyzer in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(3355625145, core);
}

/**
 * PickFolder opens a native directory chooser for the folder to analyze.
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(3457112271);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(3390353397, gate);
}

// Private type creation functions
const $$createType0 = $models.CleanupReportDTO.createFrom;
