// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CleanupService runs the read-only Cleanup Assistant analysis over a folder.
 * 
 * v1 is advisory only: there is deliberately NO server-side delete method. The
 * Analyze result carries a recommendation the UI presents; any actual deletion
 * is the user's responsibility in Finder. A DeleteAnalyzedFolder method is
 * intentionally not implemented.
 * 
 * Analysis is a re-attachable background job (StartCleanupAnalyze /
 * ActiveCleanupAnalyze / CancelCleanupAnalyze) because hashing a large folder
 * against the archive takes minutes; the synchronous Analyze remains for simple
 * callers and tests.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveCleanupAnalyze returns the current analysis state for re-attachment:
 * "running" with the latest progress snapshot, "completed" with the report (or a
 * cancelled/failed marker), or "none". A completed snapshot lapses to "none"
 * after cleanupReportTTL.
 * @returns {$CancellablePromise<$models.ActiveCleanupAnalyzeDTO>}
 */
export function ActiveCleanupAnalyze() {
    return $Call.ByID(1621347092).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Analyze performs a strictly read-only classification of every media file under
 * root against the archive and returns the report plus its delete-safety
 * recommendation. It is synchronous but honors ctx cancellation between files.
 * @param {string} root
 * @returns {$CancellablePromise<$models.CleanupReportDTO>}
 */
export function Analyze(root) {
    return $Call.ByID(2471023610, root).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Bind wires the CleanupService to an open library's analyzer in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(3355625145, core);
}

/**
 * CancelCleanupAnalyze cancels the active cleanup analysis (if any). It is a
 * no-op when nothing is running.
 * @returns {$CancellablePromise<void>}
 */
export function CancelCleanupAnalyze() {
    return $Call.ByID(3112709864);
}

/**
 * PickFolder opens a native directory chooser for the folder to analyze.
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(3457112271);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(3390353397, gate);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 * @param {$models.SleepGuard | null} g
 * @returns {$CancellablePromise<void>}
 */
export function SetSleepGuard(g) {
    return $Call.ByID(3404511190, g);
}

/**
 * StartCleanupAnalyze launches a background cleanup analysis of root. Only one may
 * run at a time (ErrCleanupInProgress otherwise). It emits throttled
 * cleanup:progress (verbose per-file count + current file; the total is unknown
 * during the single-pass walk-and-classify, so FilesTotal stays 0) and a terminal
 * cleanup:completed when it finishes; the completed report is retained for
 * re-attachment (ActiveCleanupAnalyze) for cleanupReportTTL. Cancel via
 * CancelCleanupAnalyze.
 * @param {string} root
 * @returns {$CancellablePromise<$models.StartCleanupAnalyzeResult>}
 */
export function StartCleanupAnalyze(root) {
    return $Call.ByID(890602810, root).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ActiveCleanupAnalyzeDTO.createFrom;
const $$createType1 = $models.CleanupReportDTO.createFrom;
const $$createType2 = $models.StartCleanupAnalyzeResult.createFrom;
