// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService aggregates the headline metrics shown on the dashboard. It
 * uses the repositories where they expose the needed rollups and falls back to
 * direct GORM read-model queries for aggregates the repos do not cover
 * (per-month growth, status counts, recent activity).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssetsOverTime returns the library's asset distribution over effective capture
 * time, bucketed at the given granularity ("day"|"month"|"year"|"5year"|"all").
 * "all" (and any unrecognized value) auto-picks from the data span; see
 * resolveGranularity. Gaps between the earliest and latest bucket are zero-filled
 * so the time axis is honest; the Day view windows to its most recent dayWindow
 * buckets. Excludes soft-deleted assets.
 * @param {string} granularity
 * @returns {$CancellablePromise<$models.AssetsOverTimeDTO | null>}
 */
export function AssetsOverTime(granularity) {
    return $Call.ByID(4145156572, granularity).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Bind wires the DashboardService to an open library's catalog in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(367829209, core);
}

/**
 * GetStats computes the dashboard metrics.
 * @returns {$CancellablePromise<$models.DashboardStats>}
 */
export function GetStats() {
    return $Call.ByID(3217767757).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(2297460053, gate);
}

// Private type creation functions
const $$createType0 = $models.AssetsOverTimeDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DashboardStats.createFrom;
