// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DuplicateService lists duplicate pairs and resolves them. Every resolving
 * action is destructive-adjacent and MUST be confirmed by the frontend (via
 * ConfirmDialog) before it is invoked; the service performs the action without
 * re-prompting.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the DuplicateService to an open library's catalog in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(3557733976, core);
}

/**
 * ListDuplicates returns a page of duplicate/original pairs (newest first).
 */
export function ListDuplicates(page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.DuplicatePairDTO>> {
    return $Call.ByID(4232984785, page, pageSize);
}

/**
 * ResolveDuplicate applies action to the duplicate asset. Actions (all require a
 * prior frontend confirmation):
 * 
 *   - delete: soft-delete the asset row AND move its physical archive file (when
 *     present) into <MasterLibrary>/.paim-trash/. The file is never hard-deleted.
 *   - move: physically move the duplicate's file to destFolder — a same-volume
 *     atomic rename, or a cross-volume copy+verify followed by trashing the
 *     original — and update CurrentArchivePath.
 *   - ignore: clear the duplicate flag and record a note (in the log; the Asset
 *     model has no notes column).
 *   - keep_both: clear the duplicate flag, keeping both files intentionally, and
 *     record a note.
 * 
 * destFolder is used only by the move action.
 */
export function ResolveDuplicate(duplicateAssetID: string, action: string, destFolder: string): $CancellablePromise<void> {
    return $Call.ByID(1261347546, duplicateAssetID, action, destFolder);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(3666370770, gate);
}
