// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DuplicateService lists duplicate pairs and resolves them. Every resolving
 * action is destructive-adjacent and MUST be confirmed by the frontend (via
 * ConfirmDialog) before it is invoked; the service performs the action without
 * re-prompting.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveBulkResolve returns the current bulk-resolve state for re-attachment:
 * "running" with the latest progress snapshot, "completed" with the summary (or a
 * cancelled marker), or "none". A completed snapshot lapses after safeEraseReportTTL.
 */
export function ActiveBulkResolve(): $CancellablePromise<$models.ActiveBulkResolveDTO> {
    return $Call.ByID(2562701671);
}

/**
 * Bind wires the DuplicateService to an open library's catalog in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(3557733976, core);
}

/**
 * CancelBulkResolve cancels a running bulk resolve (if any). Items already
 * resolved stay resolved; the job stops cleanly before the next item.
 */
export function CancelBulkResolve(): $CancellablePromise<void> {
    return $Call.ByID(4247312975);
}

/**
 * CountSourceOnlyRecords returns how many legacy source-only placeholder duplicate
 * rows exist (flagged duplicates with an empty archive path). These came from
 * pre-v5 copy-mode re-imports of already-archived sources: nothing was copied, so
 * they are "already imported", not duplicates. A non-zero count drives the
 * Duplicate Manager's one-time cleanup banner.
 */
export function CountSourceOnlyRecords(): $CancellablePromise<number> {
    return $Call.ByID(479478285);
}

/**
 * DuplicateStats returns the archive-wide duplicate totals (pair count + wasted
 * bytes) for the header, computed in SQL across ALL flagged duplicates.
 */
export function DuplicateStats(): $CancellablePromise<$models.DuplicateStatsDTO> {
    return $Call.ByID(4173165203);
}

/**
 * ListDuplicateGroups returns the distinct duplicate groups (with counts + wasted
 * bytes) for a group picker. groupBy is "folder" or "session". Groups are ordered
 * by wasted bytes descending.
 */
export function ListDuplicateGroups(groupBy: string): $CancellablePromise<$models.DuplicateGroupDTO[] | null> {
    return $Call.ByID(3325735128, groupBy);
}

/**
 * ListDuplicateIDs returns the full ID list of every flagged duplicate matching
 * the filter, so the frontend can "select all in folder/session/filter" without
 * paging thousands of rows through the UI.
 */
export function ListDuplicateIDs(filter: $models.DuplicateFilterDTO): $CancellablePromise<string[] | null> {
    return $Call.ByID(3669120482, filter);
}

/**
 * ListDuplicates returns a page of duplicate/original pairs (newest first,
 * unfiltered). Retained for callers that do not filter; the Total is the true
 * archive-wide count.
 */
export function ListDuplicates(page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.DuplicatePairDTO>> {
    return $Call.ByID(4232984785, page, pageSize);
}

/**
 * ListDuplicatesFiltered returns a page of duplicate/original pairs matching the
 * filter. Total reflects the FILTERED count so pagination is correct within a
 * folder/session/sort selection.
 */
export function ListDuplicatesFiltered(filter: $models.DuplicateFilterDTO, page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.DuplicatePairDTO>> {
    return $Call.ByID(20873026, filter, page, pageSize);
}

/**
 * RemoveSourceOnlyRecords soft-deletes ALL source-only placeholder duplicate rows
 * (flagged duplicates with an empty archive path) in one transaction and returns
 * the count removed. It is record-only and reversible (soft delete): it NEVER
 * touches any file — there is no library copy, and the source file on the card
 * must never be touched. Archive-copy duplicates (the Duplicate Manager's real
 * workload) are untouched.
 */
export function RemoveSourceOnlyRecords(): $CancellablePromise<number> {
    return $Call.ByID(3873513570);
}

/**
 * ResolveDuplicate applies action to the duplicate asset. Actions (all require a
 * prior frontend confirmation):
 * 
 *   - delete: soft-delete the asset row AND move its physical archive file (when
 *     present) into <MasterLibrary>/.paim-trash/. The file is never hard-deleted.
 *   - move: physically move the duplicate's file to destFolder — a same-volume
 *     atomic rename, or a cross-volume copy+verify followed by trashing the
 *     original — and update CurrentArchivePath.
 *   - ignore: clear the duplicate flag and record a note (in the log; the Asset
 *     model has no notes column).
 *   - keep_both: clear the duplicate flag, keeping both files intentionally, and
 *     record a note.
 * 
 * destFolder is used only by the move action.
 */
export function ResolveDuplicate(duplicateAssetID: string, action: string, destFolder: string): $CancellablePromise<void> {
    return $Call.ByID(1261347546, duplicateAssetID, action, destFolder);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(3666370770, gate);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 */
export function SetSleepGuard(g: $models.SleepGuard | null): $CancellablePromise<void> {
    return $Call.ByID(3493343613, g);
}

/**
 * StartBulkResolve launches a background job that applies action to every
 * duplicate in ids (delete → trash + soft-delete, move → relocate, ignore /
 * keep_both → clear the flag), reusing the exact per-pair resolve logic. Only one
 * bulk resolve may run at a time (ErrBulkResolveInProgress otherwise). It is
 * cancellable between items (CancelBulkResolve), activity-tracked (quit guard),
 * and sleep-guarded; per-item failures are collected and never abort the batch.
 * Files are never hard-deleted (delete moves to the trash dir) and DB rows are
 * only soft-deleted, exactly as the per-pair action does.
 */
export function StartBulkResolve(ids: string[] | null, action: string, destFolder: string): $CancellablePromise<$models.StartBulkResolveDTO> {
    return $Call.ByID(2625103243, ids, action, destFolder);
}
