// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService drives the scan -> dry-run -> import workflow. It enforces a
 * single active import: StartImport and ResumeSession reject concurrent starts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveAnalyze returns the current analyze state for re-attachment: "running"
 * with the latest progress snapshot, "completed" with the report (or a
 * cancelled/failed marker), or "none". A completed snapshot is retained until a
 * new operation starts (see StartImport/ResumeSession/StartReorganize) or
 * analyzeReportTTL elapses, after which it lapses to "none".
 */
export function ActiveAnalyze(): $CancellablePromise<$models.ActiveAnalyzeDTO> {
    return $Call.ByID(2632687333);
}

/**
 * ActiveImport returns the latest progress snapshot of the running import, or
 * nil when nothing is running.
 */
export function ActiveImport(): $CancellablePromise<$models.ImportProgress | null> {
    return $Call.ByID(4129542162);
}

/**
 * Bind wires the ImportService to an open library's importer and repos in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(3861444354, core);
}

/**
 * CancelImport cancels the active import (if any). The pipeline finalizes the
 * session as cancelled. It is a no-op when nothing is running.
 */
export function CancelImport(): $CancellablePromise<void> {
    return $Call.ByID(4197606086);
}

/**
 * DryRun computes hashes and classifies every file against the archive, returning
 * the mode-aware prediction. It reuses a cached scan for root when present and
 * caches the resulting report so StartImport can reuse it.
 */
export function DryRun(root: string, opts: $models.ImportOptions): $CancellablePromise<$models.DryRunReportDTO> {
    return $Call.ByID(3790038963, root, opts);
}

/**
 * PickFolder opens a native directory chooser and returns the selected path, or
 * "" if the user cancelled.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(3202014584);
}

/**
 * PlanReorganize computes a non-mutating reorganize preview from the catalog and
 * caches it so a subsequent StartReorganize reuses the exact plan. eventName is
 * the (optional) event folder segment applied to the standard layout; empty
 * yields date-only YYYY-MM-DD folders. The returned DTO caps its move/skip
 * sample at reorgDisplayCap while the counts reflect the full plan.
 */
export function PlanReorganize(eventName: string): $CancellablePromise<$models.ReorganizePlanDTO | null> {
    return $Call.ByID(2236467974, eventName);
}

/**
 * ResumeSession resumes an interrupted or cancelled session by ID, in a
 * background goroutine identical to StartImport. Only one import may run at a
 * time.
 */
export function ResumeSession(sessionID: string): $CancellablePromise<$models.StartImportResult> {
    return $Call.ByID(4153050978, sessionID);
}

/**
 * ScanSource walks root, caches the scan, and returns provisional counts (no
 * hashing or duplicate detection yet).
 */
export function ScanSource(root: string): $CancellablePromise<$models.ScanSummary> {
    return $Call.ByID(152237345, root);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(1124552088, gate);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 */
export function SetSleepGuard(g: $models.SleepGuard | null): $CancellablePromise<void> {
    return $Call.ByID(1017095179, g);
}

/**
 * StartAnalyze runs scan + dry-run ("Analyze") in a background goroutine under
 * the SAME one-active-operation guard as imports and reorganizes: while an
 * analyze runs, StartImport/ResumeSession/StartReorganize are refused with
 * ErrImportInProgress, and vice versa. A running analyze is cancelled via
 * CancelImport (the same cancel plumbing imports use), which resolves it as a
 * cancelled analyze:completed.
 * 
 * It emits throttled import:progress with phase "scanning" (FilesTotal=0,
 * FilesDone=discovered count), "hashing", and "classifying". Analyze progress
 * carries an empty SessionID so the frontend can distinguish it from an import
 * or reorganize. On finish it emits analyze:completed (success/cancelled/failed)
 * and caches the scan+report exactly as DryRun does, so a later StartImport is
 * unaffected. No ImportSession is created.
 */
export function StartAnalyze(opts: $models.ImportOptions): $CancellablePromise<$models.StartAnalyzeResult> {
    return $Call.ByID(695965157, opts);
}

/**
 * StartImport creates a session (returning its ID immediately) and launches the
 * import in a background goroutine, emitting import:progress throughout and
 * import:completed at the end. Only one import may run at a time; a concurrent
 * start returns ErrImportInProgress.
 * 
 * The run is driven through pipeline.ResumeSession against the freshly created
 * session so the service owns the session ID up front and can stamp it on every
 * emitted progress event. When a fresh Analyze/dry-run for this exact root is
 * cached (see precomputedFor), its report is threaded into the run so quick and
 * full hashes are reused rather than recomputed — eliminating a full second hash
 * pass over the library. Without a cache the import re-hashes, which is correct.
 */
export function StartImport(opts: $models.ImportOptions): $CancellablePromise<$models.StartImportResult> {
    return $Call.ByID(3538574610, opts);
}

/**
 * StartReorganize creates a reorganize session (returning its ID immediately)
 * and runs it in the background under the SAME one-active-operation guard as
 * imports, emitting import:progress (phase "reorganizing") and import:completed.
 * It reuses the plan cached by a recent PlanReorganize; a stale or missing plan
 * is recomputed. Cancel via CancelImport.
 */
export function StartReorganize(): $CancellablePromise<$models.StartImportResult> {
    return $Call.ByID(1096397871);
}
