// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService manages portable libraries: reporting the current/recent
 * libraries, and creating/opening/migrating them. It is the ONE service that is
 * never gated — it is how the user gets a library open in the first place.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the running application version (for Settings → About).
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(2908880760);
}

/**
 * Create creates a new library at path (or opens it if one already exists there)
 * and opens it. path must be an existing directory.
 */
export function Create(path: string): $CancellablePromise<$models.OpenResultDTO> {
    return $Call.ByID(1486684037, path);
}

/**
 * Current returns the open library, or nil when none is open (the frontend
 * redirects to Welcome on nil).
 */
export function Current(): $CancellablePromise<$models.CurrentLibraryDTO | null> {
    return $Call.ByID(1163760450);
}

/**
 * ForceOpen opens the library at path, breaking an existing lock. It is the
 * user-confirmed override for a lock conflict.
 */
export function ForceOpen(path: string): $CancellablePromise<$models.OpenResultDTO> {
    return $Call.ByID(451676940, path);
}

/**
 * LegacyStatus reports whether a pre-library catalog exists to migrate.
 */
export function LegacyStatus(): $CancellablePromise<$models.LegacyStatusDTO> {
    return $Call.ByID(1250907944);
}

/**
 * MigrateLegacy installs the pre-library per-machine catalog into targetRoot and
 * opens it. targetRoot must be an existing directory with no library yet.
 */
export function MigrateLegacy(targetRoot: string): $CancellablePromise<$models.OpenResultDTO> {
    return $Call.ByID(328045109, targetRoot);
}

/**
 * Open opens the existing library at path. It validates that a catalog exists
 * there and returns a clear error otherwise.
 */
export function Open(path: string): $CancellablePromise<$models.OpenResultDTO> {
    return $Call.ByID(2731203569, path);
}

/**
 * PickLibraryFolder opens a native directory chooser for a library root.
 */
export function PickLibraryFolder(): $CancellablePromise<string> {
    return $Call.ByID(734359295);
}

/**
 * Recent returns the recently opened libraries (most recent first).
 */
export function Recent(): $CancellablePromise<$models.RecentLibraryDTO[] | null> {
    return $Call.ByID(570839318);
}

/**
 * SetCurrent records the currently open library. main.go calls it after a
 * successful open (including the startup open) so Current() reflects reality.
 */
export function SetCurrent(c: $models.CurrentLibraryDTO | null): $CancellablePromise<void> {
    return $Call.ByID(946804516, c);
}
