// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "../backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cleanup$0 from "../cleanup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importer$0 from "../importer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repo$0 from "../repo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as source$0 from "../source/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../gorm.io/gorm/models.js";

/**
 * AppCore is the per-library object graph: the opened catalog, its repositories,
 * and the engines that operate on it. It is built by BuildCore when a library is
 * opened and bound into the (already Wails-registered) services in place, so a
 * cold-start open needs no application restart.
 */
export class AppCore {
    /**
     * Creates a new AppCore instance.
     * @param {Partial<AppCore>} [$$source = {}] - The source object to create the AppCore.
     */
    constructor($$source = {}) {
        if (!("Root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Root"] = "";
        }
        if (!("Meta" in $$source)) {
            /**
             * @member
             * @type {db$0.Meta | null}
             */
            this["Meta"] = null;
        }
        if (!("DB" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DB | null}
             */
            this["DB"] = null;
        }
        if (!("Assets" in $$source)) {
            /**
             * @member
             * @type {repo$0.AssetRepo | null}
             */
            this["Assets"] = null;
        }
        if (!("Sessions" in $$source)) {
            /**
             * @member
             * @type {repo$0.SessionRepo | null}
             */
            this["Sessions"] = null;
        }
        if (!("Sources" in $$source)) {
            /**
             * @member
             * @type {repo$0.SourceRepo | null}
             */
            this["Sources"] = null;
        }
        if (!("Backups" in $$source)) {
            /**
             * @member
             * @type {repo$0.BackupRepo | null}
             */
            this["Backups"] = null;
        }
        if (!("Logs" in $$source)) {
            /**
             * @member
             * @type {repo$0.LogRepo | null}
             */
            this["Logs"] = null;
        }
        if (!("Settings" in $$source)) {
            /**
             * @member
             * @type {repo$0.SettingsRepo | null}
             */
            this["Settings"] = null;
        }
        if (!("Manager" in $$source)) {
            /**
             * @member
             * @type {backup$0.Manager | null}
             */
            this["Manager"] = null;
        }
        if (!("Pipeline" in $$source)) {
            /**
             * @member
             * @type {importer$0.Pipeline | null}
             */
            this["Pipeline"] = null;
        }
        if (!("Analyzer" in $$source)) {
            /**
             * @member
             * @type {cleanup$0.Analyzer | null}
             */
            this["Analyzer"] = null;
        }
        if (!("Identifier" in $$source)) {
            /**
             * @member
             * @type {source$0.Identifier | null}
             */
            this["Identifier"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppCore instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppCore}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType13;
        const $$createField8_0 = $$createType15;
        const $$createField9_0 = $$createType17;
        const $$createField10_0 = $$createType19;
        const $$createField11_0 = $$createType21;
        const $$createField12_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Meta" in $$parsedSource) {
            $$parsedSource["Meta"] = $$createField1_0($$parsedSource["Meta"]);
        }
        if ("DB" in $$parsedSource) {
            $$parsedSource["DB"] = $$createField2_0($$parsedSource["DB"]);
        }
        if ("Assets" in $$parsedSource) {
            $$parsedSource["Assets"] = $$createField3_0($$parsedSource["Assets"]);
        }
        if ("Sessions" in $$parsedSource) {
            $$parsedSource["Sessions"] = $$createField4_0($$parsedSource["Sessions"]);
        }
        if ("Sources" in $$parsedSource) {
            $$parsedSource["Sources"] = $$createField5_0($$parsedSource["Sources"]);
        }
        if ("Backups" in $$parsedSource) {
            $$parsedSource["Backups"] = $$createField6_0($$parsedSource["Backups"]);
        }
        if ("Logs" in $$parsedSource) {
            $$parsedSource["Logs"] = $$createField7_0($$parsedSource["Logs"]);
        }
        if ("Settings" in $$parsedSource) {
            $$parsedSource["Settings"] = $$createField8_0($$parsedSource["Settings"]);
        }
        if ("Manager" in $$parsedSource) {
            $$parsedSource["Manager"] = $$createField9_0($$parsedSource["Manager"]);
        }
        if ("Pipeline" in $$parsedSource) {
            $$parsedSource["Pipeline"] = $$createField10_0($$parsedSource["Pipeline"]);
        }
        if ("Analyzer" in $$parsedSource) {
            $$parsedSource["Analyzer"] = $$createField11_0($$parsedSource["Analyzer"]);
        }
        if ("Identifier" in $$parsedSource) {
            $$parsedSource["Identifier"] = $$createField12_0($$parsedSource["Identifier"]);
        }
        return new AppCore(/** @type {Partial<AppCore>} */($$parsedSource));
    }
}

/**
 * AssetDTO is the JSON-friendly projection of a domain.Asset returned across the
 * binding boundary. It omits GORM internals (soft-delete plumbing) and normalizes
 * the nullable pointer fields the frontend cares about.
 */
export class AssetDTO {
    /**
     * Creates a new AssetDTO instance.
     * @param {Partial<AssetDTO>} [$$source = {}] - The source object to create the AssetDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("originalFilename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalFilename"] = "";
        }
        if (!("originalExtension" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalExtension"] = "";
        }
        if (!("originalFullPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalFullPath"] = "";
        }
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("quickHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["quickHash"] = "";
        }
        if (!("fullHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fullHash"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (!("captureDate" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["captureDate"] = null;
        }
        if (!("importDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["importDate"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("mediaType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mediaType"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("cameraMake" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cameraMake"] = "";
        }
        if (!("cameraModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cameraModel"] = "";
        }
        if (!("currentArchivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentArchivePath"] = "";
        }
        if (!("verificationStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verificationStatus"] = "";
        }
        if (!("backupStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupStatus"] = "";
        }
        if (!("duplicateOfAssetId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["duplicateOfAssetId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetDTO(/** @type {Partial<AssetDTO>} */($$parsedSource));
    }
}

/**
 * BackupJobDTO is the JSON-friendly projection of a BackupJob joined with its
 * asset's display filename and archive path.
 */
export class BackupJobDTO {
    /**
     * Creates a new BackupJobDTO instance.
     * @param {Partial<BackupJobDTO>} [$$source = {}] - The source object to create the BackupJobDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("assetId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetId"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("archivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivePath"] = "";
        }
        if (!("plugin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plugin"] = "";
        }
        if (!("destination" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destination"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("retries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retries"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["startedAt"] = null;
        }
        if (!("completedAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["completedAt"] = null;
        }
        if (!("errorMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["errorMessage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupJobDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupJobDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupJobDTO(/** @type {Partial<BackupJobDTO>} */($$parsedSource));
    }
}

/**
 * BackupProgress is the payload for backup:progress, carrying one worker's
 * per-job upload progress.
 */
export class BackupProgress {
    /**
     * Creates a new BackupProgress instance.
     * @param {Partial<BackupProgress>} [$$source = {}] - The source object to create the BackupProgress.
     */
    constructor($$source = {}) {
        if (!("jobId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jobId"] = "";
        }
        if (!("bytesDone" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesDone"] = 0;
        }
        if (!("bytesTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupProgress(/** @type {Partial<BackupProgress>} */($$parsedSource));
    }
}

/**
 * BackupQueueChanged is the payload for backup:queue-changed, emitted after any
 * queue state transition so the frontend can refresh counts.
 */
export class BackupQueueChanged {
    /**
     * Creates a new BackupQueueChanged instance.
     * @param {Partial<BackupQueueChanged>} [$$source = {}] - The source object to create the BackupQueueChanged.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {QueueSummaryDTO}
             */
            this["summary"] = (new QueueSummaryDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupQueueChanged instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupQueueChanged}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField0_0($$parsedSource["summary"]);
        }
        return new BackupQueueChanged(/** @type {Partial<BackupQueueChanged>} */($$parsedSource));
    }
}

/**
 * BackupSummaryDTO is the dashboard's compact backup-queue view.
 */
export class BackupSummaryDTO {
    /**
     * Creates a new BackupSummaryDTO instance.
     * @param {Partial<BackupSummaryDTO>} [$$source = {}] - The source object to create the BackupSummaryDTO.
     */
    constructor($$source = {}) {
        if (!("pending" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupSummaryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupSummaryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupSummaryDTO(/** @type {Partial<BackupSummaryDTO>} */($$parsedSource));
    }
}

/**
 * ClassStatDTO is the per-class rollup in a cleanup report.
 */
export class ClassStatDTO {
    /**
     * Creates a new ClassStatDTO instance.
     * @param {Partial<ClassStatDTO>} [$$source = {}] - The source object to create the ClassStatDTO.
     */
    constructor($$source = {}) {
        if (!("class" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["class"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["files"] = [];
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassStatDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassStatDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField3_0($$parsedSource["files"]);
        }
        return new ClassStatDTO(/** @type {Partial<ClassStatDTO>} */($$parsedSource));
    }
}

/**
 * CleanupReportDTO is the JSON-friendly cleanup analysis result.
 */
export class CleanupReportDTO {
    /**
     * Creates a new CleanupReportDTO instance.
     * @param {Partial<CleanupReportDTO>} [$$source = {}] - The source object to create the CleanupReportDTO.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("classes" in $$source)) {
            /**
             * @member
             * @type {ClassStatDTO[]}
             */
            this["classes"] = [];
        }
        if (!("totalFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalFiles"] = 0;
        }
        if (!("mediaFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mediaFiles"] = 0;
        }
        if (!("nonMedia" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nonMedia"] = 0;
        }
        if (!("unreadableMedia" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadableMedia"] = 0;
        }
        if (!("archivedNotVerified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["archivedNotVerified"] = 0;
        }
        if (!("backupIncomplete" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backupIncomplete"] = 0;
        }
        if (!("dbInconsistencies" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dbInconsistencies"] = 0;
        }
        if (!("recommendation" in $$source)) {
            /**
             * @member
             * @type {RecommendationDTO}
             */
            this["recommendation"] = (new RecommendationDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupReportDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CleanupReportDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType27;
        const $$createField9_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("classes" in $$parsedSource) {
            $$parsedSource["classes"] = $$createField1_0($$parsedSource["classes"]);
        }
        if ("recommendation" in $$parsedSource) {
            $$parsedSource["recommendation"] = $$createField9_0($$parsedSource["recommendation"]);
        }
        return new CleanupReportDTO(/** @type {Partial<CleanupReportDTO>} */($$parsedSource));
    }
}

/**
 * CurrentLibraryDTO describes the library currently open, surfaced to the
 * frontend for the Settings → Library card and the root-layout gate.
 */
export class CurrentLibraryDTO {
    /**
     * Creates a new CurrentLibraryDTO instance.
     * @param {Partial<CurrentLibraryDTO>} [$$source = {}] - The source object to create the CurrentLibraryDTO.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("appVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }
        if (!("openedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["openedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrentLibraryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CurrentLibraryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CurrentLibraryDTO(/** @type {Partial<CurrentLibraryDTO>} */($$parsedSource));
    }
}

/**
 * DashboardStats is the full dashboard payload.
 */
export class DashboardStats {
    /**
     * Creates a new DashboardStats instance.
     * @param {Partial<DashboardStats>} [$$source = {}] - The source object to create the DashboardStats.
     */
    constructor($$source = {}) {
        if (!("totals" in $$source)) {
            /**
             * @member
             * @type {TotalsDTO}
             */
            this["totals"] = (new TotalsDTO());
        }
        if (!("libraryGrowth" in $$source)) {
            /**
             * @member
             * @type {MonthCountDTO[]}
             */
            this["libraryGrowth"] = [];
        }
        if (!("pendingImports" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingImports"] = 0;
        }
        if (!("backupQueue" in $$source)) {
            /**
             * @member
             * @type {BackupSummaryDTO}
             */
            this["backupQueue"] = (new BackupSummaryDTO());
        }
        if (!("duplicateCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicateCount"] = 0;
        }
        if (!("recentSources" in $$source)) {
            /**
             * @member
             * @type {SourceDTO[]}
             */
            this["recentSources"] = [];
        }
        if (!("safeToEraseSources" in $$source)) {
            /**
             * @member
             * @type {SourceDTO[]}
             */
            this["safeToEraseSources"] = [];
        }
        if (!("recentActivity" in $$source)) {
            /**
             * @member
             * @type {LogEntryDTO[]}
             */
            this["recentActivity"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DashboardStats}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType29;
        const $$createField1_0 = $$createType31;
        const $$createField3_0 = $$createType32;
        const $$createField5_0 = $$createType34;
        const $$createField6_0 = $$createType34;
        const $$createField7_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("totals" in $$parsedSource) {
            $$parsedSource["totals"] = $$createField0_0($$parsedSource["totals"]);
        }
        if ("libraryGrowth" in $$parsedSource) {
            $$parsedSource["libraryGrowth"] = $$createField1_0($$parsedSource["libraryGrowth"]);
        }
        if ("backupQueue" in $$parsedSource) {
            $$parsedSource["backupQueue"] = $$createField3_0($$parsedSource["backupQueue"]);
        }
        if ("recentSources" in $$parsedSource) {
            $$parsedSource["recentSources"] = $$createField5_0($$parsedSource["recentSources"]);
        }
        if ("safeToEraseSources" in $$parsedSource) {
            $$parsedSource["safeToEraseSources"] = $$createField6_0($$parsedSource["safeToEraseSources"]);
        }
        if ("recentActivity" in $$parsedSource) {
            $$parsedSource["recentActivity"] = $$createField7_0($$parsedSource["recentActivity"]);
        }
        return new DashboardStats(/** @type {Partial<DashboardStats>} */($$parsedSource));
    }
}

/**
 * DryRunReportDTO is the JSON-friendly projection of importer.DryRunReport. It
 * omits the carried-forward hash maps (an internal optimization) and exposes the
 * mode-aware planning counts.
 */
export class DryRunReportDTO {
    /**
     * Creates a new DryRunReportDTO instance.
     * @param {Partial<DryRunReportDTO>} [$$source = {}] - The source object to create the DryRunReportDTO.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("reorganize" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reorganize"] = false;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("photos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["photos"] = 0;
        }
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["videos"] = 0;
        }
        if (!("alreadyImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alreadyImported"] = 0;
        }
        if (!("duplicates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicates"] = 0;
        }
        if (!("new" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["new"] = 0;
        }
        if (!("totalImportBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalImportBytes"] = 0;
        }
        if (!("estimatedSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["estimatedSeconds"] = 0;
        }
        if (!("plannedAdoptions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["plannedAdoptions"] = 0;
        }
        if (!("plannedMoves" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["plannedMoves"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DryRunReportDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DryRunReportDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DryRunReportDTO(/** @type {Partial<DryRunReportDTO>} */($$parsedSource));
    }
}

/**
 * DuplicatePairDTO pairs a duplicate asset with the original it duplicates.
 */
export class DuplicatePairDTO {
    /**
     * Creates a new DuplicatePairDTO instance.
     * @param {Partial<DuplicatePairDTO>} [$$source = {}] - The source object to create the DuplicatePairDTO.
     */
    constructor($$source = {}) {
        if (!("duplicate" in $$source)) {
            /**
             * @member
             * @type {AssetDTO}
             */
            this["duplicate"] = (new AssetDTO());
        }
        if (!("original" in $$source)) {
            /**
             * @member
             * @type {AssetDTO}
             */
            this["original"] = (new AssetDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DuplicatePairDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DuplicatePairDTO}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType37;
        const $$createField1_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("duplicate" in $$parsedSource) {
            $$parsedSource["duplicate"] = $$createField0_0($$parsedSource["duplicate"]);
        }
        if ("original" in $$parsedSource) {
            $$parsedSource["original"] = $$createField1_0($$parsedSource["original"]);
        }
        return new DuplicatePairDTO(/** @type {Partial<DuplicatePairDTO>} */($$parsedSource));
    }
}

/**
 * ImportCompleted is the payload for import:completed, emitted once when a
 * background import goroutine finishes (successfully, cancelled, or interrupted).
 */
export class ImportCompleted {
    /**
     * Creates a new ImportCompleted instance.
     * @param {Partial<ImportCompleted>} [$$source = {}] - The source object to create the ImportCompleted.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("filesScanned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesScanned"] = 0;
        }
        if (!("filesImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesImported"] = 0;
        }
        if (!("duplicates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicates"] = 0;
        }
        if (!("failures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failures"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportCompleted instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportCompleted}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportCompleted(/** @type {Partial<ImportCompleted>} */($$parsedSource));
    }
}

/**
 * ImportOptions configures StartImport. Root is the source tree. DestinationRoot
 * defaults to the configured Master Library when empty. Mode is "copy" or
 * "adopt"; Reorganize (adopt only) moves files into the standard layout.
 */
export class ImportOptions {
    /**
     * Creates a new ImportOptions instance.
     * @param {Partial<ImportOptions>} [$$source = {}] - The source object to create the ImportOptions.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("destinationRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destinationRoot"] = "";
        }
        if (!("eventName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventName"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("reorganize" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reorganize"] = false;
        }
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportOptions(/** @type {Partial<ImportOptions>} */($$parsedSource));
    }
}

/**
 * ImportProgress is the payload for import:progress. It mirrors importer.Progress
 * plus the owning session ID (so the frontend can correlate updates) and a
 * derived completion percentage.
 */
export class ImportProgress {
    /**
     * Creates a new ImportProgress instance.
     * @param {Partial<ImportProgress>} [$$source = {}] - The source object to create the ImportProgress.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("filesDone" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesDone"] = 0;
        }
        if (!("filesTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesTotal"] = 0;
        }
        if (!("bytesDone" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesDone"] = 0;
        }
        if (!("bytesTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesTotal"] = 0;
        }
        if (!("currentFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentFile"] = "";
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["errors"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportProgress(/** @type {Partial<ImportProgress>} */($$parsedSource));
    }
}

/**
 * LegacyStatusDTO reports whether a pre-library per-machine catalog exists (so
 * Welcome can offer to migrate it).
 */
export class LegacyStatusDTO {
    /**
     * Creates a new LegacyStatusDTO instance.
     * @param {Partial<LegacyStatusDTO>} [$$source = {}] - The source object to create the LegacyStatusDTO.
     */
    constructor($$source = {}) {
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LegacyStatusDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LegacyStatusDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LegacyStatusDTO(/** @type {Partial<LegacyStatusDTO>} */($$parsedSource));
    }
}

/**
 * LibraryGate is the shared open/closed switch every DB-backed service consults.
 * It is closed until a library is opened (at startup or from Welcome) and reopens
 * atomically once the object graph is bound in place. A nil *LibraryGate is
 * treated as always-open, so services constructed directly in unit tests (which
 * pass no gate) are never gated.
 */
export class LibraryGate {
    /**
     * Creates a new LibraryGate instance.
     * @param {Partial<LibraryGate>} [$$source = {}] - The source object to create the LibraryGate.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryGate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LibraryGate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryGate(/** @type {Partial<LibraryGate>} */($$parsedSource));
    }
}

/**
 * LockConflictDTO carries the structured details of a refused lock so the
 * frontend can present an informed Force Open confirmation.
 */
export class LockConflictDTO {
    /**
     * Creates a new LockConflictDTO instance.
     * @param {Partial<LockConflictDTO>} [$$source = {}] - The source object to create the LockConflictDTO.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("sameHostLive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["sameHostLive"] = false;
        }
        if (!("heartbeatAgeSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heartbeatAgeSeconds"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LockConflictDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LockConflictDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LockConflictDTO(/** @type {Partial<LockConflictDTO>} */($$parsedSource));
    }
}

/**
 * LogEntryDTO is the JSON-friendly projection of a persisted LogEntry.
 */
export class LogEntryDTO {
    /**
     * Creates a new LogEntryDTO instance.
     * @param {Partial<LogEntryDTO>} [$$source = {}] - The source object to create the LogEntryDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("subsystem" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subsystem"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("metadataJson" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["metadataJson"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntryDTO(/** @type {Partial<LogEntryDTO>} */($$parsedSource));
    }
}

/**
 * MatchDTO is the JSON-friendly result of identifying a volume.
 */
export class MatchDTO {
    /**
     * Creates a new MatchDTO instance.
     * @param {Partial<MatchDTO>} [$$source = {}] - The source object to create the MatchDTO.
     */
    constructor($$source = {}) {
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {SourceDTO}
             */
            this["source"] = (new SourceDTO());
        }
        if (!("confidence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidence"] = 0;
        }
        if (!("reasons" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["reasons"] = [];
        }
        if (!("isKnown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isKnown"] = false;
        }
        if (!("contentsPreviouslyImported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["contentsPreviouslyImported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MatchDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType33;
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField1_0($$parsedSource["source"]);
        }
        if ("reasons" in $$parsedSource) {
            $$parsedSource["reasons"] = $$createField3_0($$parsedSource["reasons"]);
        }
        return new MatchDTO(/** @type {Partial<MatchDTO>} */($$parsedSource));
    }
}

/**
 * MonthCountDTO is one point in the library growth series.
 */
export class MonthCountDTO {
    /**
     * Creates a new MonthCountDTO instance.
     * @param {Partial<MonthCountDTO>} [$$source = {}] - The source object to create the MonthCountDTO.
     */
    constructor($$source = {}) {
        if (!("month" in $$source)) {
            /**
             * YYYY-MM
             * @member
             * @type {string}
             */
            this["month"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonthCountDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MonthCountDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonthCountDTO(/** @type {Partial<MonthCountDTO>} */($$parsedSource));
    }
}

/**
 * OpenResultDTO is returned by Create/Open/ForceOpen/MigrateLegacy. Exactly one
 * of {Library set}, {LockConflict set}, or {NeedsRelaunch true} is meaningful:
 *   - Library set, NeedsRelaunch false: opened in place, frontend can proceed.
 *   - NeedsRelaunch true: a different library was already open; config was
 *     updated and the app must relaunch to switch (frontend prompts).
 *   - LockConflict set: the library is locked; frontend offers Force Open.
 */
export class OpenResultDTO {
    /**
     * Creates a new OpenResultDTO instance.
     * @param {Partial<OpenResultDTO>} [$$source = {}] - The source object to create the OpenResultDTO.
     */
    constructor($$source = {}) {
        if (!("needsRelaunch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsRelaunch"] = false;
        }
        if (!("library" in $$source)) {
            /**
             * @member
             * @type {CurrentLibraryDTO | null}
             */
            this["library"] = null;
        }
        if (!("lockConflict" in $$source)) {
            /**
             * @member
             * @type {LockConflictDTO | null}
             */
            this["lockConflict"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenResultDTO}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType39;
        const $$createField2_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("library" in $$parsedSource) {
            $$parsedSource["library"] = $$createField1_0($$parsedSource["library"]);
        }
        if ("lockConflict" in $$parsedSource) {
            $$parsedSource["lockConflict"] = $$createField2_0($$parsedSource["lockConflict"]);
        }
        return new OpenResultDTO(/** @type {Partial<OpenResultDTO>} */($$parsedSource));
    }
}

/**
 * PageResult wraps a paginated slice with its total match count so tables can
 * render pagination controls.
 * @template T
 */
export class PageResult {
    /**
     * Creates a new PageResult instance.
     * @param {Partial<PageResult<T>>} [$$source = {}] - The source object to create the PageResult.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {T[]}
             */
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class PageResult.
     * @template [T=any]
     * @param {(source: any) => T} $$createParamT
     * @returns {($$source?: any) => PageResult<T>}
     */
    static createFrom($$createParamT) {
        const $$createField0_0 = $$createType42($$createParamT);
        return ($$source = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("items" in $$parsedSource) {
                $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
            }
            return new PageResult(/** @type {Partial<PageResult<T>>} */($$parsedSource));
        };
    }
}

/**
 * PluginDTO describes an available backup plugin and its capabilities.
 */
export class PluginDTO {
    /**
     * Creates a new PluginDTO instance.
     * @param {Partial<PluginDTO>} [$$source = {}] - The source object to create the PluginDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("supportsVerify" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supportsVerify"] = false;
        }
        if (!("supportsDelete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supportsDelete"] = false;
        }
        if (!("supportsResume" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supportsResume"] = false;
        }
        if (!("maxFileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxFileSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginDTO(/** @type {Partial<PluginDTO>} */($$parsedSource));
    }
}

/**
 * ProviderDTO is the JSON-friendly projection of a BackupProvider.
 */
export class ProviderDTO {
    /**
     * Creates a new ProviderDTO instance.
     * @param {Partial<ProviderDTO>} [$$source = {}] - The source object to create the ProviderDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("pluginName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginName"] = "";
        }
        if (!("configJson" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configJson"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderDTO(/** @type {Partial<ProviderDTO>} */($$parsedSource));
    }
}

/**
 * QueueSummaryDTO reports the number of backup jobs in each status.
 */
export class QueueSummaryDTO {
    /**
     * Creates a new QueueSummaryDTO instance.
     * @param {Partial<QueueSummaryDTO>} [$$source = {}] - The source object to create the QueueSummaryDTO.
     */
    constructor($$source = {}) {
        if (!("pending" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["running"] = 0;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["paused"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cancelled"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueSummaryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueueSummaryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueSummaryDTO(/** @type {Partial<QueueSummaryDTO>} */($$parsedSource));
    }
}

/**
 * RecentLibraryDTO is one entry in the recent-libraries list.
 */
export class RecentLibraryDTO {
    /**
     * Creates a new RecentLibraryDTO instance.
     * @param {Partial<RecentLibraryDTO>} [$$source = {}] - The source object to create the RecentLibraryDTO.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("lastOpenedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastOpenedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentLibraryDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentLibraryDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentLibraryDTO(/** @type {Partial<RecentLibraryDTO>} */($$parsedSource));
    }
}

/**
 * RecommendationDTO is the delete-safety verdict.
 */
export class RecommendationDTO {
    /**
     * Creates a new RecommendationDTO instance.
     * @param {Partial<RecommendationDTO>} [$$source = {}] - The source object to create the RecommendationDTO.
     */
    constructor($$source = {}) {
        if (!("safeToDelete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["safeToDelete"] = false;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("reasons" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["reasons"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecommendationDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecommendationDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasons" in $$parsedSource) {
            $$parsedSource["reasons"] = $$createField3_0($$parsedSource["reasons"]);
        }
        return new RecommendationDTO(/** @type {Partial<RecommendationDTO>} */($$parsedSource));
    }
}

/**
 * ReorganizeMoveDTO is one planned same-drive move in a reorganize preview.
 */
export class ReorganizeMoveDTO {
    /**
     * Creates a new ReorganizeMoveDTO instance.
     * @param {Partial<ReorganizeMoveDTO>} [$$source = {}] - The source object to create the ReorganizeMoveDTO.
     */
    constructor($$source = {}) {
        if (!("assetId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetId"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReorganizeMoveDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReorganizeMoveDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReorganizeMoveDTO(/** @type {Partial<ReorganizeMoveDTO>} */($$parsedSource));
    }
}

/**
 * ReorganizePlanDTO is the JSON-friendly reorganize preview: aggregate counts
 * plus a display-capped sample of moves and skips. Truncated reports whether the
 * move sample was cut to DisplayCap (the counts remain exact).
 */
export class ReorganizePlanDTO {
    /**
     * Creates a new ReorganizePlanDTO instance.
     * @param {Partial<ReorganizePlanDTO>} [$$source = {}] - The source object to create the ReorganizePlanDTO.
     */
    constructor($$source = {}) {
        if (!("totalAssets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalAssets"] = 0;
        }
        if (!("inPlace" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inPlace"] = 0;
        }
        if (!("moves" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["moves"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("displayCap" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["displayCap"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("movesSample" in $$source)) {
            /**
             * @member
             * @type {ReorganizeMoveDTO[]}
             */
            this["movesSample"] = [];
        }
        if (!("skippedSample" in $$source)) {
            /**
             * @member
             * @type {ReorganizeSkipDTO[]}
             */
            this["skippedSample"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReorganizePlanDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReorganizePlanDTO}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType44;
        const $$createField7_0 = $$createType46;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("movesSample" in $$parsedSource) {
            $$parsedSource["movesSample"] = $$createField6_0($$parsedSource["movesSample"]);
        }
        if ("skippedSample" in $$parsedSource) {
            $$parsedSource["skippedSample"] = $$createField7_0($$parsedSource["skippedSample"]);
        }
        return new ReorganizePlanDTO(/** @type {Partial<ReorganizePlanDTO>} */($$parsedSource));
    }
}

/**
 * ReorganizeSkipDTO is one asset the reorganize will not move, with the reason
 * (missing-on-disk, cross-volume, duplicate).
 */
export class ReorganizeSkipDTO {
    /**
     * Creates a new ReorganizeSkipDTO instance.
     * @param {Partial<ReorganizeSkipDTO>} [$$source = {}] - The source object to create the ReorganizeSkipDTO.
     */
    constructor($$source = {}) {
        if (!("assetId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetId"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReorganizeSkipDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReorganizeSkipDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReorganizeSkipDTO(/** @type {Partial<ReorganizeSkipDTO>} */($$parsedSource));
    }
}

/**
 * SafeToEraseDTO is the JSON-friendly safe-to-erase report.
 */
export class SafeToEraseDTO {
    /**
     * Creates a new SafeToEraseDTO instance.
     * @param {Partial<SafeToEraseDTO>} [$$source = {}] - The source object to create the SafeToEraseDTO.
     */
    constructor($$source = {}) {
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }
        if (!("safe" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["safe"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("totalMedia" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalMedia"] = 0;
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["archived"] = 0;
        }
        if (!("new" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["new"] = 0;
        }
        if (!("unverified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unverified"] = 0;
        }
        if (!("backupIncomplete" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backupIncomplete"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SafeToEraseDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SafeToEraseDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SafeToEraseDTO(/** @type {Partial<SafeToEraseDTO>} */($$parsedSource));
    }
}

/**
 * ScanSummary is the provisional result of scanning a source tree, before any
 * hashing or duplicate detection.
 */
export class ScanSummary {
    /**
     * Creates a new ScanSummary instance.
     * @param {Partial<ScanSummary>} [$$source = {}] - The source object to create the ScanSummary.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("photos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["photos"] = 0;
        }
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["videos"] = 0;
        }
        if (!("rawPhotos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rawPhotos"] = 0;
        }
        if (!("provisionalPairs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["provisionalPairs"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanSummary(/** @type {Partial<ScanSummary>} */($$parsedSource));
    }
}

/**
 * SessionDTO is the JSON-friendly projection of an ImportSession. Mode is decoded
 * from the session's resume-state notes so the Import History can badge adopt
 * runs distinctly from copy runs.
 */
export class SessionDTO {
    /**
     * Creates a new SessionDTO instance.
     * @param {Partial<SessionDTO>} [$$source = {}] - The source object to create the SessionDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("completedAt" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["completedAt"] = null;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }
        if (!("destinationRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destinationRoot"] = "";
        }
        if (!("filesScanned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesScanned"] = 0;
        }
        if (!("filesImported" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesImported"] = 0;
        }
        if (!("duplicates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicates"] = 0;
        }
        if (!("failures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failures"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionDTO(/** @type {Partial<SessionDTO>} */($$parsedSource));
    }
}

/**
 * SessionDetail bundles a session with the log entries produced during its run.
 */
export class SessionDetail {
    /**
     * Creates a new SessionDetail instance.
     * @param {Partial<SessionDetail>} [$$source = {}] - The source object to create the SessionDetail.
     */
    constructor($$source = {}) {
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {SessionDTO}
             */
            this["session"] = (new SessionDTO());
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {LogEntryDTO[]}
             */
            this["events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType47;
        const $$createField1_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField1_0($$parsedSource["events"]);
        }
        return new SessionDetail(/** @type {Partial<SessionDetail>} */($$parsedSource));
    }
}

/**
 * Settings is the typed, JSON-friendly view of PAIM's configuration returned by
 * SettingsService.GetAll and consumed by main.go to drive the archive layout,
 * backup worker pool, and import concurrency. MetadataAvailable is read-only,
 * derived at runtime from whether exiftool (or the fallback) can extract data.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("masterLibraryRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["masterLibraryRoot"] = "";
        }
        if (!("backupWorkers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backupWorkers"] = 0;
        }
        if (!("maxRetries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRetries"] = 0;
        }
        if (!("importConcurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["importConcurrency"] = 0;
        }
        if (!("defaultEventName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultEventName"] = "";
        }
        if (!("metadataAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["metadataAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * SourceDTO is the JSON-friendly projection of an ImportSource.
 */
export class SourceDTO {
    /**
     * Creates a new SourceDTO instance.
     * @param {Partial<SourceDTO>} [$$source = {}] - The source object to create the SourceDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sourceType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceType"] = "";
        }
        if (!("hardwareSerial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hardwareSerial"] = "";
        }
        if (!("filesystemUuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filesystemUuid"] = "";
        }
        if (!("volumeUuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["volumeUuid"] = "";
        }
        if (!("volumeLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["volumeLabel"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("capacityBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacityBytes"] = 0;
        }
        if (!("connectionType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectionType"] = "";
        }
        if (!("confidence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidence"] = 0;
        }
        if (!("confidenceReason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["confidenceReason"] = "";
        }
        if (!("lastSeenAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSeenAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("importCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["importCount"] = 0;
        }
        if (!("safeToErase" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["safeToErase"] = false;
        }
        if (!("safeToEraseReason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["safeToEraseReason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceDTO(/** @type {Partial<SourceDTO>} */($$parsedSource));
    }
}

/**
 * SourceIdentified is the payload for source:identified, emitted after a volume
 * is identified and persisted.
 */
export class SourceIdentified {
    /**
     * Creates a new SourceIdentified instance.
     * @param {Partial<SourceIdentified>} [$$source = {}] - The source object to create the SourceIdentified.
     */
    constructor($$source = {}) {
        if (!("mountPoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mountPoint"] = "";
        }
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }
        if (!("confidence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["confidence"] = 0;
        }
        if (!("isKnown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isKnown"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceIdentified instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceIdentified}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceIdentified(/** @type {Partial<SourceIdentified>} */($$parsedSource));
    }
}

/**
 * StartImportResult is returned immediately from StartImport once the session is
 * created and the background run has been launched.
 */
export class StartImportResult {
    /**
     * Creates a new StartImportResult instance.
     * @param {Partial<StartImportResult>} [$$source = {}] - The source object to create the StartImportResult.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartImportResult(/** @type {Partial<StartImportResult>} */($$parsedSource));
    }
}

/**
 * TotalsDTO holds the library totals.
 */
export class TotalsDTO {
    /**
     * Creates a new TotalsDTO instance.
     * @param {Partial<TotalsDTO>} [$$source = {}] - The source object to create the TotalsDTO.
     */
    constructor($$source = {}) {
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["assets"] = 0;
        }
        if (!("photos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["photos"] = 0;
        }
        if (!("videos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["videos"] = 0;
        }
        if (!("livePhotos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["livePhotos"] = 0;
        }
        if (!("storageBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["storageBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TotalsDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TotalsDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TotalsDTO(/** @type {Partial<TotalsDTO>} */($$parsedSource));
    }
}

/**
 * VolumeDTO is the JSON-friendly projection of a mounted volume description.
 */
export class VolumeDTO {
    /**
     * Creates a new VolumeDTO instance.
     * @param {Partial<VolumeDTO>} [$$source = {}] - The source object to create the VolumeDTO.
     */
    constructor($$source = {}) {
        if (!("mountPoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mountPoint"] = "";
        }
        if (!("volumeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["volumeName"] = "";
        }
        if (!("volumeUuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["volumeUuid"] = "";
        }
        if (!("filesystemUuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filesystemUuid"] = "";
        }
        if (!("filesystemType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filesystemType"] = "";
        }
        if (!("capacityBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacityBytes"] = 0;
        }
        if (!("freeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["freeBytes"] = 0;
        }
        if (!("removable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["removable"] = false;
        }
        if (!("internal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["internal"] = false;
        }
        if (!("ejectable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ejectable"] = false;
        }
        if (!("connectionType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectionType"] = "";
        }
        if (!("hardwareSerial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hardwareSerial"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("isNetworkVolume" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isNetworkVolume"] = false;
        }
        if (!("networkUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["networkUrl"] = "";
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumeDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VolumeDTO}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField16_0($$parsedSource["warnings"]);
        }
        return new VolumeDTO(/** @type {Partial<VolumeDTO>} */($$parsedSource));
    }
}

/**
 * VolumeEvent is the payload for volume:mounted and volume:unmounted.
 */
export class VolumeEvent {
    /**
     * Creates a new VolumeEvent instance.
     * @param {Partial<VolumeEvent>} [$$source = {}] - The source object to create the VolumeEvent.
     */
    constructor($$source = {}) {
        if (!("mountPoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mountPoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumeEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VolumeEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VolumeEvent(/** @type {Partial<VolumeEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = db$0.Meta.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = gorm$0.DB.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = repo$0.AssetRepo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = repo$0.SessionRepo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = repo$0.SourceRepo.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = repo$0.BackupRepo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = repo$0.LogRepo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = repo$0.SettingsRepo.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = backup$0.Manager.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = importer$0.Pipeline.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = cleanup$0.Analyzer.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = source$0.Identifier.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = QueueSummaryDTO.createFrom;
const $$createType25 = $Create.Array($Create.Any);
const $$createType26 = ClassStatDTO.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = RecommendationDTO.createFrom;
const $$createType29 = TotalsDTO.createFrom;
const $$createType30 = MonthCountDTO.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = BackupSummaryDTO.createFrom;
const $$createType33 = SourceDTO.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = LogEntryDTO.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = AssetDTO.createFrom;
const $$createType38 = CurrentLibraryDTO.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = LockConflictDTO.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = /** @type {(...args: any[]) => any} */(($$createParamT) => $Create.Array($$createParamT));
const $$createType43 = ReorganizeMoveDTO.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = ReorganizeSkipDTO.createFrom;
const $$createType46 = $Create.Array($$createType45);
const $$createType47 = SessionDTO.createFrom;
