// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "../backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cleanup$0 from "../cleanup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importer$0 from "../importer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repo$0 from "../repo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as source$0 from "../source/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as thumbs$0 from "../thumbs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as volumes$0 from "../volumes/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../gorm.io/gorm/models.js";

/**
 * ActiveAnalyzeDTO is the re-attachment snapshot returned by ActiveAnalyze.
 * State is "running" (Progress holds the latest snapshot), "completed" (Report,
 * or Cancelled/Error for a cancelled/failed run, is populated), or "none".
 * Opts echoes the normalized request so the frontend can restore the whole
 * step-2 context (root, mode, reorganize, event) after navigation.
 */
export interface ActiveAnalyzeDTO {
    "state": string;
    "opts": ImportOptions;
    "progress": ImportProgress | null;
    "report": DryRunReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * ActiveBulkResolveDTO is the re-attachment snapshot for a bulk resolve: "running"
 * (Progress holds the latest snapshot), "completed" (Summary, possibly Cancelled),
 * or "none". A completed snapshot lapses to "none" after safeEraseReportTTL.
 */
export interface ActiveBulkResolveDTO {
    "state": string;
    "progress": BulkResolveProgress | null;
    "summary": BulkResolveSummaryDTO | null;
    "cancelled": boolean;
}

/**
 * ActiveCleanupAnalyzeDTO is the re-attachment snapshot returned by
 * ActiveCleanupAnalyze. State is "running" (Progress holds the latest snapshot),
 * "completed" (Report, or Cancelled/Error, is populated), or "none". Root echoes
 * the request so the frontend can restore context after navigation.
 */
export interface ActiveCleanupAnalyzeDTO {
    "state": string;
    "root": string;
    "progress": CleanupProgress | null;
    "report": CleanupReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * ActiveClearSourceDTO is the re-attachment snapshot for a clear job: "running"
 * (Progress holds the latest snapshot), "completed" (Result, or Cancelled/Error),
 * or "none". A completed snapshot lapses to "none" after safeEraseReportTTL.
 */
export interface ActiveClearSourceDTO {
    "state": string;
    "root": string;
    "progress": SourceProgress | null;
    "result": ClearSourceResultDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * ActiveSafeToEraseDTO is the re-attachment snapshot returned by
 * ActiveSafeToErase. State is "running" (Progress holds the latest snapshot),
 * "completed" (Report, or Cancelled/Error, is populated), or "none". MountPoint
 * and SourceID echo the request so the frontend can restore the volume card.
 */
export interface ActiveSafeToEraseDTO {
    "state": string;
    "mountPoint": string;
    "sourceId": string;
    "progress": SourceProgress | null;
    "report": SafeToEraseDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * AnalyzeCompleted is the payload for analyze:completed, emitted once when a
 * background analyze (scan + dry run) goroutine finishes. Exactly one of the
 * terminal states holds:
 *   - success: Report is non-nil, Cancelled=false, Error=="".
 *   - cancelled (via CancelImport): Report=nil, Cancelled=true.
 *   - failed: Report=nil, Error carries the message.
 * 
 * Root and Opts echo the (normalized) request so the frontend can restore the
 * whole step-2 context on re-attach without re-deriving it.
 */
export interface AnalyzeCompleted {
    "root": string;
    "opts": ImportOptions;
    "report": DryRunReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * AppCore is the per-library object graph: the opened catalog, its repositories,
 * and the engines that operate on it. It is built by BuildCore when a library is
 * opened and bound into the (already Wails-registered) services in place, so a
 * cold-start open needs no application restart.
 */
export interface AppCore {
    "Root": string;
    "Meta": db$0.Meta | null;
    "DB": gorm$0.DB | null;
    "Assets": repo$0.AssetRepo | null;
    "Sessions": repo$0.SessionRepo | null;
    "Failures": repo$0.ImportFailureRepo | null;
    "Sources": repo$0.SourceRepo | null;
    "Backups": repo$0.BackupRepo | null;
    "Logs": repo$0.LogRepo | null;
    "Settings": repo$0.SettingsRepo | null;
    "Manager": backup$0.Manager | null;
    "Pipeline": importer$0.Pipeline | null;
    "Analyzer": cleanup$0.Analyzer | null;
    "Identifier": source$0.Identifier | null;

    /**
     * Collector enumerates/describes mounted volumes. It is library-independent
     * (owned by main.go, passed through CoreDeps) but carried here so services
     * bound to the core — e.g. the ImportService source auto-link — can reach it
     * without a separate wiring path.
     */
    "Collector": volumes$0.Collector | null;

    /**
     * Thumbs is this library's disposable thumbnail cache
     * (<root>/.paim/thumbs). The thumbnail HTTP handler serves from it.
     */
    "Thumbs": thumbs$0.Cache | null;
}

/**
 * AssetDTO is the JSON-friendly projection of a domain.Asset returned across the
 * binding boundary. It omits GORM internals (soft-delete plumbing) and normalizes
 * the nullable pointer fields the frontend cares about.
 */
export interface AssetDTO {
    "id": string;
    "originalFilename": string;
    "originalExtension": string;
    "originalFullPath": string;
    "sourceId": string;
    "sessionId": string;
    "quickHash": string;
    "fullHash": string;
    "fileSize": number;
    "captureDate": string | null;
    "importDate": string;
    "mediaType": string;
    "width": number;
    "height": number;
    "durationSeconds": number;
    "cameraMake": string;
    "cameraModel": string;
    "currentArchivePath": string;
    "verificationStatus": string;
    "backupStatus": string;
    "duplicateOfAssetId": string;
}

/**
 * AssetDetailDTO is the full provenance record shown in the detail drawer.
 */
export interface AssetDetailDTO {
    "id": string;
    "originalFilename": string;
    "originalExtension": string;
    "originalFullPath": string;

    /**
     * resolved absolute
     */
    "currentArchivePath": string;
    "quickHash": string;
    "fullHash": string;
    "fileSize": number;
    "captureDate": string | null;
    "importDate": string;
    "mediaType": string;
    "width": number;
    "height": number;
    "durationSeconds": number;
    "cameraMake": string;
    "cameraModel": string;
    "lens": string;
    "iso": number;
    "shutterSpeed": string;
    "aperture": string;
    "gpsLatitude": number | null;
    "gpsLongitude": number | null;
    "verificationStatus": string;
    "backupStatus": string;
    "isLivePhotoPair": boolean;
    "sourceId": string;
    "sourceLabel": string;
    "sourceType": string;
    "sessionId": string;
    "sessionDate": string | null;
    "backupJobs": BackupJobRefDTO[] | null;
    "duplicateOf": AssetRefDTO | null;
    "duplicates": AssetRefDTO[] | null;
    "livePhotoPartner": AssetRefDTO | null;
}

/**
 * AssetRefDTO is a slim reference to a related asset (duplicate/original/Live
 * Photo partner) used for in-drawer navigation.
 */
export interface AssetRefDTO {
    "id": string;
    "filename": string;
    "mediaType": string;
    "captureDate": string | null;
}

/**
 * AssetsOverTimeBucketDTO is one bar of the assets-over-time chart: a labeled
 * effective-capture-time bucket with its photo/video split.
 */
export interface AssetsOverTimeBucketDTO {
    /**
     * human bucket label ("2026-07", "2020–2024", …)
     */
    "label": string;

    /**
     * ISO date (YYYY-MM-DD) at the bucket's start
     */
    "start": string;

    /**
     * photo + raw_photo + live_photo_pair
     */
    "photos": number;
    "videos": number;
}

/**
 * AssetsOverTimeDTO is the capture-date distribution shown on the dashboard,
 * bucketed at the resolved granularity. Buckets are keyed on
 * COALESCE(capture_date, import_date), so assets with no capture date land in their
 * import-date bucket — TotalUndatedFallback counts how many, surfaced as a footnote.
 * Windowed is true when Buckets cover only part of [RangeStart, RangeEnd] (the Day
 * view's most-recent-120-days window, or the maxBuckets safety trim); the UI shows
 * the full range so the window is honest.
 */
export interface AssetsOverTimeDTO {
    /**
     * resolved concrete granularity
     */
    "granularity": string;
    "buckets": AssetsOverTimeBucketDTO[] | null;
    "windowed": boolean;

    /**
     * ISO date, "" when empty
     */
    "rangeStart": string;
    "rangeEnd": string;
    "totalUndatedFallback": number;
}

/**
 * BackfillStatusDTO is the re-attachment snapshot of the current provider backfill
 * (or the initial status returned by StartBackfill). Done/Total count eligible
 * assets scanned; ProviderID names the destination being filled.
 */
export interface BackfillStatusDTO {
    "running": boolean;
    "providerId": string;
    "done": number;
    "total": number;
}

/**
 * BackupBackfillCompleted is the payload for backup:backfill-completed, emitted
 * once when a provider backfill finishes (or is cancelled). Enqueued is how many
 * new backup jobs it created; Skipped is how many eligible assets already had a
 * job for the provider (idempotent no-ops). Cancelled is true when the run was
 * stopped early — a later run resumes and enqueues the remainder.
 */
export interface BackupBackfillCompleted {
    "providerId": string;
    "enqueued": number;
    "skipped": number;
    "cancelled": boolean;
}

/**
 * BackupBackfillProgress is the payload for backup:backfill-progress, emitted
 * (throttled) while a provider backfill enqueues jobs for a library's existing
 * assets. ProviderID names the destination being filled; Done/Total count
 * eligible assets scanned. Running is false only on the terminal tick (paired
 * with a backup:backfill-completed event carrying the final counts).
 */
export interface BackupBackfillProgress {
    "providerId": string;
    "done": number;
    "total": number;
    "running": boolean;
}

/**
 * BackupJobDTO is the JSON-friendly projection of a BackupJob joined with its
 * asset's display filename and archive path.
 */
export interface BackupJobDTO {
    "id": string;
    "assetId": string;
    "filename": string;
    "archivePath": string;
    "plugin": string;
    "destination": string;
    "status": string;
    "retries": number;
    "startedAt": string | null;
    "completedAt": string | null;
    "errorMessage": string;
}

/**
 * BackupJobRefDTO is the compact per-asset backup-job view in the detail drawer.
 */
export interface BackupJobRefDTO {
    "plugin": string;
    "destination": string;
    "status": string;
    "completedAt": string | null;
}

/**
 * BackupProgress is the payload for backup:progress, carrying one worker's
 * per-job upload progress.
 */
export interface BackupProgress {
    "jobId": string;
    "bytesDone": number;
    "bytesTotal": number;
}

/**
 * BackupProviderFailing is the payload for backup:provider-failing, emitted once
 * (throttled per provider in the Manager) when a destination crosses the failing
 * edge. It drives a single low-frequency toast ("Backups to <name> are failing").
 * ProviderName is a best-effort human label (rclone remote / localfs root / plugin
 * name), falling back to ProviderID.
 */
export interface BackupProviderFailing {
    "providerId": string;
    "providerName": string;
}

/**
 * BackupQueueChanged is the payload for backup:queue-changed, emitted after any
 * queue state transition so the frontend can refresh counts.
 */
export interface BackupQueueChanged {
    "summary": QueueSummaryDTO;
}

/**
 * BackupReconcileCompleted is the payload for backup:reconcile-completed, emitted
 * once when a "recalculate queue" reconcile finishes (or is cancelled). Cancelled
 * is how many out-of-scope pending/paused jobs it cancelled; Enqueued is how many
 * in-scope missing jobs it created. Aborted is true when the run was stopped early
 * (the cancel step still applied; the enqueue phase may be partial and resumes on a
 * later run). It drives the "Removed X · Queued Y" toast.
 */
export interface BackupReconcileCompleted {
    "providerId": string;
    "cancelled": number;
    "enqueued": number;
    "aborted": boolean;
}

/**
 * BackupSummaryDTO is the dashboard's compact backup-queue view. Pending/Failed
 * are the HEADLINE numbers and count required (non-mirror) backups only, so a
 * convenience mirror lagging behind never inflates the failure count. MirrorPending
 * / MirrorFailed are a separate soft count the dashboard shows as "mirror uploads
 * pending: N".
 */
export interface BackupSummaryDTO {
    "pending": number;
    "failed": number;
    "mirrorPending": number;
    "mirrorFailed": number;

    /**
     * Live rate/ETA for the dashboard backup card ("11,402 pending → done
     * ~Thursday"). JobsPerMinute is the rolling completion rate; BytesRemaining is
     * the outstanding upload workload; EtaSeconds/EtaAt estimate when the whole
     * active queue (all providers, pending+running) drains; LastCompletedAt is the
     * most recent completion; Paused is true when backups are yielding to foreground
     * work or a provider is cooling (the card shows the paused state, not an ETA).
     */
    "jobsPerMinute": number;
    "bytesRemaining": number;
    "etaSeconds": number;
    "etaAt": string | null;
    "lastCompletedAt": string | null;
    "paused": boolean;
}

/**
 * BrowseAssetDTO is the slim per-tile projection for the grid. It carries only
 * what a tile and its badges need; full provenance comes from AssetDetail.
 */
export interface BrowseAssetDTO {
    "id": string;
    "filename": string;
    "captureDate": string | null;
    "mediaType": string;
    "fileSize": number;
    "width": number;
    "height": number;
    "durationSeconds": number;
    "verificationStatus": string;
    "backupStatus": string;
    "isLivePhotoPair": boolean;
    "duplicateOfAssetId": string;
    "hasArchiveCopy": boolean;
}

/**
 * BrowseFilters are the browser grid's optional filters. Empty strings mean "no
 * filter". YearMonth is "2006-01" (capture month). CaptureFrom/CaptureTo are
 * inclusive ISO date/datetime bounds on the effective date
 * (COALESCE(capture_date, import_date)); the frontend supplies whole-day/whole-
 * year boundaries. CameraMake/CameraModel are exact-match camera identity. The
 * month, the from/to range, and the camera are independent AND-ed predicates.
 */
export interface BrowseFilters {
    "query": string;
    "mediaType": string;
    "verificationStatus": string;
    "backupStatus": string;
    "sessionId": string;
    "yearMonth": string;
    "captureFrom": string;
    "captureTo": string;
    "cameraMake": string;
    "cameraModel": string;
}

/**
 * BulkResolveFailure records one duplicate the bulk job could not resolve: the
 * asset ID, its display filename and resolved path (best effort), and the error.
 * One bad pair never aborts the batch — every failure is collected here.
 */
export interface BulkResolveFailure {
    "assetId": string;
    "filename": string;
    "path": string;
    "error": string;
}

/**
 * BulkResolveProgress is the payload for duplicates:progress, emitted (throttled)
 * while a StartBulkResolve job works through the selected duplicates. Done/Total
 * count items processed; Succeeded/Failed accumulate outcomes; CurrentFile is the
 * duplicate being resolved. Done == Total marks the final tick (paired with a
 * duplicates:completed carrying the summary).
 */
export interface BulkResolveProgress {
    "action": string;
    "done": number;
    "total": number;
    "succeeded": number;
    "failed": number;
    "currentFile": string;
}

/**
 * BulkResolveSummaryDTO is the payload for duplicates:completed and the terminal
 * snapshot ActiveBulkResolve returns. It totals the batch outcome and lists every
 * per-item failure. Cancelled is true when the run was stopped early (items
 * already resolved stay resolved; the remainder are left flagged for a later run).
 */
export interface BulkResolveSummaryDTO {
    "action": string;
    "total": number;
    "succeeded": number;
    "failed": number;
    "cancelled": boolean;
    "failures": BulkResolveFailure[] | null;
}

/**
 * CameraCountDTO is one distinct camera in the library with its asset count. It
 * backs the Library browser's Camera filter (BrowserService.Cameras). Make and
 * Model are the exact stored values the grid filters on; Label is the display
 * "Make Model".
 */
export interface CameraCountDTO {
    "make": string;
    "model": string;
    "label": string;
    "count": number;
}

/**
 * ClassStatDTO is the per-class rollup in a cleanup report.
 */
export interface ClassStatDTO {
    "class": string;
    "count": number;
    "bytes": number;
    "files": string[] | null;
    "truncated": boolean;
}

/**
 * CleanupCompleted is the payload for cleanup:completed, emitted once when a
 * background cleanup analyze finishes. Exactly one terminal state holds: success
 * (Report set), cancelled (Cancelled true), or failed (Error set). Root echoes
 * the analyzed folder so the frontend can restore context on re-attach.
 */
export interface CleanupCompleted {
    "root": string;
    "report": CleanupReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * CleanupProgress is the payload for cleanup:progress. FilesDone advances per
 * classified file; FilesTotal is 0 while the analyzer walks-and-classifies in a
 * single pass (the total is not known until the walk completes), so the UI
 * renders an indeterminate count. CurrentFile is the file being classified.
 */
export interface CleanupProgress {
    "filesDone": number;
    "filesTotal": number;
    "currentFile": string;
}

/**
 * CleanupReportDTO is the JSON-friendly cleanup analysis result.
 */
export interface CleanupReportDTO {
    "root": string;
    "classes": ClassStatDTO[] | null;
    "totalFiles": number;
    "mediaFiles": number;
    "nonMedia": number;
    "unreadableMedia": number;
    "archivedNotVerified": number;
    "backupIncomplete": number;
    "dbInconsistencies": number;
    "recommendation": RecommendationDTO;
}

/**
 * ClearSourcePreviewDTO is what the confirmation dialog needs before a clear:
 * the number of evaluated-safe files, their total size (best-effort stat), and
 * the trash destination parent. It is produced only when the gate is satisfied;
 * otherwise the preview call returns a typed gate error.
 */
export interface ClearSourcePreviewDTO {
    "root": string;
    "fileCount": number;
    "totalBytes": number;
    "trashDir": string;
}

/**
 * ClearSourceResultDTO summarizes a completed clear: how many evaluated-safe
 * files were moved to the timestamped trash directory, how many unsafe files were
 * deliberately left untouched, and how many moves errored. TrashDir is the exact
 * destination so the UI can tell the user where the files went.
 */
export interface ClearSourceResultDTO {
    "root": string;
    "trashDir": string;
    "moved": number;
    "skippedUnsafe": number;
    "errors": number;
    "cancelled": boolean;
}

/**
 * CoverageProviderDTO describes one column of the coverage table: a destination
 * ever referenced by a backup job. It survives provider removal (Removed=true,
 * named from the soft-deleted row) so the table stays honest about where past
 * backups went. Mirror marks a destination whose completed jobs are
 * uploaded-but-unverifiable.
 */
export interface CoverageProviderDTO {
    "providerId": string;
    "name": string;
    "mirror": boolean;
    "removed": boolean;
}

/**
 * CoverageProviderFilter is the optional per-provider status filter for
 * ListCoverage: restrict to assets whose backup state for ProviderID matches
 * Status (a coverage status string). A nil pointer (or empty fields) applies no
 * provider filter.
 */
export interface CoverageProviderFilter {
    "providerId": string;
    "status": string;
}

/**
 * CoverageRowDTO is one asset row of the Backup Coverage table: its identity and
 * provenance (name, resolved archive location, where it came from, taken/imported
 * dates) plus its per-destination backup state. Providers carries ONLY the
 * destinations this asset actually has a job for; a column in the table with no
 * matching entry renders as "none".
 */
export interface CoverageRowDTO {
    "assetId": string;
    "filename": string;

    /**
     * resolved absolute
     */
    "archivePath": string;
    "sourceLabel": string;
    "captureDate": string | null;
    "importDate": string;
    "mediaType": string;
    "hasArchiveCopy": boolean;
    "providers": ProviderCoverageDTO[] | null;
}

/**
 * CurrentLibraryDTO describes the library currently open, surfaced to the
 * frontend for the Settings → Library card and the root-layout gate.
 */
export interface CurrentLibraryDTO {
    "path": string;
    "name": string;
    "schemaVersion": number;
    "appVersion": string;
    "openedAt": string;
}

/**
 * DashboardStats is the full dashboard payload.
 */
export interface DashboardStats {
    "totals": TotalsDTO;
    "pendingImports": number;
    "backupQueue": BackupSummaryDTO;

    /**
     * EnabledRequiredProviders is the number of enabled, non-mirror (required)
     * backup destinations configured. Zero while assets exist means the archive is
     * the only copy — the dashboard renders a prominent "no backup destination"
     * warning. Mirrors are excluded: a mirror-only setup still has no custody copy.
     */
    "enabledRequiredProviders": number;
    "duplicateCount": number;
    "recentSources": SourceDTO[] | null;
    "safeToEraseSources": SourceDTO[] | null;
    "recentActivity": LogEntryDTO[] | null;
}

/**
 * DryRunReportDTO is the JSON-friendly projection of importer.DryRunReport. It
 * omits the carried-forward hash maps (an internal optimization) and exposes the
 * mode-aware planning counts.
 */
export interface DryRunReportDTO {
    "mode": string;
    "reorganize": boolean;
    "files": number;
    "photos": number;
    "videos": number;
    "alreadyImported": number;
    "duplicates": number;
    "new": number;
    "totalImportBytes": number;
    "estimatedSeconds": number;
    "plannedAdoptions": number;
    "plannedMoves": number;
}

/**
 * DuplicateFilterDTO selects a subset of duplicates for the listing/ID methods.
 * GroupBy ("" | "folder" | "session") plus GroupKey narrows to one folder or one
 * import session; SortBySize orders by wasted size descending. All filtering is
 * pushed into SQL.
 */
export interface DuplicateFilterDTO {
    "groupBy": string;
    "groupKey": string;
    "sortBySize": boolean;
}

/**
 * DuplicateGroupDTO is one group in the picker: its raw Key (folder path or
 * session ID, echoed back as GroupKey when filtering), a human Label, and the
 * flagged-duplicate Count and WastedBytes in that group.
 */
export interface DuplicateGroupDTO {
    "key": string;
    "label": string;
    "count": number;
    "wastedBytes": number;
}

/**
 * DuplicatePairDTO pairs a duplicate asset with the original it duplicates, plus
 * per-side presence flags so the UI can disable reveal actions for files that are
 * not reachable right now (e.g. the archive volume is offline). Every duplicate
 * managed here has its OWN physical archive copy (that is what makes it a genuine,
 * reclaimable duplicate); source-only placeholder rows are excluded upstream.
 */
export interface DuplicatePairDTO {
    "duplicate": AssetDTO;
    "original": AssetDTO;

    /**
     * DuplicateFileExists reports whether the duplicate's archived file exists on
     * disk right now (os.Stat of its resolved archive path).
     */
    "duplicateFileExists": boolean;

    /**
     * OriginalFileExists reports whether the original's archived file exists right
     * now (os.Stat of its resolved archive path).
     */
    "originalFileExists": boolean;
}

/**
 * DuplicateProgress is the payload for duplicate:progress, carrying the byte
 * progress of a cross-volume duplicate move (copy+verify).
 */
export interface DuplicateProgress {
    "assetId": string;
    "bytesDone": number;
    "bytesTotal": number;
}

/**
 * DuplicateStatsDTO reports the TRUE totals across all non-deleted flagged
 * duplicates (never just the visible page): the pair count and the sum of the
 * duplicate assets' FileSize (reclaimable "wasted" bytes).
 */
export interface DuplicateStatsDTO {
    "totalPairs": number;
    "totalWastedBytes": number;
}

/**
 * Emitter delivers a typed event payload to the frontend. It is implemented in
 * main.go over the Wails App's event manager and injected into every service
 * that reports progress. A nil Emitter is tolerated by emitSafe.
 */
export type Emitter = any;

/**
 * FolderEntryDTO is one immediate subdirectory in a folder listing: its display
 * name, full root-relative path (for drilling in), recursive asset count, a
 * representative cover asset id (for a thumbnail), the newest effective capture
 * date anywhere beneath it (nullable ISO string; capture date, or import date as
 * fallback), and whether it is a renameable date-event folder.
 */
export interface FolderEntryDTO {
    "name": string;
    "relPath": string;
    "assetCount": number;
    "coverAssetId": string;
    "newestCapture": string | null;
    "isDateFolder": boolean;
}

/**
 * FolderListingDTO is one level of the archive tree: the cleaned directory, its
 * immediate subfolders, and the assets sitting directly in it (paged). For a
 * date-event folder it also carries IsDateFolder=true and the current Label so
 * the UI can offer Rename… prefilled.
 */
export interface FolderListingDTO {
    "relDir": string;
    "isDateFolder": boolean;
    "label": string;
    "subfolders": FolderEntryDTO[] | null;
    "assets": PageResult<BrowseAssetDTO>;
}

/**
 * ImportCompleted is the payload for import:completed, emitted once when a
 * background import goroutine finishes (successfully, cancelled, or interrupted).
 */
export interface ImportCompleted {
    "sessionId": string;
    "status": string;
    "filesScanned": number;
    "filesImported": number;
    "duplicates": number;
    "failures": number;
    "skipped": number;
    "alreadyImported": number;
}

/**
 * ImportFailureDTO is the JSON-friendly projection of a structured per-file
 * import failure. Op names the pipeline stage that failed; Status is open,
 * retried, or dismissed. It backs the Import completion panel and Import History
 * "Failed files" panel, whose per-file Retry/Dismiss actions resolve it.
 */
export interface ImportFailureDTO {
    "id": string;
    "sessionId": string;
    "path": string;
    "op": string;
    "errorMessage": string;
    "status": string;
    "resolvedAt": string | null;
    "dismissReason": string;
    "createdAt": string;
}

/**
 * ImportOptions configures StartImport. Root is the source tree. DestinationRoot
 * defaults to the configured Master Library when empty. Mode is "copy" or
 * "adopt"; Reorganize (adopt only) moves files into the standard layout.
 */
export interface ImportOptions {
    "root": string;
    "destinationRoot": string;
    "eventName": string;
    "mode": string;
    "reorganize": boolean;
    "sourceId": string;

    /**
     * SkipProviderIds names enabled backup providers to exclude for this import
     * (per-import provider opt-out). Each is validated against the configured
     * providers; the pipeline records a durable opted-out marker per excluded
     * provider instead of a pending backup job. Persisted in the resume state so a
     * resumed import applies the same skips.
     */
    "skipProviderIds": string[] | null;
}

/**
 * ImportProgress is the payload for import:progress. It mirrors importer.Progress
 * plus the owning session ID (so the frontend can correlate updates) and a
 * derived completion percentage.
 */
export interface ImportProgress {
    "sessionId": string;
    "phase": string;
    "filesDone": number;
    "filesTotal": number;
    "bytesDone": number;
    "bytesTotal": number;
    "currentFile": string;
    "errors": number;
    "percent": number;
    "done": boolean;
}

/**
 * LegacyStatusDTO reports whether a pre-library per-machine catalog exists (so
 * Welcome can offer to migrate it).
 */
export interface LegacyStatusDTO {
    "exists": boolean;
    "path": string;
}

/**
 * LibraryGate is the shared open/closed switch every DB-backed service consults.
 * It is closed until a library is opened (at startup or from Welcome) and reopens
 * atomically once the object graph is bound in place. A nil *LibraryGate is
 * treated as always-open, so services constructed directly in unit tests (which
 * pass no gate) are never gated.
 */
export interface LibraryGate {
}

/**
 * LibraryProgress is the payload for library:progress, emitted during a library
 * open that runs migrations / legacy installation. Phase names the current step
 * ("backing-up", "installing-legacy", "converting-paths", "verifying",
 * "migrating"); Done/Total are populated for determinate phases (0 otherwise).
 * Not cancellable: migrations must run to completion or roll back atomically.
 */
export interface LibraryProgress {
    "phase": string;
    "message": string;
    "done": number;
    "total": number;
}

/**
 * LockConflictDTO carries the structured details of a refused lock so the
 * frontend can present an informed Force Open confirmation.
 */
export interface LockConflictDTO {
    "hostname": string;
    "pid": number;
    "sameHostLive": boolean;
    "heartbeatAgeSeconds": number;
    "message": string;
}

/**
 * LogEntryDTO is the JSON-friendly projection of a persisted LogEntry.
 */
export interface LogEntryDTO {
    "id": number;
    "timestamp": string;
    "level": string;
    "subsystem": string;
    "message": string;
    "metadataJson": string;
}

/**
 * LogExportProgress is the payload for log:export-progress, emitted (throttled)
 * while a log export streams rows to disk. RowsWritten is the running count.
 */
export interface LogExportProgress {
    "rowsWritten": number;
}

/**
 * MatchDTO is the JSON-friendly result of identifying a volume.
 */
export interface MatchDTO {
    "sourceId": string;
    "source": SourceDTO;
    "confidence": number;
    "reasons": string[] | null;
    "isKnown": boolean;
    "contentsPreviouslyImported": boolean;
}

/**
 * MonthCountDTO pairs a capture month ("YYYY-MM") with an asset count. It backs
 * the Library browser's month filter (BrowserService.Months).
 */
export interface MonthCountDTO {
    /**
     * YYYY-MM
     */
    "month": string;
    "count": number;
}

/**
 * OpenResultDTO is returned by Create/Open/ForceOpen/MigrateLegacy. Exactly one
 * of {Library set}, {LockConflict set}, or {NeedsRelaunch true} is meaningful:
 *   - Library set, NeedsRelaunch false: opened in place, frontend can proceed.
 *   - NeedsRelaunch true: a different library was already open; config was
 *     updated and the app must relaunch to switch (frontend prompts).
 *   - LockConflict set: the library is locked; frontend offers Force Open.
 */
export interface OpenResultDTO {
    "needsRelaunch": boolean;
    "library": CurrentLibraryDTO | null;
    "lockConflict": LockConflictDTO | null;
}

/**
 * OperationInfo is one running long operation reported to the quit guard. Kind is
 * a stable machine token (one of the OpKind* constants); Label is a human phrase.
 * FilesDone/FilesTotal and BytesDone/BytesTotal are the latest progress snapshot
 * (a zero total means the count is indeterminate). It is JSON-serializable so it
 * can ride the app:quit-requested event payload and the
 * AppService.ActiveOperations binding.
 */
export interface OperationInfo {
    "kind": string;
    "label": string;
    "filesDone": number;
    "filesTotal": number;
    "bytesDone": number;
    "bytesTotal": number;
}

/**
 * PageResult wraps a paginated slice with its total match count so tables can
 * render pagination controls.
 */
export interface PageResult<T> {
    "items": T[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * PluginDTO describes an available backup plugin and its capabilities.
 */
export interface PluginDTO {
    "name": string;
    "supportsVerify": boolean;
    "supportsDelete": boolean;
    "supportsResume": boolean;
    "maxFileSize": number;
}

/**
 * ProviderCooldownDTO describes one provider's active quota cooldown.
 */
export interface ProviderCooldownDTO {
    "providerId": string;
    "until": string;
    "reason": string;
}

/**
 * ProviderCoverageDTO is one asset's backup state for one destination in the
 * coverage table: the coverage status, when the job completed (nil unless it
 * completed), and a note (a verify-unavailable explanation on an unverifiable
 * destination, or the error message on a failure; empty otherwise).
 */
export interface ProviderCoverageDTO {
    "providerId": string;
    "status": string;
    "completedAt": string | null;
    "note": string;
}

/**
 * ProviderDTO is the JSON-friendly projection of a BackupProvider.
 */
export interface ProviderDTO {
    "id": string;
    "pluginName": string;
    "configJson": string;
    "enabled": boolean;
    "mirror": boolean;
    "uploadOrder": string;

    /**
     * MediaScope is the CSV of media kinds this destination backs up, from
     * {photos,videos,raws} (see internal/mediatype). An empty string means "all
     * kinds" (the default). Missing/opted-out counts and backfill are scoped to it.
     */
    "mediaScope": string;

    /**
     * MissingBackupCount is how many eligible library assets have NO backup job for
     * this destination yet — the count that powers the "Queue N backups" auto-offer
     * and the per-card badge. It is populated only for ENABLED providers (backfill
     * is refused for disabled ones); 0 otherwise or when the catalog is unbound.
     * Assets deliberately opted out of this destination are NOT counted here (they
     * are surfaced separately as OptedOutCount).
     */
    "missingBackupCount": number;

    /**
     * OptedOutCount is how many assets the user deliberately excluded from this
     * destination at import time (opted_out jobs). It drives the card's "N skipped
     * by choice · Queue anyway" reversal line. Populated for enabled providers.
     */
    "optedOutCount": number;

    /**
     * LastError is this destination's most recent still-failing job (its error
     * message and when it was recorded), or nil when it has no currently-failed
     * job. LastSuccessAt is when its most recent job completed, or nil if none has.
     * The card shows a "Failing — <error>" amber state (in place of the green
     * Enabled dot) when LastError is set and is more recent than LastSuccessAt.
     */
    "lastError": ProviderErrorDTO | null;
    "lastSuccessAt": string | null;
}

/**
 * ProviderErrorDTO is a destination's most recent failure: the job's error
 * message and the time it was recorded (the failed job's UpdatedAt).
 */
export interface ProviderErrorDTO {
    "message": string;
    "at": string;
}

/**
 * QueueSummaryDTO reports the number of backup jobs in each status, plus any
 * provider quota cooldowns currently in effect (so the Backup Queue can show a
 * "uploads resume ~HH:MM" banner; the cooling jobs stay visible as pending).
 */
export interface QueueSummaryDTO {
    "pending": number;
    "running": number;
    "paused": number;
    "completed": number;
    "failed": number;
    "cancelled": number;

    /**
     * OptedOut counts jobs the user deliberately excluded per-import (opted_out).
     * They are never claimed and never gate a safety verdict; shown subtly in the
     * queue summary so the count is visible without implying pending work.
     */
    "optedOut": number;
    "total": number;
    "cooldowns": ProviderCooldownDTO[] | null;

    /**
     * JobsPerMinute is the rolling backup completion rate (completed jobs per
     * minute) over a recent trailing window; 0 when there is not enough recent
     * activity to estimate. It drives the queue header's rate line.
     */
    "jobsPerMinute": number;

    /**
     * BytesRemaining is the outstanding upload workload in bytes — the summed file
     * size of assets behind pending/paused/running jobs (per provider). SQL
     * aggregate; never a full row scan.
     */
    "bytesRemaining": number;

    /**
     * LastCompletedAt is the most recent backup-job completion, or nil when nothing
     * has completed yet (the UI shows a relative "last backup 2m ago").
     */
    "lastCompletedAt": string | null;

    /**
     * EtaSeconds estimates how many seconds until the active queue (pending+running)
     * drains at the current rate; EtaAt is the corresponding wall-clock instant.
     * Both are zero/nil when the rate is 0, the queue is empty, or backups are
     * paused/yielding/cooling — the frontend then renders "—" and surfaces the
     * paused state instead of a stale ETA, never "done ~Infinity".
     */
    "etaSeconds": number;
    "etaAt": string | null;

    /**
     * Yielding is true when the backup manager is currently withholding new job
     * claims because a foreground operation (import/analyze/reorganize/…) is
     * running; in-flight uploads still finish and pending jobs resume
     * automatically when the foreground work ends. Drives the Backup Queue's
     * "paused while an import runs" banner.
     */
    "yielding": boolean;
}

/**
 * QuitRequested is the payload for app:quit-requested, emitted when the user
 * tries to quit while long operations are running. The quit is vetoed and this
 * carries the live operations list so the global quit-guard dialog can name each
 * one with current numbers. A repeated quit attempt re-emits with fresh numbers.
 */
export interface QuitRequested {
    "operations": OperationInfo[] | null;
}

/**
 * RcloneRemoteInfoDTO reports a chosen rclone remote's backend type and whether
 * PAIM can verify uploads to it. The Add-destination UI uses SupportsChecksum to
 * auto-suggest the Mirror toggle and warn that uploads cannot be verified when the
 * backend (e.g. Google Photos) exposes no content hash.
 */
export interface RcloneRemoteInfoDTO {
    "remote": string;
    "backendType": string;
    "supportsChecksum": boolean;
    "error": string;
}

/**
 * RcloneRemotesDTO reports rclone's install status and the remotes it has
 * configured, for the Add-destination UI. When Installed is false the UI shows
 * install guidance (brew install rclone) instead of a remotes dropdown; when
 * Installed is true but Error is set, rclone is present but listing its remotes
 * failed (surfaced inline). This is deliberately NOT gated on an open library —
 * discovering rclone remotes is independent of the catalog.
 */
export interface RcloneRemotesDTO {
    "installed": boolean;
    "binary": string;
    "remotes": string[] | null;
    "error": string;
}

/**
 * RecentLibraryDTO is one entry in the recent-libraries list.
 */
export interface RecentLibraryDTO {
    "path": string;
    "name": string;
    "lastOpenedAt": string;
}

/**
 * RecommendationDTO is the delete-safety verdict.
 */
export interface RecommendationDTO {
    "safeToDelete": boolean;
    "title": string;
    "summary": string;
    "reasons": string[] | null;
}

/**
 * ReconcilePreviewDTO is the dry-run outcome of a queue reconcile for a provider:
 * how many jobs would be cancelled (pending/paused jobs whose asset is now OUT of
 * the provider's scope) and how many would be enqueued (in-scope eligible assets
 * with no job yet). Both are computed from the provider's CURRENT stored scope, so
 * the UI saves a scope change first, then previews.
 */
export interface ReconcilePreviewDTO {
    "providerId": string;
    "toCancel": number;
    "toEnqueue": number;
}

/**
 * ReorganizeMoveDTO is one planned same-drive move in a reorganize preview.
 */
export interface ReorganizeMoveDTO {
    "assetId": string;
    "filename": string;
    "from": string;
    "to": string;
}

/**
 * ReorganizePlanDTO is the JSON-friendly reorganize preview: aggregate counts
 * plus a display-capped sample of moves and skips. Truncated reports whether the
 * move sample was cut to DisplayCap (the counts remain exact).
 */
export interface ReorganizePlanDTO {
    "totalAssets": number;
    "inPlace": number;
    "moves": number;
    "skipped": number;
    "displayCap": number;
    "truncated": boolean;
    "movesSample": ReorganizeMoveDTO[] | null;
    "skippedSample": ReorganizeSkipDTO[] | null;
}

/**
 * ReorganizePlanProgress is the payload for reorganize:plan-progress, emitted
 * (throttled) while PlanReorganize walks the catalog. Total is known up front
 * (after listing archived assets) so the UI can render a determinate bar.
 */
export interface ReorganizePlanProgress {
    "done": number;
    "total": number;
}

/**
 * ReorganizeSkipDTO is one asset the reorganize will not move, with the reason
 * (missing-on-disk, cross-volume, duplicate).
 */
export interface ReorganizeSkipDTO {
    "assetId": string;
    "filename": string;
    "path": string;
    "reason": string;
}

/**
 * RetryFailedFileResult reports the outcome of a single-file retry. Success is
 * true when the file was re-imported (AssetID set when a new asset row was
 * created — a duplicate/already-imported resolution leaves it empty). On a
 * re-failure Success is false and Op/Error name the stage and message; the
 * underlying failure record stays open so it can be retried or dismissed again.
 */
export interface RetryFailedFileResult {
    "failureId": string;
    "success": boolean;
    "assetId": string;
    "op": string;
    "error": string;
}

/**
 * SafeToEraseDTO is the JSON-friendly safe-to-erase report. FastPath/Hashed
 * report how many media files were classified from the catalog without hashing
 * vs by (re)hashing, so the UI can show how cheap a just-imported evaluation was.
 */
export interface SafeToEraseDTO {
    "sourceId": string;
    "safe": boolean;
    "reason": string;

    /**
     * NoBackupDestination is true when the not-safe verdict is solely because no
     * backup destination is configured (every file is archived and verified but
     * the archive is the only copy). The UI renders this amber, distinct from the
     * red not-archived cases.
     */
    "noBackupDestination": boolean;
    "totalMedia": number;
    "archived": number;
    "new": number;
    "unverified": number;
    "backupIncomplete": number;
    "fastPath": number;
    "hashed": number;
}

/**
 * ScanSummary is the provisional result of scanning a source tree, before any
 * hashing or duplicate detection.
 */
export interface ScanSummary {
    "root": string;
    "files": number;
    "photos": number;
    "videos": number;
    "rawPhotos": number;
    "provisionalPairs": number;
    "totalBytes": number;
}

/**
 * SessionBackupStatusDTO is the live per-session backup progress the import
 * completion panel shows ("N of M backed up"). TotalAssets counts the session's
 * backup-eligible assets (those with an archive copy); BackedUp counts those
 * whose aggregate BackupStatus is complete — the same signal safe-to-erase uses
 * per asset. Complete is true when every eligible asset is backed up (or there
 * are none to back up), i.e. the usual clear-after-import blocker has cleared.
 */
export interface SessionBackupStatusDTO {
    "sessionId": string;
    "totalAssets": number;
    "backedUp": number;
    "complete": boolean;
}

/**
 * SessionDTO is the JSON-friendly projection of an ImportSession. Mode is decoded
 * from the session's resume-state notes so the Import History can badge adopt
 * runs distinctly from copy runs.
 */
export interface SessionDTO {
    "id": string;
    "startedAt": string;
    "completedAt": string | null;
    "durationSeconds": number;
    "sourceId": string;
    "destinationRoot": string;
    "filesScanned": number;
    "filesImported": number;
    "duplicates": number;
    "failures": number;
    "skipped": number;
    "alreadyImported": number;
    "status": string;
    "mode": string;

    /**
     * SourceLabel is a human-readable description of the import source for the
     * History "Source" column: for adopt runs "Library (adopt)"; for a copy run
     * with a linked source, the volume label + type (enriched by HistoryService);
     * otherwise a display-only fallback to the source root folder's basename. It is
     * never empty for a session whose notes recorded a source root.
     */
    "sourceLabel": string;

    /**
     * SourceRoot is the absolute source tree recorded in the session's resume-state
     * notes. It backs the Source column's tooltip (and the basename fallback).
     */
    "sourceRoot": string;
}

/**
 * SessionDetail bundles a session with the log entries produced during its run.
 * Truncated reports whether the event list was capped (sessionEventsCap); the
 * counts on the session itself always reflect the full run.
 */
export interface SessionDetail {
    "session": SessionDTO;
    "events": LogEntryDTO[] | null;
    "truncated": boolean;

    /**
     * Approximate is true when the events could not be matched to this session by
     * ID (an older session imported before per-file logs carried a sessionId) and
     * were instead gathered by the import subsystem's time window. The UI notes
     * this so the user knows the list is a best-effort time-window match.
     */
    "approximate": boolean;
}

/**
 * Settings is the typed, JSON-friendly view of PAIM's configuration returned by
 * SettingsService.GetAll and consumed by main.go to drive the archive layout,
 * backup worker pool, and import concurrency. MetadataAvailable is read-only,
 * derived at runtime from whether exiftool (or the fallback) can extract data.
 */
export interface Settings {
    "masterLibraryRoot": string;
    "backupWorkers": number;
    "maxRetries": number;
    "importConcurrency": number;
    "defaultEventName": string;
    "generateThumbsAfterImport": boolean;
    "metadataAvailable": boolean;
}

/**
 * SleepGuard holds a macOS power-management assertion for the duration of any
 * long-running PAIM operation (import, analyze, reorganize, safe-to-erase,
 * cleanup analyze). While such work is in flight we run `/usr/bin/caffeinate -im`
 * as a child process, which keeps the system (and, with -m, the disk) awake.
 * 
 * WHY: if the Mac sleeps mid-import the filesystem I/O the pipeline depends on is
 * paused — copies stall, hashing halts, and a multi-hour import of a large card
 * can silently wedge until the machine is woken. Holding the assertion for the
 * life of the operation keeps long jobs progressing on an unattended machine.
 * 
 * It is refcounted so several concurrent operations share one assertion: the
 * first Acquire starts the process, the last Release kills it. Shutdown force-
 * kills it regardless of the count so no caffeinate child outlives the app.
 * 
 * The command starter is injected so tests can assert the refcount transitions
 * without spawning a real process.
 */
export interface SleepGuard {
}

/**
 * SnapshotConfigDTO is the per-machine snapshot configuration.
 */
export interface SnapshotConfigDTO {
    "dest": string;
    "interval": string;
}

/**
 * SnapshotStatusDTO is the snapshot config plus the last-run result for the UI.
 */
export interface SnapshotStatusDTO {
    "dest": string;
    "interval": string;
    "enabled": boolean;
    "running": boolean;
    "lastAt": string;
    "lastPath": string;
    "lastError": string;
}

/**
 * SourceCleared is the payload for source:cleared, emitted once when a background
 * clear-source job finishes (successfully or cancelled). Moved is how many
 * evaluated-safe files were moved into TrashDir; SkippedUnsafe is how many unsafe
 * files were deliberately left in place; Errors is how many moves failed.
 */
export interface SourceCleared {
    "root": string;
    "trashDir": string;
    "moved": number;
    "skippedUnsafe": number;
    "errors": number;
    "cancelled": boolean;
}

/**
 * SourceDTO is the JSON-friendly projection of an ImportSource.
 */
export interface SourceDTO {
    "id": string;
    "sourceType": string;
    "hardwareSerial": string;
    "filesystemUuid": string;
    "volumeUuid": string;
    "volumeLabel": string;
    "manufacturer": string;
    "model": string;
    "capacityBytes": number;
    "connectionType": string;
    "confidence": number;
    "confidenceReason": string;
    "lastSeenAt": string;
    "importCount": number;
    "safeToErase": boolean;
    "safeToEraseReason": string;
}

/**
 * SourceEvaluated is the payload for source:evaluated, emitted once when a
 * background safe-to-erase evaluation finishes. Exactly one terminal state
 * holds: success (Report set), cancelled (Cancelled true), or failed (Error set).
 */
export interface SourceEvaluated {
    "mountPoint": string;
    "sourceId": string;
    "report": SafeToEraseDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * SourceIdentified is the payload for source:identified, emitted after a volume
 * is identified and persisted.
 */
export interface SourceIdentified {
    "mountPoint": string;
    "sourceId": string;
    "confidence": number;
    "isKnown": boolean;
}

/**
 * SourceProgress is the payload for source:progress, carrying the progress of a
 * long-running source operation. Kind is "safe-to-erase" (determinate:
 * FilesTotal is known), "clear" (determinate: moving evaluated-safe files to
 * trash), or "identify" (indeterminate: only Scanned advances, FilesTotal is 0).
 * MountPoint correlates the update with a volume card (or the source root for a
 * clear).
 */
export interface SourceProgress {
    "kind": string;
    "mountPoint": string;
    "filesDone": number;
    "filesTotal": number;
    "scanned": number;
    "currentFile": string;
}

/**
 * StartAnalyzeResult is returned immediately from StartAnalyze once the
 * background analyze has been launched. Root echoes the resolved source root; an
 * analyze is sessionless (no ImportSession is created), so it is re-attached via
 * ActiveAnalyze rather than by a session ID.
 */
export interface StartAnalyzeResult {
    "root": string;
}

/**
 * StartBulkResolveDTO is returned immediately once a bulk resolve launches.
 */
export interface StartBulkResolveDTO {
    "action": string;
    "total": number;
}

/**
 * StartCleanupAnalyzeResult is returned immediately from StartCleanupAnalyze once
 * the background analysis has been launched. Root echoes the analyzed folder; the
 * analysis is re-attached via ActiveCleanupAnalyze (only one runs at a time).
 */
export interface StartCleanupAnalyzeResult {
    "root": string;
}

/**
 * StartClearSourceResult is returned immediately once the clear job launches.
 */
export interface StartClearSourceResult {
    "root": string;
    "trashDir": string;
    "files": number;
}

/**
 * StartImportResult is returned immediately from StartImport once the session is
 * created and the background run has been launched.
 */
export interface StartImportResult {
    "sessionId": string;
}

/**
 * StartSafeToEraseResult is returned immediately from StartSafeToErase once the
 * background evaluation has been launched. MountPoint echoes the volume; the
 * evaluation is re-attached via ActiveSafeToErase (keyed by nothing — only one
 * runs at a time).
 */
export interface StartSafeToEraseResult {
    "mountPoint": string;
}

/**
 * ThumbCacheDTO describes where the thumbnail cache currently lives and the two
 * possible locations, so the Settings UI can render the choice and the active
 * path.
 */
export interface ThumbCacheDTO {
    /**
     * "library" | "local"
     */
    "location": string;

    /**
     * where thumbnails are written today
     */
    "activeDir": string;

    /**
     * <root>/.paim/thumbs
     */
    "libraryDir": string;

    /**
     * app-support/thumbs/<libraryId>
     */
    "localDir": string;
}

/**
 * ThumbsProgress is the payload for thumbs:progress, emitted (throttled) while a
 * thumbnail warm-up runs. Done/Total count assets processed; Label distinguishes
 * a whole-catalog warm-up from a post-import one so the UI can word it. Done ==
 * Total with Running=false marks completion.
 */
export interface ThumbsProgress {
    "done": number;
    "total": number;
    "label": string;
    "running": boolean;
}

/**
 * TotalsDTO holds the library totals.
 */
export interface TotalsDTO {
    "assets": number;
    "photos": number;
    "videos": number;
    "livePhotos": number;
    "storageBytes": number;
}

/**
 * VersionInfo is the build-stamped application version surfaced to the frontend
 * (Settings → About, Welcome subtitle). Commit and Date are empty in a dev build;
 * Full is always non-empty (it degrades to "<version> (dev)").
 */
export interface VersionInfo {
    "version": string;
    "commit": string;
    "date": string;
    "full": string;
}

/**
 * VolumeDTO is the JSON-friendly projection of a mounted volume description.
 */
export interface VolumeDTO {
    "mountPoint": string;
    "volumeName": string;
    "volumeUuid": string;
    "filesystemUuid": string;
    "filesystemType": string;
    "capacityBytes": number;
    "freeBytes": number;
    "removable": boolean;
    "internal": boolean;
    "ejectable": boolean;
    "connectionType": string;
    "hardwareSerial": string;
    "manufacturer": string;
    "model": string;
    "isNetworkVolume": boolean;
    "networkUrl": string;
    "warnings": string[] | null;
}

/**
 * VolumeEvent is the payload for volume:mounted and volume:unmounted. For
 * volume:mounted it is enriched server-side (a lightweight diskutil describe) so
 * the frontend can decide whether to offer an "Import?" toast without a follow-up
 * fetch: VolumeName is the display label; Removable/Ejectable mark a physically
 * removable card/drive (the only kind worth prompting to import); IsLibraryVolume
 * is true when the open library lives on this volume (never prompt for it). The
 * enrichment fields are best-effort and left zero for volume:unmounted.
 */
export interface VolumeEvent {
    "mountPoint": string;
    "volumeName": string;
    "removable": boolean;
    "ejectable": boolean;
    "isLibraryVolume": boolean;
}

/**
 * WarmupStatusDTO is the re-attachment snapshot of the current warm-up.
 */
export interface WarmupStatusDTO {
    "running": boolean;
    "done": number;
    "total": number;
    "label": string;
}

/**
 * YearCountDTO pairs a capture year ("YYYY") with an asset count. It backs the
 * Library browser's Date filter year level (BrowserService.Years).
 */
export interface YearCountDTO {
    /**
     * YYYY
     */
    "year": string;
    "count": number;
}

/**
 * activitySnapshotter is the minimal view of the activity tracker the browser
 * consults before a mutating folder operation. *ActivityTracker satisfies it.
 */
export type activitySnapshotter = any;

/**
 * ejectActivity is the minimal view of the activity tracker EjectVolume consults
 * to refuse ejecting a volume a live operation is still touching. *ActivityTracker
 * satisfies it.
 */
export type ejectActivity = any;
