// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "../backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cleanup$0 from "../cleanup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importer$0 from "../importer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repo$0 from "../repo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as source$0 from "../source/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as thumbs$0 from "../thumbs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../gorm.io/gorm/models.js";

/**
 * ActiveAnalyzeDTO is the re-attachment snapshot returned by ActiveAnalyze.
 * State is "running" (Progress holds the latest snapshot), "completed" (Report,
 * or Cancelled/Error for a cancelled/failed run, is populated), or "none".
 * Opts echoes the normalized request so the frontend can restore the whole
 * step-2 context (root, mode, reorganize, event) after navigation.
 */
export interface ActiveAnalyzeDTO {
    "state": string;
    "opts": ImportOptions;
    "progress": ImportProgress | null;
    "report": DryRunReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * ActiveCleanupAnalyzeDTO is the re-attachment snapshot returned by
 * ActiveCleanupAnalyze. State is "running" (Progress holds the latest snapshot),
 * "completed" (Report, or Cancelled/Error, is populated), or "none". Root echoes
 * the request so the frontend can restore context after navigation.
 */
export interface ActiveCleanupAnalyzeDTO {
    "state": string;
    "root": string;
    "progress": CleanupProgress | null;
    "report": CleanupReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * ActiveSafeToEraseDTO is the re-attachment snapshot returned by
 * ActiveSafeToErase. State is "running" (Progress holds the latest snapshot),
 * "completed" (Report, or Cancelled/Error, is populated), or "none". MountPoint
 * and SourceID echo the request so the frontend can restore the volume card.
 */
export interface ActiveSafeToEraseDTO {
    "state": string;
    "mountPoint": string;
    "sourceId": string;
    "progress": SourceProgress | null;
    "report": SafeToEraseDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * AnalyzeCompleted is the payload for analyze:completed, emitted once when a
 * background analyze (scan + dry run) goroutine finishes. Exactly one of the
 * terminal states holds:
 *   - success: Report is non-nil, Cancelled=false, Error=="".
 *   - cancelled (via CancelImport): Report=nil, Cancelled=true.
 *   - failed: Report=nil, Error carries the message.
 * 
 * Root and Opts echo the (normalized) request so the frontend can restore the
 * whole step-2 context on re-attach without re-deriving it.
 */
export interface AnalyzeCompleted {
    "root": string;
    "opts": ImportOptions;
    "report": DryRunReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * AppCore is the per-library object graph: the opened catalog, its repositories,
 * and the engines that operate on it. It is built by BuildCore when a library is
 * opened and bound into the (already Wails-registered) services in place, so a
 * cold-start open needs no application restart.
 */
export interface AppCore {
    "Root": string;
    "Meta": db$0.Meta | null;
    "DB": gorm$0.DB | null;
    "Assets": repo$0.AssetRepo | null;
    "Sessions": repo$0.SessionRepo | null;
    "Sources": repo$0.SourceRepo | null;
    "Backups": repo$0.BackupRepo | null;
    "Logs": repo$0.LogRepo | null;
    "Settings": repo$0.SettingsRepo | null;
    "Manager": backup$0.Manager | null;
    "Pipeline": importer$0.Pipeline | null;
    "Analyzer": cleanup$0.Analyzer | null;
    "Identifier": source$0.Identifier | null;

    /**
     * Thumbs is this library's disposable thumbnail cache
     * (<root>/.paim/thumbs). The thumbnail HTTP handler serves from it.
     */
    "Thumbs": thumbs$0.Cache | null;
}

/**
 * AssetDTO is the JSON-friendly projection of a domain.Asset returned across the
 * binding boundary. It omits GORM internals (soft-delete plumbing) and normalizes
 * the nullable pointer fields the frontend cares about.
 */
export interface AssetDTO {
    "id": string;
    "originalFilename": string;
    "originalExtension": string;
    "originalFullPath": string;
    "sourceId": string;
    "sessionId": string;
    "quickHash": string;
    "fullHash": string;
    "fileSize": number;
    "captureDate": string | null;
    "importDate": string;
    "mediaType": string;
    "width": number;
    "height": number;
    "durationSeconds": number;
    "cameraMake": string;
    "cameraModel": string;
    "currentArchivePath": string;
    "verificationStatus": string;
    "backupStatus": string;
    "duplicateOfAssetId": string;
}

/**
 * AssetDetailDTO is the full provenance record shown in the detail drawer.
 */
export interface AssetDetailDTO {
    "id": string;
    "originalFilename": string;
    "originalExtension": string;
    "originalFullPath": string;

    /**
     * resolved absolute
     */
    "currentArchivePath": string;
    "quickHash": string;
    "fullHash": string;
    "fileSize": number;
    "captureDate": string | null;
    "importDate": string;
    "mediaType": string;
    "width": number;
    "height": number;
    "durationSeconds": number;
    "cameraMake": string;
    "cameraModel": string;
    "lens": string;
    "iso": number;
    "shutterSpeed": string;
    "aperture": string;
    "gpsLatitude": number | null;
    "gpsLongitude": number | null;
    "verificationStatus": string;
    "backupStatus": string;
    "isLivePhotoPair": boolean;
    "sourceId": string;
    "sourceLabel": string;
    "sourceType": string;
    "sessionId": string;
    "sessionDate": string | null;
    "backupJobs": BackupJobRefDTO[] | null;
    "duplicateOf": AssetRefDTO | null;
    "duplicates": AssetRefDTO[] | null;
    "livePhotoPartner": AssetRefDTO | null;
}

/**
 * AssetRefDTO is a slim reference to a related asset (duplicate/original/Live
 * Photo partner) used for in-drawer navigation.
 */
export interface AssetRefDTO {
    "id": string;
    "filename": string;
    "mediaType": string;
    "captureDate": string | null;
}

/**
 * BackupJobDTO is the JSON-friendly projection of a BackupJob joined with its
 * asset's display filename and archive path.
 */
export interface BackupJobDTO {
    "id": string;
    "assetId": string;
    "filename": string;
    "archivePath": string;
    "plugin": string;
    "destination": string;
    "status": string;
    "retries": number;
    "startedAt": string | null;
    "completedAt": string | null;
    "errorMessage": string;
}

/**
 * BackupJobRefDTO is the compact per-asset backup-job view in the detail drawer.
 */
export interface BackupJobRefDTO {
    "plugin": string;
    "destination": string;
    "status": string;
    "completedAt": string | null;
}

/**
 * BackupProgress is the payload for backup:progress, carrying one worker's
 * per-job upload progress.
 */
export interface BackupProgress {
    "jobId": string;
    "bytesDone": number;
    "bytesTotal": number;
}

/**
 * BackupQueueChanged is the payload for backup:queue-changed, emitted after any
 * queue state transition so the frontend can refresh counts.
 */
export interface BackupQueueChanged {
    "summary": QueueSummaryDTO;
}

/**
 * BackupSummaryDTO is the dashboard's compact backup-queue view.
 */
export interface BackupSummaryDTO {
    "pending": number;
    "failed": number;
}

/**
 * BrowseAssetDTO is the slim per-tile projection for the grid. It carries only
 * what a tile and its badges need; full provenance comes from AssetDetail.
 */
export interface BrowseAssetDTO {
    "id": string;
    "filename": string;
    "captureDate": string | null;
    "mediaType": string;
    "fileSize": number;
    "width": number;
    "height": number;
    "durationSeconds": number;
    "verificationStatus": string;
    "backupStatus": string;
    "isLivePhotoPair": boolean;
    "duplicateOfAssetId": string;
    "hasArchiveCopy": boolean;
}

/**
 * BrowseFilters are the browser grid's optional filters. Empty strings mean "no
 * filter". YearMonth is "2006-01" (capture month).
 */
export interface BrowseFilters {
    "query": string;
    "mediaType": string;
    "verificationStatus": string;
    "backupStatus": string;
    "sessionId": string;
    "yearMonth": string;
}

/**
 * ClassStatDTO is the per-class rollup in a cleanup report.
 */
export interface ClassStatDTO {
    "class": string;
    "count": number;
    "bytes": number;
    "files": string[] | null;
    "truncated": boolean;
}

/**
 * CleanupCompleted is the payload for cleanup:completed, emitted once when a
 * background cleanup analyze finishes. Exactly one terminal state holds: success
 * (Report set), cancelled (Cancelled true), or failed (Error set). Root echoes
 * the analyzed folder so the frontend can restore context on re-attach.
 */
export interface CleanupCompleted {
    "root": string;
    "report": CleanupReportDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * CleanupProgress is the payload for cleanup:progress. FilesDone advances per
 * classified file; FilesTotal is 0 while the analyzer walks-and-classifies in a
 * single pass (the total is not known until the walk completes), so the UI
 * renders an indeterminate count. CurrentFile is the file being classified.
 */
export interface CleanupProgress {
    "filesDone": number;
    "filesTotal": number;
    "currentFile": string;
}

/**
 * CleanupReportDTO is the JSON-friendly cleanup analysis result.
 */
export interface CleanupReportDTO {
    "root": string;
    "classes": ClassStatDTO[] | null;
    "totalFiles": number;
    "mediaFiles": number;
    "nonMedia": number;
    "unreadableMedia": number;
    "archivedNotVerified": number;
    "backupIncomplete": number;
    "dbInconsistencies": number;
    "recommendation": RecommendationDTO;
}

/**
 * CurrentLibraryDTO describes the library currently open, surfaced to the
 * frontend for the Settings → Library card and the root-layout gate.
 */
export interface CurrentLibraryDTO {
    "path": string;
    "name": string;
    "schemaVersion": number;
    "appVersion": string;
    "openedAt": string;
}

/**
 * DashboardStats is the full dashboard payload.
 */
export interface DashboardStats {
    "totals": TotalsDTO;
    "libraryGrowth": MonthCountDTO[] | null;
    "pendingImports": number;
    "backupQueue": BackupSummaryDTO;
    "duplicateCount": number;
    "recentSources": SourceDTO[] | null;
    "safeToEraseSources": SourceDTO[] | null;
    "recentActivity": LogEntryDTO[] | null;
}

/**
 * DryRunReportDTO is the JSON-friendly projection of importer.DryRunReport. It
 * omits the carried-forward hash maps (an internal optimization) and exposes the
 * mode-aware planning counts.
 */
export interface DryRunReportDTO {
    "mode": string;
    "reorganize": boolean;
    "files": number;
    "photos": number;
    "videos": number;
    "alreadyImported": number;
    "duplicates": number;
    "new": number;
    "totalImportBytes": number;
    "estimatedSeconds": number;
    "plannedAdoptions": number;
    "plannedMoves": number;
}

/**
 * DuplicatePairDTO pairs a duplicate asset with the original it duplicates.
 */
export interface DuplicatePairDTO {
    "duplicate": AssetDTO;
    "original": AssetDTO;
}

/**
 * DuplicateProgress is the payload for duplicate:progress, carrying the byte
 * progress of a cross-volume duplicate move (copy+verify).
 */
export interface DuplicateProgress {
    "assetId": string;
    "bytesDone": number;
    "bytesTotal": number;
}

/**
 * ImportCompleted is the payload for import:completed, emitted once when a
 * background import goroutine finishes (successfully, cancelled, or interrupted).
 */
export interface ImportCompleted {
    "sessionId": string;
    "status": string;
    "filesScanned": number;
    "filesImported": number;
    "duplicates": number;
    "failures": number;
    "skipped": number;
}

/**
 * ImportOptions configures StartImport. Root is the source tree. DestinationRoot
 * defaults to the configured Master Library when empty. Mode is "copy" or
 * "adopt"; Reorganize (adopt only) moves files into the standard layout.
 */
export interface ImportOptions {
    "root": string;
    "destinationRoot": string;
    "eventName": string;
    "mode": string;
    "reorganize": boolean;
    "sourceId": string;
}

/**
 * ImportProgress is the payload for import:progress. It mirrors importer.Progress
 * plus the owning session ID (so the frontend can correlate updates) and a
 * derived completion percentage.
 */
export interface ImportProgress {
    "sessionId": string;
    "phase": string;
    "filesDone": number;
    "filesTotal": number;
    "bytesDone": number;
    "bytesTotal": number;
    "currentFile": string;
    "errors": number;
    "percent": number;
    "done": boolean;
}

/**
 * LegacyStatusDTO reports whether a pre-library per-machine catalog exists (so
 * Welcome can offer to migrate it).
 */
export interface LegacyStatusDTO {
    "exists": boolean;
    "path": string;
}

/**
 * LibraryGate is the shared open/closed switch every DB-backed service consults.
 * It is closed until a library is opened (at startup or from Welcome) and reopens
 * atomically once the object graph is bound in place. A nil *LibraryGate is
 * treated as always-open, so services constructed directly in unit tests (which
 * pass no gate) are never gated.
 */
export interface LibraryGate {
}

/**
 * LibraryProgress is the payload for library:progress, emitted during a library
 * open that runs migrations / legacy installation. Phase names the current step
 * ("backing-up", "installing-legacy", "converting-paths", "verifying",
 * "migrating"); Done/Total are populated for determinate phases (0 otherwise).
 * Not cancellable: migrations must run to completion or roll back atomically.
 */
export interface LibraryProgress {
    "phase": string;
    "message": string;
    "done": number;
    "total": number;
}

/**
 * LockConflictDTO carries the structured details of a refused lock so the
 * frontend can present an informed Force Open confirmation.
 */
export interface LockConflictDTO {
    "hostname": string;
    "pid": number;
    "sameHostLive": boolean;
    "heartbeatAgeSeconds": number;
    "message": string;
}

/**
 * LogEntryDTO is the JSON-friendly projection of a persisted LogEntry.
 */
export interface LogEntryDTO {
    "id": number;
    "timestamp": string;
    "level": string;
    "subsystem": string;
    "message": string;
    "metadataJson": string;
}

/**
 * LogExportProgress is the payload for log:export-progress, emitted (throttled)
 * while a log export streams rows to disk. RowsWritten is the running count.
 */
export interface LogExportProgress {
    "rowsWritten": number;
}

/**
 * MatchDTO is the JSON-friendly result of identifying a volume.
 */
export interface MatchDTO {
    "sourceId": string;
    "source": SourceDTO;
    "confidence": number;
    "reasons": string[] | null;
    "isKnown": boolean;
    "contentsPreviouslyImported": boolean;
}

/**
 * MonthCountDTO is one point in the library growth series.
 */
export interface MonthCountDTO {
    /**
     * YYYY-MM
     */
    "month": string;
    "count": number;
}

/**
 * OpenResultDTO is returned by Create/Open/ForceOpen/MigrateLegacy. Exactly one
 * of {Library set}, {LockConflict set}, or {NeedsRelaunch true} is meaningful:
 *   - Library set, NeedsRelaunch false: opened in place, frontend can proceed.
 *   - NeedsRelaunch true: a different library was already open; config was
 *     updated and the app must relaunch to switch (frontend prompts).
 *   - LockConflict set: the library is locked; frontend offers Force Open.
 */
export interface OpenResultDTO {
    "needsRelaunch": boolean;
    "library": CurrentLibraryDTO | null;
    "lockConflict": LockConflictDTO | null;
}

/**
 * OperationInfo is one running long operation reported to the quit guard. Kind is
 * a stable machine token (import | analyze | reorganize | safe_to_erase | cleanup
 * | backup_upload); Label is a human phrase. FilesDone/FilesTotal and
 * BytesDone/BytesTotal are the latest progress snapshot (a zero total means the
 * count is indeterminate). It is JSON-serializable so it can ride the
 * app:quit-requested event payload and the AppService.ActiveOperations binding.
 */
export interface OperationInfo {
    "kind": string;
    "label": string;
    "filesDone": number;
    "filesTotal": number;
    "bytesDone": number;
    "bytesTotal": number;
}

/**
 * PageResult wraps a paginated slice with its total match count so tables can
 * render pagination controls.
 */
export interface PageResult<T> {
    "items": T[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * PluginDTO describes an available backup plugin and its capabilities.
 */
export interface PluginDTO {
    "name": string;
    "supportsVerify": boolean;
    "supportsDelete": boolean;
    "supportsResume": boolean;
    "maxFileSize": number;
}

/**
 * ProviderDTO is the JSON-friendly projection of a BackupProvider.
 */
export interface ProviderDTO {
    "id": string;
    "pluginName": string;
    "configJson": string;
    "enabled": boolean;
}

/**
 * QueueSummaryDTO reports the number of backup jobs in each status.
 */
export interface QueueSummaryDTO {
    "pending": number;
    "running": number;
    "paused": number;
    "completed": number;
    "failed": number;
    "cancelled": number;
    "total": number;
}

/**
 * QuitRequested is the payload for app:quit-requested, emitted when the user
 * tries to quit while long operations are running. The quit is vetoed and this
 * carries the live operations list so the global quit-guard dialog can name each
 * one with current numbers. A repeated quit attempt re-emits with fresh numbers.
 */
export interface QuitRequested {
    "operations": OperationInfo[] | null;
}

/**
 * RecentLibraryDTO is one entry in the recent-libraries list.
 */
export interface RecentLibraryDTO {
    "path": string;
    "name": string;
    "lastOpenedAt": string;
}

/**
 * RecommendationDTO is the delete-safety verdict.
 */
export interface RecommendationDTO {
    "safeToDelete": boolean;
    "title": string;
    "summary": string;
    "reasons": string[] | null;
}

/**
 * ReorganizeMoveDTO is one planned same-drive move in a reorganize preview.
 */
export interface ReorganizeMoveDTO {
    "assetId": string;
    "filename": string;
    "from": string;
    "to": string;
}

/**
 * ReorganizePlanDTO is the JSON-friendly reorganize preview: aggregate counts
 * plus a display-capped sample of moves and skips. Truncated reports whether the
 * move sample was cut to DisplayCap (the counts remain exact).
 */
export interface ReorganizePlanDTO {
    "totalAssets": number;
    "inPlace": number;
    "moves": number;
    "skipped": number;
    "displayCap": number;
    "truncated": boolean;
    "movesSample": ReorganizeMoveDTO[] | null;
    "skippedSample": ReorganizeSkipDTO[] | null;
}

/**
 * ReorganizePlanProgress is the payload for reorganize:plan-progress, emitted
 * (throttled) while PlanReorganize walks the catalog. Total is known up front
 * (after listing archived assets) so the UI can render a determinate bar.
 */
export interface ReorganizePlanProgress {
    "done": number;
    "total": number;
}

/**
 * ReorganizeSkipDTO is one asset the reorganize will not move, with the reason
 * (missing-on-disk, cross-volume, duplicate).
 */
export interface ReorganizeSkipDTO {
    "assetId": string;
    "filename": string;
    "path": string;
    "reason": string;
}

/**
 * SafeToEraseDTO is the JSON-friendly safe-to-erase report.
 */
export interface SafeToEraseDTO {
    "sourceId": string;
    "safe": boolean;
    "reason": string;
    "totalMedia": number;
    "archived": number;
    "new": number;
    "unverified": number;
    "backupIncomplete": number;
}

/**
 * ScanSummary is the provisional result of scanning a source tree, before any
 * hashing or duplicate detection.
 */
export interface ScanSummary {
    "root": string;
    "files": number;
    "photos": number;
    "videos": number;
    "rawPhotos": number;
    "provisionalPairs": number;
    "totalBytes": number;
}

/**
 * SessionDTO is the JSON-friendly projection of an ImportSession. Mode is decoded
 * from the session's resume-state notes so the Import History can badge adopt
 * runs distinctly from copy runs.
 */
export interface SessionDTO {
    "id": string;
    "startedAt": string;
    "completedAt": string | null;
    "durationSeconds": number;
    "sourceId": string;
    "destinationRoot": string;
    "filesScanned": number;
    "filesImported": number;
    "duplicates": number;
    "failures": number;
    "skipped": number;
    "status": string;
    "mode": string;
}

/**
 * SessionDetail bundles a session with the log entries produced during its run.
 * Truncated reports whether the event list was capped (sessionEventsCap); the
 * counts on the session itself always reflect the full run.
 */
export interface SessionDetail {
    "session": SessionDTO;
    "events": LogEntryDTO[] | null;
    "truncated": boolean;
}

/**
 * Settings is the typed, JSON-friendly view of PAIM's configuration returned by
 * SettingsService.GetAll and consumed by main.go to drive the archive layout,
 * backup worker pool, and import concurrency. MetadataAvailable is read-only,
 * derived at runtime from whether exiftool (or the fallback) can extract data.
 */
export interface Settings {
    "masterLibraryRoot": string;
    "backupWorkers": number;
    "maxRetries": number;
    "importConcurrency": number;
    "defaultEventName": string;
    "generateThumbsAfterImport": boolean;
    "metadataAvailable": boolean;
}

/**
 * SleepGuard holds a macOS power-management assertion for the duration of any
 * long-running PAIM operation (import, analyze, reorganize, safe-to-erase,
 * cleanup analyze). While such work is in flight we run `/usr/bin/caffeinate -im`
 * as a child process, which keeps the system (and, with -m, the disk) awake.
 * 
 * WHY: if the Mac sleeps mid-import the filesystem I/O the pipeline depends on is
 * paused — copies stall, hashing halts, and a multi-hour import of a large card
 * can silently wedge until the machine is woken. Holding the assertion for the
 * life of the operation keeps long jobs progressing on an unattended machine.
 * 
 * It is refcounted so several concurrent operations share one assertion: the
 * first Acquire starts the process, the last Release kills it. Shutdown force-
 * kills it regardless of the count so no caffeinate child outlives the app.
 * 
 * The command starter is injected so tests can assert the refcount transitions
 * without spawning a real process.
 */
export interface SleepGuard {
}

/**
 * SnapshotConfigDTO is the per-machine snapshot configuration.
 */
export interface SnapshotConfigDTO {
    "dest": string;
    "interval": string;
}

/**
 * SnapshotStatusDTO is the snapshot config plus the last-run result for the UI.
 */
export interface SnapshotStatusDTO {
    "dest": string;
    "interval": string;
    "enabled": boolean;
    "running": boolean;
    "lastAt": string;
    "lastPath": string;
    "lastError": string;
}

/**
 * SourceDTO is the JSON-friendly projection of an ImportSource.
 */
export interface SourceDTO {
    "id": string;
    "sourceType": string;
    "hardwareSerial": string;
    "filesystemUuid": string;
    "volumeUuid": string;
    "volumeLabel": string;
    "manufacturer": string;
    "model": string;
    "capacityBytes": number;
    "connectionType": string;
    "confidence": number;
    "confidenceReason": string;
    "lastSeenAt": string;
    "importCount": number;
    "safeToErase": boolean;
    "safeToEraseReason": string;
}

/**
 * SourceEvaluated is the payload for source:evaluated, emitted once when a
 * background safe-to-erase evaluation finishes. Exactly one terminal state
 * holds: success (Report set), cancelled (Cancelled true), or failed (Error set).
 */
export interface SourceEvaluated {
    "mountPoint": string;
    "sourceId": string;
    "report": SafeToEraseDTO | null;
    "cancelled": boolean;
    "error": string;
}

/**
 * SourceIdentified is the payload for source:identified, emitted after a volume
 * is identified and persisted.
 */
export interface SourceIdentified {
    "mountPoint": string;
    "sourceId": string;
    "confidence": number;
    "isKnown": boolean;
}

/**
 * SourceProgress is the payload for source:progress, carrying the progress of a
 * long-running source operation. Kind is "safe-to-erase" (determinate:
 * FilesTotal is known) or "identify" (indeterminate: only Scanned advances,
 * FilesTotal is 0). MountPoint correlates the update with a volume card.
 */
export interface SourceProgress {
    "kind": string;
    "mountPoint": string;
    "filesDone": number;
    "filesTotal": number;
    "scanned": number;
    "currentFile": string;
}

/**
 * StartAnalyzeResult is returned immediately from StartAnalyze once the
 * background analyze has been launched. Root echoes the resolved source root; an
 * analyze is sessionless (no ImportSession is created), so it is re-attached via
 * ActiveAnalyze rather than by a session ID.
 */
export interface StartAnalyzeResult {
    "root": string;
}

/**
 * StartCleanupAnalyzeResult is returned immediately from StartCleanupAnalyze once
 * the background analysis has been launched. Root echoes the analyzed folder; the
 * analysis is re-attached via ActiveCleanupAnalyze (only one runs at a time).
 */
export interface StartCleanupAnalyzeResult {
    "root": string;
}

/**
 * StartImportResult is returned immediately from StartImport once the session is
 * created and the background run has been launched.
 */
export interface StartImportResult {
    "sessionId": string;
}

/**
 * StartSafeToEraseResult is returned immediately from StartSafeToErase once the
 * background evaluation has been launched. MountPoint echoes the volume; the
 * evaluation is re-attached via ActiveSafeToErase (keyed by nothing — only one
 * runs at a time).
 */
export interface StartSafeToEraseResult {
    "mountPoint": string;
}

/**
 * ThumbCacheDTO describes where the thumbnail cache currently lives and the two
 * possible locations, so the Settings UI can render the choice and the active
 * path.
 */
export interface ThumbCacheDTO {
    /**
     * "library" | "local"
     */
    "location": string;

    /**
     * where thumbnails are written today
     */
    "activeDir": string;

    /**
     * <root>/.paim/thumbs
     */
    "libraryDir": string;

    /**
     * app-support/thumbs/<libraryId>
     */
    "localDir": string;
}

/**
 * ThumbsProgress is the payload for thumbs:progress, emitted (throttled) while a
 * thumbnail warm-up runs. Done/Total count assets processed; Label distinguishes
 * a whole-catalog warm-up from a post-import one so the UI can word it. Done ==
 * Total with Running=false marks completion.
 */
export interface ThumbsProgress {
    "done": number;
    "total": number;
    "label": string;
    "running": boolean;
}

/**
 * TotalsDTO holds the library totals.
 */
export interface TotalsDTO {
    "assets": number;
    "photos": number;
    "videos": number;
    "livePhotos": number;
    "storageBytes": number;
}

/**
 * VersionInfo is the build-stamped application version surfaced to the frontend
 * (Settings → About, Welcome subtitle). Commit and Date are empty in a dev build;
 * Full is always non-empty (it degrades to "<version> (dev)").
 */
export interface VersionInfo {
    "version": string;
    "commit": string;
    "date": string;
    "full": string;
}

/**
 * VolumeDTO is the JSON-friendly projection of a mounted volume description.
 */
export interface VolumeDTO {
    "mountPoint": string;
    "volumeName": string;
    "volumeUuid": string;
    "filesystemUuid": string;
    "filesystemType": string;
    "capacityBytes": number;
    "freeBytes": number;
    "removable": boolean;
    "internal": boolean;
    "ejectable": boolean;
    "connectionType": string;
    "hardwareSerial": string;
    "manufacturer": string;
    "model": string;
    "isNetworkVolume": boolean;
    "networkUrl": string;
    "warnings": string[] | null;
}

/**
 * VolumeEvent is the payload for volume:mounted and volume:unmounted.
 */
export interface VolumeEvent {
    "mountPoint": string;
}

/**
 * WarmupStatusDTO is the re-attachment snapshot of the current warm-up.
 */
export interface WarmupStatusDTO {
    "running": boolean;
    "done": number;
    "total": number;
    "label": string;
}
