// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderService manages configured backup destinations (BackupProvider rows)
 * and reports the plugins available to back them. Provider CRUD is performed
 * directly over GORM (repo has no provider repository); the registry is used to
 * validate a provider's config via a plugin Initialize probe and to enumerate
 * available plugins with their capabilities.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add validates configJSON against the named plugin (via an Initialize probe)
 * and, on success, creates an enabled provider. mirror marks a quality-of-life
 * destination (its jobs never block a safety verdict); uploadOrder controls claim
 * order (oldest_first FIFO or newest_first). The mirror flag is also stamped into
 * the rclone config so the plugin can enforce its multi-remote-pool rules.
 */
export function Add(pluginName: string, configJSON: string, mirror: boolean, uploadOrder: string, mediaScope: string): $CancellablePromise<$models.ProviderDTO> {
    return $Call.ByID(3798959424, pluginName, configJSON, mirror, uploadOrder, mediaScope);
}

/**
 * AvailablePlugins lists the registered plugins with their capabilities.
 */
export function AvailablePlugins(): $CancellablePromise<$models.PluginDTO[] | null> {
    return $Call.ByID(898994396);
}

/**
 * Bind wires the ProviderService to an open library's catalog in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(2685491282, core);
}

/**
 * List returns every configured provider (including disabled ones).
 */
export function List(): $CancellablePromise<$models.ProviderDTO[] | null> {
    return $Call.ByID(2224840357);
}

/**
 * RcloneRemoteInfo probes one rclone remote's backend type and checksum support.
 * It is not gated on an open library (it inspects rclone config, not the catalog).
 * A probe failure is returned inline (Error set) rather than as a hard error so
 * the UI degrades to the manual Mirror toggle.
 */
export function RcloneRemoteInfo(remote: string): $CancellablePromise<$models.RcloneRemoteInfoDTO> {
    return $Call.ByID(3792459144, remote);
}

/**
 * RcloneRemotes resolves the rclone binary and lists its configured remotes so
 * the Add flow can present a dropdown. A missing binary is reported as a typed
 * "not installed" state (Installed=false) rather than an error, so the UI can
 * render setup guidance.
 */
export function RcloneRemotes(): $CancellablePromise<$models.RcloneRemotesDTO> {
    return $Call.ByID(3498411557);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(1064554728, gate);
}

/**
 * Update revalidates configJSON against the provider's plugin and persists the
 * new config, enabled flag, mirror flag, and upload order.
 */
export function Update(id: string, configJSON: string, enabled: boolean, mirror: boolean, uploadOrder: string, mediaScope: string): $CancellablePromise<$models.ProviderDTO> {
    return $Call.ByID(4249247096, id, configJSON, enabled, mirror, uploadOrder, mediaScope);
}
