// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService reads and writes application settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the SettingsService to an open library's settings repo in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(3528820422, core);
}

/**
 * GetAll returns the typed settings with defaults applied and the read-only
 * MetadataAvailable flag populated.
 */
export function GetAll(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3320771594);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(3296246396, gate);
}

/**
 * Update persists the writable settings. Changing MasterLibraryRoot revalidates
 * that the path exists and is a directory before storing it (an empty root is
 * allowed — the library has not been chosen yet). MetadataAvailable is read-only
 * and ignored. Changes to worker/retry/concurrency counts take effect on the
 * next application start (the running Manager/Pipeline are configured at boot).
 */
export function Update($in: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3458506124, $in);
}
