// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService manages the one-way, disaster-recovery catalog snapshots: a
 * per-machine destination folder + interval, a manual "Snapshot now", and the
 * automatic triggers (a timer while the app is open + on graceful quit). The
 * destination/interval are stored in the per-machine library.Config, never in the
 * library DB. Snapshots are insurance only — they are never opened as the live
 * catalog. Failures (destination missing/unplugged) are recorded and logged, then
 * retried next interval; they never block anything.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the SnapshotService to an open library's catalog handle and path.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(1297539067, core);
}

/**
 * GetSnapshotConfig returns the current per-machine snapshot configuration.
 */
export function GetSnapshotConfig(): $CancellablePromise<$models.SnapshotConfigDTO> {
    return $Call.ByID(2998969234);
}

/**
 * PickSnapshotDest opens a native directory chooser for the snapshot destination.
 */
export function PickSnapshotDest(): $CancellablePromise<string> {
    return $Call.ByID(244770405);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(740257355, gate);
}

/**
 * SetSnapshotConfig persists the snapshot destination/interval and re-arms the
 * timer. An empty destination disables snapshots.
 */
export function SetSnapshotConfig($in: $models.SnapshotConfigDTO): $CancellablePromise<$models.SnapshotStatusDTO> {
    return $Call.ByID(1818418214, $in);
}

/**
 * SnapshotNow runs a snapshot immediately (the manual "Snapshot now" button). It
 * returns an error only when the destination is unconfigured; a copy failure is
 * recorded in the returned status (LastError) and logged, not returned as an
 * error, so the UI shows it inline.
 */
export function SnapshotNow(): $CancellablePromise<$models.SnapshotStatusDTO> {
    return $Call.ByID(1149921416);
}

/**
 * SnapshotOnQuit runs a final snapshot during graceful shutdown when a
 * destination is configured and the interval is not "off". It is best-effort and
 * bounded by the caller's context; it never blocks the quit path on failure.
 */
export function SnapshotOnQuit(): $CancellablePromise<void> {
    return $Call.ByID(78899914);
}

/**
 * SnapshotStatus returns the config plus the last-run result.
 */
export function SnapshotStatus(): $CancellablePromise<$models.SnapshotStatusDTO> {
    return $Call.ByID(1356212306);
}

/**
 * StartTimer launches the interval timer for the life of ctx. It re-reads the
 * configured interval whenever SetSnapshotConfig signals reconfigure, snapshots
 * on each tick, and idles (waiting only on reconfigure/ctx) when the interval has
 * no timer (off / quit-only) or no destination is set.
 */
export function StartTimer(): $CancellablePromise<void> {
    return $Call.ByID(1801246505);
}
