// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourcesService lists volumes, identifies import sources, and evaluates
 * safe-to-erase.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveSafeToErase returns the current evaluation state for re-attachment:
 * "running" with the latest progress snapshot, "completed" with the report (or a
 * cancelled/failed marker), or "none". A completed snapshot lapses to "none"
 * after safeEraseReportTTL.
 * @returns {$CancellablePromise<$models.ActiveSafeToEraseDTO>}
 */
export function ActiveSafeToErase() {
    return $Call.ByID(1201452976).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Bind wires the SourcesService to an open library's identifier and repos in
 * place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(1781319071, core);
}

/**
 * CancelIdentify aborts an in-flight IdentifyVolume call (if any) by cancelling
 * its derived context, unwinding the fingerprint walk. It is a no-op when no
 * identification is running.
 * @returns {$CancellablePromise<void>}
 */
export function CancelIdentify() {
    return $Call.ByID(1936244550);
}

/**
 * CancelSafeToErase cancels the active safe-to-erase evaluation (if any). It is a
 * no-op when nothing is running.
 * @returns {$CancellablePromise<void>}
 */
export function CancelSafeToErase() {
    return $Call.ByID(4142348336);
}

/**
 * IdentifyVolume identifies the volume at mountPoint, persists the resulting
 * source (creating a new record or updating the matched one and its LastSeen),
 * emits source:identified, and returns the match with confidence and reasons.
 * @param {string} mountPoint
 * @returns {$CancellablePromise<$models.MatchDTO>}
 */
export function IdentifyVolume(mountPoint) {
    return $Call.ByID(3239382622, mountPoint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListKnownSources returns the most recently seen persisted sources.
 * @returns {$CancellablePromise<$models.SourceDTO[]>}
 */
export function ListKnownSources() {
    return $Call.ByID(3142920755).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListVolumes enumerates and describes every mounted volume under /Volumes.
 * @returns {$CancellablePromise<$models.VolumeDTO[]>}
 */
export function ListVolumes() {
    return $Call.ByID(2030789603).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(47600799, gate);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 * @param {$models.SleepGuard | null} g
 * @returns {$CancellablePromise<void>}
 */
export function SetSleepGuard(g) {
    return $Call.ByID(1264687288, g);
}

/**
 * StartSafeToErase launches a background safe-to-erase evaluation of the volume
 * at mountPoint. Only one evaluation may run at a time (ErrSafeToEraseInProgress
 * otherwise). It emits throttled source:progress (kind "safe-to-erase") while
 * hashing and a terminal source:evaluated when it finishes; the completed report
 * is retained for re-attachment (ActiveSafeToErase) for safeEraseReportTTL. A
 * running evaluation is cancelled via CancelSafeToErase.
 * @param {string} sourceID
 * @param {string} mountPoint
 * @returns {$CancellablePromise<$models.StartSafeToEraseResult>}
 */
export function StartSafeToErase(sourceID, mountPoint) {
    return $Call.ByID(3941016818, sourceID, mountPoint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * StartWatching runs the volume watcher until ctx is cancelled, emitting
 * volume:mounted / volume:unmounted for each change. It is invoked once from
 * main.go in a background goroutine; the watcher establishes its baseline from
 * the volumes already mounted at start (which produce no events).
 * @returns {$CancellablePromise<void>}
 */
export function StartWatching() {
    return $Call.ByID(2506465009);
}

// Private type creation functions
const $$createType0 = $models.ActiveSafeToEraseDTO.createFrom;
const $$createType1 = $models.MatchDTO.createFrom;
const $$createType2 = $models.SourceDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.VolumeDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.StartSafeToEraseResult.createFrom;
