// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourcesService lists volumes, identifies import sources, and evaluates
 * safe-to-erase.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveClearSource returns the current clear job's state for re-attachment.
 */
export function ActiveClearSource(): $CancellablePromise<$models.ActiveClearSourceDTO> {
    return $Call.ByID(3666593646);
}

/**
 * ActiveSafeToErase returns the current evaluation state for re-attachment:
 * "running" with the latest progress snapshot, "completed" with the report (or a
 * cancelled/failed marker), or "none". A completed snapshot lapses to "none"
 * after safeEraseReportTTL.
 */
export function ActiveSafeToErase(): $CancellablePromise<$models.ActiveSafeToEraseDTO> {
    return $Call.ByID(1201452976);
}

/**
 * Bind wires the SourcesService to an open library's identifier and repos in
 * place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(1781319071, core);
}

/**
 * CancelClearSource cancels a running clear (if any). Files already moved stay
 * moved; the job stops cleanly before the next file.
 */
export function CancelClearSource(): $CancellablePromise<void> {
    return $Call.ByID(2312521710);
}

/**
 * CancelIdentify aborts an in-flight IdentifyVolume call (if any) by cancelling
 * its derived context, unwinding the fingerprint walk. It is a no-op when no
 * identification is running.
 */
export function CancelIdentify(): $CancellablePromise<void> {
    return $Call.ByID(1936244550);
}

/**
 * CancelSafeToErase cancels the active safe-to-erase evaluation (if any). It is a
 * no-op when nothing is running.
 */
export function CancelSafeToErase(): $CancellablePromise<void> {
    return $Call.ByID(4142348336);
}

/**
 * ClearSourcePreview validates the clear gate for root and returns the confirm-
 * dialog inputs (file count, total bytes, trash destination). It returns a typed
 * gate error when the evaluation is missing, stale, red, for a different root, or
 * when root overlaps the library.
 */
export function ClearSourcePreview(root: string): $CancellablePromise<$models.ClearSourcePreviewDTO> {
    return $Call.ByID(4285950892, root);
}

/**
 * EjectVolume ejects the volume mounted at mountPoint via `diskutil eject`, with
 * two server-side safety guards it NEVER delegates to the frontend:
 * 
 *  1. it refuses to eject the volume the open library lives on
 *     (ErrEjectLibraryVolume); and
 *  2. it refuses when any tracked long operation (import/analyze/reorganize/
 *     safe-to-erase/clear/cleanup) is currently touching a path on that volume,
 *     naming the reason.
 * 
 * The OS is the final backstop: `diskutil eject` itself fails (surfaced here as a
 * readable message) if the volume has open files, so a case the path guards do
 * not cover — e.g. a backup writing to a destination on this volume — still can
 * never eject a busy disk. On success the volume unmounts and the existing
 * volume:unmounted watcher event refreshes the UI. Logged under the source
 * subsystem.
 */
export function EjectVolume(mountPoint: string): $CancellablePromise<void> {
    return $Call.ByID(1159049947, mountPoint);
}

/**
 * IdentifyVolume identifies the volume at mountPoint, persists the resulting
 * source (creating a new record or updating the matched one and its LastSeen),
 * emits source:identified, and returns the match with confidence and reasons.
 */
export function IdentifyVolume(mountPoint: string): $CancellablePromise<$models.MatchDTO> {
    return $Call.ByID(3239382622, mountPoint);
}

/**
 * ListKnownSources returns the most recently seen persisted sources.
 */
export function ListKnownSources(): $CancellablePromise<$models.SourceDTO[] | null> {
    return $Call.ByID(3142920755);
}

/**
 * ListVolumes enumerates and describes every mounted volume under /Volumes.
 */
export function ListVolumes(): $CancellablePromise<$models.VolumeDTO[] | null> {
    return $Call.ByID(2030789603);
}

/**
 * SetActivity injects the shared activity tracker so EjectVolume can refuse
 * ejecting a volume an in-flight operation is using. Called once from main.go.
 */
export function SetActivity(a: $models.ejectActivity): $CancellablePromise<void> {
    return $Call.ByID(2806359957, a);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(47600799, gate);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 */
export function SetSleepGuard(g: $models.SleepGuard | null): $CancellablePromise<void> {
    return $Call.ByID(1264687288, g);
}

/**
 * StartClearSource launches a background job that moves every evaluated-safe media
 * file under root into <root>/.paim-trash/<yyyymmdd-hhmmss>/, preserving each
 * file's path relative to root (so identically-named files across subfolders never
 * collide). It is gated: a fresh GREEN safe-to-erase evaluation for exactly this
 * root must exist (validateClearGate), else a typed error the UI renders as
 * "evaluate first". PAIM never hard-deletes — the user formats the card or empties
 * the trash folder afterward. Files that are not evaluated-safe are never touched.
 * 
 * The job is cancellable between files: cancelling stops cleanly before the next
 * move; files already moved stay moved (they are provably safe — that is the whole
 * point). It is activity-tracked (quit guard) and sleep-guarded.
 */
export function StartClearSource(root: string): $CancellablePromise<$models.StartClearSourceResult> {
    return $Call.ByID(2705697556, root);
}

/**
 * StartSafeToErase launches a background safe-to-erase evaluation of the volume
 * at mountPoint. Only one evaluation may run at a time (ErrSafeToEraseInProgress
 * otherwise). It emits throttled source:progress (kind "safe-to-erase") while
 * hashing and a terminal source:evaluated when it finishes; the completed report
 * is retained for re-attachment (ActiveSafeToErase) for safeEraseReportTTL. A
 * running evaluation is cancelled via CancelSafeToErase.
 */
export function StartSafeToErase(sourceID: string, mountPoint: string): $CancellablePromise<$models.StartSafeToEraseResult> {
    return $Call.ByID(3941016818, sourceID, mountPoint);
}

/**
 * StartWatching runs the volume watcher until ctx is cancelled, emitting
 * volume:mounted / volume:unmounted for each change. It is invoked once from
 * main.go in a background goroutine; the watcher establishes its baseline from
 * the volumes already mounted at start (which produce no events).
 */
export function StartWatching(): $CancellablePromise<void> {
    return $Call.ByID(2506465009);
}
