// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourcesService lists volumes, identifies import sources, and evaluates
 * safe-to-erase.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the SourcesService to an open library's identifier and repos in
 * place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(1781319071, core);
}

/**
 * EvaluateSafeToErase walks the volume at mountPoint, decides whether it is safe
 * to erase, persists the conclusion on the source (when sourceID is set), and
 * returns the report.
 */
export function EvaluateSafeToErase(sourceID: string, mountPoint: string): $CancellablePromise<$models.SafeToEraseDTO> {
    return $Call.ByID(2071845607, sourceID, mountPoint);
}

/**
 * IdentifyVolume identifies the volume at mountPoint, persists the resulting
 * source (creating a new record or updating the matched one and its LastSeen),
 * emits source:identified, and returns the match with confidence and reasons.
 */
export function IdentifyVolume(mountPoint: string): $CancellablePromise<$models.MatchDTO> {
    return $Call.ByID(3239382622, mountPoint);
}

/**
 * ListKnownSources returns the most recently seen persisted sources.
 */
export function ListKnownSources(): $CancellablePromise<$models.SourceDTO[] | null> {
    return $Call.ByID(3142920755);
}

/**
 * ListVolumes enumerates and describes every mounted volume under /Volumes.
 */
export function ListVolumes(): $CancellablePromise<$models.VolumeDTO[] | null> {
    return $Call.ByID(2030789603);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(47600799, gate);
}

/**
 * StartWatching runs the volume watcher until ctx is cancelled, emitting
 * volume:mounted / volume:unmounted for each change. It is invoked once from
 * main.go in a background goroutine; the watcher establishes its baseline from
 * the volumes already mounted at start (which produce no events).
 */
export function StartWatching(): $CancellablePromise<void> {
    return $Call.ByID(2506465009);
}
