// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThumbnailService owns the disposable thumbnail cache's per-machine concerns:
 * where the cache lives (in-library vs this Mac's local disk), clearing it, and
 * warming it ahead of browsing. The cache location is stored in the per-machine
 * library.Config (not the library DB) because it is a machine-local performance
 * preference. Warm-up is a single-instance background job registered with the
 * activity tracker (quit-guard aware) and the sleep guard; it deliberately does
 * NOT share the import one-active guard, so it never blocks an import.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the ThumbnailService to an open library's cache, resolver, and repos
 * in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(2283657781, core);
}

/**
 * CancelWarmup cancels the active warm-up (if any). It is a no-op when nothing is
 * running.
 * @returns {$CancellablePromise<void>}
 */
export function CancelWarmup() {
    return $Call.ByID(3250378820);
}

/**
 * ClearThumbnailCache deletes the contents of the ACTIVE cache directory. It
 * verifies the active dir is one of the two known cache roots for this library
 * before removing anything, so a mis-set path can never delete unrelated files.
 * @returns {$CancellablePromise<void>}
 */
export function ClearThumbnailCache() {
    return $Call.ByID(847647677);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(4186376193, gate);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 * @param {$models.SleepGuard | null} g
 * @returns {$CancellablePromise<void>}
 */
export function SetSleepGuard(g) {
    return $Call.ByID(3569740906, g);
}

/**
 * SetThumbnailCacheLocation persists the per-machine cache-location preference and
 * re-points the live cache immediately. The old location is left in place (its
 * contents are disposable). location must be "library" or "local".
 * @param {string} location
 * @returns {$CancellablePromise<$models.ThumbCacheDTO>}
 */
export function SetThumbnailCacheLocation(location) {
    return $Call.ByID(2686881747, location).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetThumbnailParallelism persists the per-machine generation parallelism and
 * applies it to the live cache immediately (shared by interactive browsing and
 * the warm-up). The requested value is clamped to [1, MaxThumbnailParallelism];
 * the clamped value is returned.
 * @param {number} n
 * @returns {$CancellablePromise<number>}
 */
export function SetThumbnailParallelism(n) {
    return $Call.ByID(83115572, n);
}

/**
 * StartWarmupAll pre-generates 512px thumbnails for the whole catalog. It is
 * resumable (cache hits are skipped instantly), so re-running after a partial run
 * finishes the rest. Refused with ErrWarmupInProgress if one is already running.
 * @returns {$CancellablePromise<$models.WarmupStatusDTO>}
 */
export function StartWarmupAll() {
    return $Call.ByID(815335301).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ThumbnailCacheLocation returns the current cache location and paths.
 * @returns {$CancellablePromise<$models.ThumbCacheDTO>}
 */
export function ThumbnailCacheLocation() {
    return $Call.ByID(1453629195).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ThumbnailParallelism returns the per-machine thumbnail generation parallelism,
 * normalized to the supported range (the default when unset).
 * @returns {$CancellablePromise<number>}
 */
export function ThumbnailParallelism() {
    return $Call.ByID(1355637308);
}

/**
 * WarmSessionIfEnabled warms exactly the assets a just-completed import/adopt
 * session added, when the "Generate thumbnails after import" setting is on. It is
 * the after-import trigger, invoked by the composition root when import:completed
 * is emitted; it never blocks the import (it runs after completion) and quietly
 * no-ops when the setting is off, the session added no archived assets (e.g. a
 * reorganize session), or a warm-up is already running. Errors are returned for
 * the caller to log but are non-fatal.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function WarmSessionIfEnabled(sessionID) {
    return $Call.ByID(3475698635, sessionID);
}

/**
 * WarmupStatus returns the current warm-up state so the Library header can render
 * compact progress and decide whether to offer the "Pre-generate all" action.
 * @returns {$CancellablePromise<$models.WarmupStatusDTO>}
 */
export function WarmupStatus() {
    return $Call.ByID(891431752).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ThumbCacheDTO.createFrom;
const $$createType1 = $models.WarmupStatusDTO.createFrom;
