// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThumbnailService owns the disposable thumbnail cache's per-machine concerns:
 * where the cache lives (in-library vs this Mac's local disk), clearing it, and
 * warming it ahead of browsing. The cache location is stored in the per-machine
 * library.Config (not the library DB) because it is a machine-local performance
 * preference. Warm-up is a single-instance background job registered with the
 * activity tracker (quit-guard aware) and the sleep guard; it deliberately does
 * NOT share the import one-active guard, so it never blocks an import.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the ThumbnailService to an open library's cache, resolver, and repos
 * in place.
 */
export function Bind(core: $models.AppCore | null): $CancellablePromise<void> {
    return $Call.ByID(2283657781, core);
}

/**
 * CancelWarmup cancels the active warm-up (if any). It is a no-op when nothing is
 * running.
 */
export function CancelWarmup(): $CancellablePromise<void> {
    return $Call.ByID(3250378820);
}

/**
 * ClearThumbnailCache deletes the contents of the ACTIVE cache directory. It
 * verifies the active dir is one of the two known cache roots for this library
 * before removing anything, so a mis-set path can never delete unrelated files.
 */
export function ClearThumbnailCache(): $CancellablePromise<void> {
    return $Call.ByID(847647677);
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 */
export function SetGate(gate: $models.LibraryGate | null): $CancellablePromise<void> {
    return $Call.ByID(4186376193, gate);
}

/**
 * SetSleepGuard injects the shared sleep guard. Called once by main.go after
 * construction; left unset (no-op) in unit tests.
 */
export function SetSleepGuard(g: $models.SleepGuard | null): $CancellablePromise<void> {
    return $Call.ByID(3569740906, g);
}

/**
 * SetThumbnailCacheLocation persists the per-machine cache-location preference and
 * re-points the live cache immediately. The old location is left in place (its
 * contents are disposable). location must be "library" or "local".
 */
export function SetThumbnailCacheLocation(location: string): $CancellablePromise<$models.ThumbCacheDTO> {
    return $Call.ByID(2686881747, location);
}

/**
 * StartWarmupAll pre-generates 512px thumbnails for the whole catalog. It is
 * resumable (cache hits are skipped instantly), so re-running after a partial run
 * finishes the rest. Refused with ErrWarmupInProgress if one is already running.
 */
export function StartWarmupAll(): $CancellablePromise<$models.WarmupStatusDTO> {
    return $Call.ByID(815335301);
}

/**
 * ThumbnailCacheLocation returns the current cache location and paths.
 */
export function ThumbnailCacheLocation(): $CancellablePromise<$models.ThumbCacheDTO> {
    return $Call.ByID(1453629195);
}

/**
 * WarmSessionIfEnabled warms exactly the assets a just-completed import/adopt
 * session added, when the "Generate thumbnails after import" setting is on. It is
 * the after-import trigger, invoked by the composition root when import:completed
 * is emitted; it never blocks the import (it runs after completion) and quietly
 * no-ops when the setting is off, the session added no archived assets (e.g. a
 * reorganize session), or a warm-up is already running. Errors are returned for
 * the caller to log but are non-fatal.
 */
export function WarmSessionIfEnabled(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3475698635, sessionID);
}

/**
 * WarmupStatus returns the current warm-up state so the Library header can render
 * compact progress and decide whether to offer the "Pre-generate all" action.
 */
export function WarmupStatus(): $CancellablePromise<$models.WarmupStatusDTO> {
    return $Call.ByID(891431752);
}
