// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Analyzer performs read-only cleanup analysis.
 */
export interface Analyzer {
    /**
     * Root is the portable-library root used to resolve assets' relative
     * CurrentArchivePath values to absolute paths before reading/stat'ing the
     * archived files. Empty leaves stored paths as-is (dev/legacy absolute paths).
     */
    "Root": string;
}
