// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Collector describes and enumerates mounted volumes. It shells out to
 * diskutil, system_profiler and mount; all calls are context-bounded and
 * failures degrade gracefully into Info.Warnings.
 */
export interface Collector {
}
