// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AssetRepo persists and queries Asset rows.
 */
export interface AssetRepo {
}

/**
 * BackupRepo persists and queries the BackupJob queue. The BackupJob rows are
 * the queue, which makes the backup system restart-safe by construction.
 */
export interface BackupRepo {
}

/**
 * LogRepo persists and queries LogEntry rows for the Logs page.
 */
export interface LogRepo {
}

/**
 * SessionRepo persists and queries ImportSession rows.
 */
export interface SessionRepo {
}

/**
 * SettingsRepo persists key/value application settings. Values are stored as JSON
 * in the Setting.ValueJSON column.
 */
export interface SettingsRepo {
}

/**
 * SourceRepo persists and queries ImportSource rows.
 */
export interface SourceRepo {
}
