// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AssetRepo persists and queries Asset rows.
 */
export class AssetRepo {
    /**
     * Creates a new AssetRepo instance.
     * @param {Partial<AssetRepo>} [$$source = {}] - The source object to create the AssetRepo.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetRepo(/** @type {Partial<AssetRepo>} */($$parsedSource));
    }
}

/**
 * BackupRepo persists and queries the BackupJob queue. The BackupJob rows are
 * the queue, which makes the backup system restart-safe by construction.
 */
export class BackupRepo {
    /**
     * Creates a new BackupRepo instance.
     * @param {Partial<BackupRepo>} [$$source = {}] - The source object to create the BackupRepo.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupRepo(/** @type {Partial<BackupRepo>} */($$parsedSource));
    }
}

/**
 * ImportFailureRepo persists and queries ImportFailure rows — the structured,
 * resolvable per-file failure records produced during an import.
 */
export class ImportFailureRepo {
    /**
     * Creates a new ImportFailureRepo instance.
     * @param {Partial<ImportFailureRepo>} [$$source = {}] - The source object to create the ImportFailureRepo.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportFailureRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportFailureRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportFailureRepo(/** @type {Partial<ImportFailureRepo>} */($$parsedSource));
    }
}

/**
 * LogRepo persists and queries LogEntry rows for the Logs page.
 */
export class LogRepo {
    /**
     * Creates a new LogRepo instance.
     * @param {Partial<LogRepo>} [$$source = {}] - The source object to create the LogRepo.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogRepo(/** @type {Partial<LogRepo>} */($$parsedSource));
    }
}

/**
 * SessionRepo persists and queries ImportSession rows.
 */
export class SessionRepo {
    /**
     * Creates a new SessionRepo instance.
     * @param {Partial<SessionRepo>} [$$source = {}] - The source object to create the SessionRepo.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRepo(/** @type {Partial<SessionRepo>} */($$parsedSource));
    }
}

/**
 * SettingsRepo persists key/value application settings. Values are stored as JSON
 * in the Setting.ValueJSON column.
 */
export class SettingsRepo {
    /**
     * Creates a new SettingsRepo instance.
     * @param {Partial<SettingsRepo>} [$$source = {}] - The source object to create the SettingsRepo.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsRepo(/** @type {Partial<SettingsRepo>} */($$parsedSource));
    }
}

/**
 * SourceRepo persists and queries ImportSource rows.
 */
export class SourceRepo {
    /**
     * Creates a new SourceRepo instance.
     * @param {Partial<SourceRepo>} [$$source = {}] - The source object to create the SourceRepo.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceRepo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceRepo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceRepo(/** @type {Partial<SourceRepo>} */($$parsedSource));
    }
}
