// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Meta describes an opened library's catalog: where it lives and the versioning
 * metadata recorded in library_meta.
 */
export interface Meta {
    "Root": string;
    "DBPath": string;
    "SchemaVersion": number;
    "CreatedByAppVersion": string;
    "CreatedAt": string;
    "LastOpenedByAppVersion": string;
    "LastOpenedAt": string;
}
