// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Meta describes an opened library's catalog: where it lives and the versioning
 * metadata recorded in library_meta.
 */
export class Meta {
    /**
     * Creates a new Meta instance.
     * @param {Partial<Meta>} [$$source = {}] - The source object to create the Meta.
     */
    constructor($$source = {}) {
        if (!("Root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Root"] = "";
        }
        if (!("DBPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DBPath"] = "";
        }
        if (!("SchemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["SchemaVersion"] = 0;
        }
        if (!("CreatedByAppVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedByAppVersion"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("LastOpenedByAppVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LastOpenedByAppVersion"] = "";
        }
        if (!("LastOpenedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LastOpenedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Meta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Meta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Meta(/** @type {Partial<Meta>} */($$parsedSource));
    }
}
