// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Identifier identifies import sources and evaluates whether they are safe to
 * erase. Construct it with NewIdentifier.
 */
export interface Identifier {
}
