// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Cache is a content-addressed thumbnail cache. Its directory is normally
 * <root>/.paim/thumbs but may be re-pointed at runtime (see Repoint) when the
 * user moves the cache to this Mac's local disk; dmu guards the mutable dir so
 * concurrent Ensure calls and a Repoint never race.
 */
export interface Cache {
}
