// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Cache is a content-addressed thumbnail cache rooted at <root>/.paim/thumbs.
 */
export class Cache {
    /**
     * Creates a new Cache instance.
     * @param {Partial<Cache>} [$$source = {}] - The source object to create the Cache.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cache instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Cache}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cache(/** @type {Partial<Cache>} */($$parsedSource));
    }
}
