// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Manager runs the backup worker pool over the SQLite-persisted job queue. It is
 * restart-safe: on start it reverts jobs left running (from a crash) to pending,
 * and on stop it does the same for in-flight jobs it could not finish.
 * 
 * Retry backoff is held in memory (BackupJob has no next-attempt column): a job
 * that fails transiently is marked failed, then requeued to pending only once
 * its backoff elapses. A process restart therefore resets outstanding backoff
 * timers and requeues those jobs immediately, which is acceptable per the spec.
 */
export class Manager {
    /**
     * Creates a new Manager instance.
     * @param {Partial<Manager>} [$$source = {}] - The source object to create the Manager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Manager(/** @type {Partial<Manager>} */($$parsedSource));
    }
}
