// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    StructField,
    Value
} from "./models.js";

import * as $models from "./models.js";

/**
 * A StructTag is the tag string in a struct field.
 * 
 * By convention, tag strings are a concatenation of
 * optionally space-separated key:"value" pairs.
 * Each key is a non-empty string consisting of non-control
 * characters other than space (U+0020 ' '), quote (U+0022 '"'),
 * and colon (U+003A ':').  Each value is quoted using U+0022 '"'
 * characters and Go string literal syntax.
 * @typedef {$models.StructTag} StructTag
 */

/**
 * Type is the representation of a Go type.
 * 
 * Not all methods apply to all kinds of types. Restrictions,
 * if any, are noted in the documentation for each method.
 * Use the Kind method to find out the kind of type before
 * calling kind-specific methods. Calling a method
 * inappropriate to the kind of type causes a run-time panic.
 * 
 * Type values are comparable, such as with the == operator,
 * so they can be used as map keys.
 * Two Type values are equal if they represent identical types.
 * @typedef {$models.Type} Type
 */
