// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Interface logger interface
 * @typedef {$models.Interface} Interface
 */
