// Central re-export of the generated Wails bindings. Every service call and
// every DTO type used in the frontend flows through here so the (long,
// generated) import path lives in exactly one place. NEVER call fetch/axios —
// all backend access is through these bindings.
export {
  AppService,
  BackupService,
  BrowserService,
  CleanupService,
  DashboardService,
  DuplicateService,
  HistoryService,
  ImportService,
  LibraryService,
  LogService,
  ProviderService,
  SettingsService,
  SnapshotService,
  SourcesService,
  ThumbnailService,
} from "../../bindings/github.com/Sam-Lam/PAIM/internal/services";

export type {
  ActiveAnalyzeDTO,
  ActiveCleanupAnalyzeDTO,
  ActiveClearSourceDTO,
  ActiveSafeToEraseDTO,
  AnalyzeCompleted,
  AssetDTO,
  AssetsOverTimeBucketDTO,
  AssetsOverTimeDTO,
  CleanupCompleted,
  CleanupProgress,
  ClearSourcePreviewDTO,
  ClearSourceResultDTO,
  DuplicateProgress,
  LibraryProgress,
  LogExportProgress,
  ReorganizePlanProgress,
  SourceEvaluated,
  SourceProgress,
  StartCleanupAnalyzeResult,
  StartSafeToEraseResult,
  AssetDetailDTO,
  AssetRefDTO,
  BackfillStatusDTO,
  BackupBackfillCompleted,
  BackupBackfillProgress,
  BackupReconcileCompleted,
  BackupProviderFailing,
  BackupJobDTO,
  BackupJobRefDTO,
  BackupProgress,
  BackupQueueChanged,
  BackupSummaryDTO,
  BrowseAssetDTO,
  BrowseFilters,
  CameraCountDTO,
  CoverageProviderDTO,
  CoverageProviderFilter,
  CoverageRowDTO,
  ProviderCoverageDTO,
  ClassStatDTO,
  CleanupReportDTO,
  CurrentLibraryDTO,
  DashboardStats,
  DryRunReportDTO,
  DuplicatePairDTO,
  FolderEntryDTO,
  FolderListingDTO,
  ImportCompleted,
  ImportOptions,
  ImportProgress,
  LegacyStatusDTO,
  LockConflictDTO,
  LogEntryDTO,
  MatchDTO,
  MonthCountDTO,
  OpenResultDTO,
  OperationInfo,
  PageResult,
  PluginDTO,
  ProviderCooldownDTO,
  ProviderDTO,
  QueueSummaryDTO,
  QuitRequested,
  RcloneRemoteInfoDTO,
  RcloneRemotesDTO,
  ReconcilePreviewDTO,
  RecentLibraryDTO,
  RecommendationDTO,
  ReorganizeMoveDTO,
  ReorganizePlanDTO,
  ReorganizeSkipDTO,
  SafeToEraseDTO,
  ScanSummary,
  SessionBackupStatusDTO,
  SessionDTO,
  SessionDetail,
  Settings,
  SnapshotConfigDTO,
  SnapshotStatusDTO,
  SourceDTO,
  SourceCleared,
  SourceIdentified,
  StartAnalyzeResult,
  StartClearSourceResult,
  StartImportResult,
  ThumbCacheDTO,
  ThumbsProgress,
  TotalsDTO,
  VersionInfo,
  VolumeDTO,
  VolumeEvent,
  WarmupStatusDTO,
  YearCountDTO,
} from "../../bindings/github.com/Sam-Lam/PAIM/internal/services";

// Canonical event names emitted by the Go services (internal/services/events.go).
export const WailsEvents = {
  ImportProgress: "import:progress",
  ImportCompleted: "import:completed",
  AnalyzeCompleted: "analyze:completed",
  BackupProgress: "backup:progress",
  BackupQueueChanged: "backup:queue-changed",
  BackupBackfillProgress: "backup:backfill-progress",
  BackupBackfillCompleted: "backup:backfill-completed",
  BackupReconcileCompleted: "backup:reconcile-completed",
  BackupProviderFailing: "backup:provider-failing",
  VolumeMounted: "volume:mounted",
  VolumeUnmounted: "volume:unmounted",
  SourceIdentified: "source:identified",
  SourceProgress: "source:progress",
  SourceEvaluated: "source:evaluated",
  SourceCleared: "source:cleared",
  CleanupProgress: "cleanup:progress",
  CleanupCompleted: "cleanup:completed",
  ReorganizePlanProgress: "reorganize:plan-progress",
  LogExportProgress: "log:export-progress",
  DuplicateProgress: "duplicate:progress",
  LibraryProgress: "library:progress",
  QuitRequested: "app:quit-requested",
  ThumbsProgress: "thumbs:progress",
} as const;
