// Central re-export of the generated Wails bindings. Every service call and
// every DTO type used in the frontend flows through here so the (long,
// generated) import path lives in exactly one place. NEVER call fetch/axios —
// all backend access is through these bindings.
export {
  BackupService,
  CleanupService,
  DashboardService,
  DuplicateService,
  HistoryService,
  ImportService,
  LibraryService,
  LogService,
  ProviderService,
  SettingsService,
  SourcesService,
} from "../../bindings/github.com/Sam-Lam/PAIM/internal/services";

export type {
  ActiveAnalyzeDTO,
  ActiveCleanupAnalyzeDTO,
  ActiveSafeToEraseDTO,
  AnalyzeCompleted,
  AssetDTO,
  CleanupCompleted,
  CleanupProgress,
  DuplicateProgress,
  LibraryProgress,
  LogExportProgress,
  ReorganizePlanProgress,
  SourceEvaluated,
  SourceProgress,
  StartCleanupAnalyzeResult,
  StartSafeToEraseResult,
  BackupJobDTO,
  BackupProgress,
  BackupQueueChanged,
  BackupSummaryDTO,
  ClassStatDTO,
  CleanupReportDTO,
  CurrentLibraryDTO,
  DashboardStats,
  DryRunReportDTO,
  DuplicatePairDTO,
  ImportCompleted,
  ImportOptions,
  ImportProgress,
  LegacyStatusDTO,
  LockConflictDTO,
  LogEntryDTO,
  MatchDTO,
  MonthCountDTO,
  OpenResultDTO,
  PageResult,
  PluginDTO,
  ProviderDTO,
  QueueSummaryDTO,
  RecentLibraryDTO,
  RecommendationDTO,
  ReorganizeMoveDTO,
  ReorganizePlanDTO,
  ReorganizeSkipDTO,
  SafeToEraseDTO,
  ScanSummary,
  SessionDTO,
  SessionDetail,
  Settings,
  SourceDTO,
  SourceIdentified,
  StartAnalyzeResult,
  StartImportResult,
  TotalsDTO,
  VolumeDTO,
  VolumeEvent,
} from "../../bindings/github.com/Sam-Lam/PAIM/internal/services";

// Canonical event names emitted by the Go services (internal/services/events.go).
export const WailsEvents = {
  ImportProgress: "import:progress",
  ImportCompleted: "import:completed",
  AnalyzeCompleted: "analyze:completed",
  BackupProgress: "backup:progress",
  BackupQueueChanged: "backup:queue-changed",
  VolumeMounted: "volume:mounted",
  VolumeUnmounted: "volume:unmounted",
  SourceIdentified: "source:identified",
  SourceProgress: "source:progress",
  SourceEvaluated: "source:evaluated",
  CleanupProgress: "cleanup:progress",
  CleanupCompleted: "cleanup:completed",
  ReorganizePlanProgress: "reorganize:plan-progress",
  LogExportProgress: "log:export-progress",
  DuplicateProgress: "duplicate:progress",
  LibraryProgress: "library:progress",
} as const;
