// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService inspects and controls the SQLite-persisted backup queue via the
 * backup Manager. State-changing methods emit backup:queue-changed so the UI can
 * refresh; per-upload progress is emitted as backup:progress by the Manager's
 * ProgressFn (wired in main.go, see NewBackupProgressEmitter).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel cancels a job from any non-terminal state.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(jobID) {
    return $Call.ByID(1944181464, jobID);
}

/**
 * ListJobs returns a page of backup jobs (optionally filtered by status), joined
 * with each job's asset filename and archive path. An empty statusFilter lists
 * all statuses.
 * @param {string} statusFilter
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.BackupJobDTO>>}
 */
export function ListJobs(statusFilter, page, pageSize) {
    return $Call.ByID(48006254, statusFilter, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Pause pauses a pending job.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Pause(jobID) {
    return $Call.ByID(3412453788, jobID);
}

/**
 * PauseAll pauses every pending job.
 * @returns {$CancellablePromise<void>}
 */
export function PauseAll() {
    return $Call.ByID(3205164423);
}

/**
 * QueueSummary returns the count of jobs in each status.
 * @returns {$CancellablePromise<$models.QueueSummaryDTO>}
 */
export function QueueSummary() {
    return $Call.ByID(2056755563).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Resume resumes a paused job.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Resume(jobID) {
    return $Call.ByID(1002769893, jobID);
}

/**
 * ResumeAll resumes every paused job.
 * @returns {$CancellablePromise<void>}
 */
export function ResumeAll() {
    return $Call.ByID(684596164);
}

/**
 * Retry requeues a failed job immediately.
 * @param {string} jobID
 * @returns {$CancellablePromise<void>}
 */
export function Retry(jobID) {
    return $Call.ByID(3825207064, jobID);
}

// Private type creation functions
const $$createType0 = $models.BackupJobDTO.createFrom;
const $$createType1 = $models.PageResult.createFrom($$createType0);
const $$createType2 = $models.QueueSummaryDTO.createFrom;
