// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService inspects and controls the SQLite-persisted backup queue via the
 * backup Manager. State-changing methods emit backup:queue-changed so the UI can
 * refresh; per-upload progress is emitted as backup:progress by the Manager's
 * ProgressFn (wired in main.go, see NewBackupProgressEmitter).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel cancels a job from any non-terminal state.
 */
export function Cancel(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(1944181464, jobID);
}

/**
 * ListJobs returns a page of backup jobs (optionally filtered by status), joined
 * with each job's asset filename and archive path. An empty statusFilter lists
 * all statuses.
 */
export function ListJobs(statusFilter: string, page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.BackupJobDTO>> {
    return $Call.ByID(48006254, statusFilter, page, pageSize);
}

/**
 * Pause pauses a pending job.
 */
export function Pause(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3412453788, jobID);
}

/**
 * PauseAll pauses every pending job.
 */
export function PauseAll(): $CancellablePromise<void> {
    return $Call.ByID(3205164423);
}

/**
 * QueueSummary returns the count of jobs in each status.
 */
export function QueueSummary(): $CancellablePromise<$models.QueueSummaryDTO> {
    return $Call.ByID(2056755563);
}

/**
 * Resume resumes a paused job.
 */
export function Resume(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(1002769893, jobID);
}

/**
 * ResumeAll resumes every paused job.
 */
export function ResumeAll(): $CancellablePromise<void> {
    return $Call.ByID(684596164);
}

/**
 * Retry requeues a failed job immediately.
 */
export function Retry(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3825207064, jobID);
}
