// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CleanupService runs the read-only Cleanup Assistant analysis over a folder.
 * 
 * v1 is advisory only: there is deliberately NO server-side delete method. The
 * Analyze result carries a recommendation the UI presents; any actual deletion
 * is the user's responsibility in Finder. A DeleteAnalyzedFolder method is
 * intentionally not implemented.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Analyze performs a strictly read-only classification of every media file under
 * root against the archive and returns the report plus its delete-safety
 * recommendation. It is synchronous but honors ctx cancellation between files.
 */
export function Analyze(root: string): $CancellablePromise<$models.CleanupReportDTO> {
    return $Call.ByID(530975406, root);
}

/**
 * PickFolder opens a native directory chooser for the folder to analyze.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2287990203);
}
