// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService aggregates the headline metrics shown on the dashboard. It
 * uses the repositories where they expose the needed rollups and falls back to
 * direct GORM read-model queries for aggregates the repos do not cover
 * (per-month growth, status counts, recent activity).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStats computes the dashboard metrics.
 */
export function GetStats(): $CancellablePromise<$models.DashboardStats> {
    return $Call.ByID(579990625);
}
