// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService aggregates the headline metrics shown on the dashboard. It
 * uses the repositories where they expose the needed rollups and falls back to
 * direct GORM read-model queries for aggregates the repos do not cover
 * (per-month growth, status counts, recent activity).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the DashboardService to an open library's catalog in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(1891870997, core);
}

/**
 * GetStats computes the dashboard metrics.
 * @returns {$CancellablePromise<$models.DashboardStats>}
 */
export function GetStats() {
    return $Call.ByID(579990625).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(2096842529, gate);
}

// Private type creation functions
const $$createType0 = $models.DashboardStats.createFrom;
