// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService lists past import sessions and the log entries belonging to one.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind wires the HistoryService to an open library's repos in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(3738823893, core);
}

/**
 * ListSessions returns a page of import sessions, newest first. SessionRepo
 * exposes only a limit-based recent listing, so pagination is implemented by
 * fetching up to (offset+limit) recent rows and slicing the window; Total is the
 * true count of all sessions so the History table renders correct pagination.
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.SessionDTO>>}
 */
export function ListSessions(page, pageSize) {
    return $Call.ByID(3185044847, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SessionEvents returns the session plus the log entries that reference it. The
 * LogRepo cannot query MetadataJSON directly, so entries are gathered from the
 * import subsystem within the session's time window and filtered in memory to
 * those whose MetadataJSON mentions the session ID.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.SessionDetail>}
 */
export function SessionEvents(sessionID) {
    return $Call.ByID(97310383, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(3095585249, gate);
}

// Private type creation functions
const $$createType0 = $models.SessionDTO.createFrom;
const $$createType1 = $models.PageResult.createFrom($$createType0);
const $$createType2 = $models.SessionDetail.createFrom;
