// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService lists past import sessions and the log entries belonging to one.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListSessions returns a page of import sessions, newest first. SessionRepo
 * exposes only a limit-based recent listing, so pagination is implemented by
 * fetching up to (offset+limit) recent rows and slicing the window; Total is a
 * lower bound (the number fetched) which is adequate for the History table's
 * "load more" pattern.
 */
export function ListSessions(page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.SessionDTO>> {
    return $Call.ByID(3185044847, page, pageSize);
}

/**
 * SessionEvents returns the session plus the log entries that reference it. The
 * LogRepo cannot query MetadataJSON directly, so entries are gathered from the
 * import subsystem within the session's time window and filtered in memory to
 * those whose MetadataJSON mentions the session ID.
 */
export function SessionEvents(sessionID: string): $CancellablePromise<$models.SessionDetail> {
    return $Call.ByID(97310383, sessionID);
}
