// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService drives the scan -> dry-run -> import workflow. It enforces a
 * single active import: StartImport and ResumeSession reject concurrent starts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveImport returns the latest progress snapshot of the running import, or
 * nil when nothing is running.
 */
export function ActiveImport(): $CancellablePromise<$models.ImportProgress | null> {
    return $Call.ByID(939337238);
}

/**
 * CancelImport cancels the active import (if any). The pipeline finalizes the
 * session as cancelled. It is a no-op when nothing is running.
 */
export function CancelImport(): $CancellablePromise<void> {
    return $Call.ByID(1382102186);
}

/**
 * DryRun computes hashes and classifies every file against the archive, returning
 * the mode-aware prediction. It reuses a cached scan for root when present and
 * caches the resulting report so StartImport can reuse it.
 */
export function DryRun(root: string, opts: $models.ImportOptions): $CancellablePromise<$models.DryRunReportDTO> {
    return $Call.ByID(2149229199, root, opts);
}

/**
 * PickFolder opens a native directory chooser and returns the selected path, or
 * "" if the user cancelled.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2382930612);
}

/**
 * ResumeSession resumes an interrupted or cancelled session by ID, in a
 * background goroutine identical to StartImport. Only one import may run at a
 * time.
 */
export function ResumeSession(sessionID: string): $CancellablePromise<$models.StartImportResult> {
    return $Call.ByID(4045256054, sessionID);
}

/**
 * ScanSource walks root, caches the scan, and returns provisional counts (no
 * hashing or duplicate detection yet).
 */
export function ScanSource(root: string): $CancellablePromise<$models.ScanSummary> {
    return $Call.ByID(2716834293, root);
}

/**
 * StartImport creates a session (returning its ID immediately) and launches the
 * import in a background goroutine, emitting import:progress throughout and
 * import:completed at the end. Only one import may run at a time; a concurrent
 * start returns ErrImportInProgress.
 * 
 * The run is driven through pipeline.ResumeSession against the freshly created
 * session so the service owns the session ID up front and can stamp it on every
 * emitted progress event. Quick hashes are recomputed at import time (they are
 * cheap relative to the copy); the dry-run cache is used to validate the request
 * and to power instant UI stats, not to seed hashes.
 */
export function StartImport(opts: $models.ImportOptions): $CancellablePromise<$models.StartImportResult> {
    return $Call.ByID(608332294, opts);
}
