// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService drives the scan -> dry-run -> import workflow. It enforces a
 * single active import: StartImport and ResumeSession reject concurrent starts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveImport returns the latest progress snapshot of the running import, or
 * nil when nothing is running.
 * @returns {$CancellablePromise<$models.ImportProgress | null>}
 */
export function ActiveImport() {
    return $Call.ByID(939337238).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Bind wires the ImportService to an open library's importer and repos in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(1987678406, core);
}

/**
 * CancelImport cancels the active import (if any). The pipeline finalizes the
 * session as cancelled. It is a no-op when nothing is running.
 * @returns {$CancellablePromise<void>}
 */
export function CancelImport() {
    return $Call.ByID(1382102186);
}

/**
 * DryRun computes hashes and classifies every file against the archive, returning
 * the mode-aware prediction. It reuses a cached scan for root when present and
 * caches the resulting report so StartImport can reuse it.
 * @param {string} root
 * @param {$models.ImportOptions} opts
 * @returns {$CancellablePromise<$models.DryRunReportDTO>}
 */
export function DryRun(root, opts) {
    return $Call.ByID(2149229199, root, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PickFolder opens a native directory chooser and returns the selected path, or
 * "" if the user cancelled.
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(2382930612);
}

/**
 * ResumeSession resumes an interrupted or cancelled session by ID, in a
 * background goroutine identical to StartImport. Only one import may run at a
 * time.
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.StartImportResult>}
 */
export function ResumeSession(sessionID) {
    return $Call.ByID(4045256054, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ScanSource walks root, caches the scan, and returns provisional counts (no
 * hashing or duplicate detection yet).
 * @param {string} root
 * @returns {$CancellablePromise<$models.ScanSummary>}
 */
export function ScanSource(root) {
    return $Call.ByID(2716834293, root).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(168142972, gate);
}

/**
 * StartImport creates a session (returning its ID immediately) and launches the
 * import in a background goroutine, emitting import:progress throughout and
 * import:completed at the end. Only one import may run at a time; a concurrent
 * start returns ErrImportInProgress.
 * 
 * The run is driven through pipeline.ResumeSession against the freshly created
 * session so the service owns the session ID up front and can stamp it on every
 * emitted progress event. Quick hashes are recomputed at import time (they are
 * cheap relative to the copy); the dry-run cache is used to validate the request
 * and to power instant UI stats, not to seed hashes.
 * @param {$models.ImportOptions} opts
 * @returns {$CancellablePromise<$models.StartImportResult>}
 */
export function StartImport(opts) {
    return $Call.ByID(608332294, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ImportProgress.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DryRunReportDTO.createFrom;
const $$createType3 = $models.StartImportResult.createFrom;
const $$createType4 = $models.ScanSummary.createFrom;
