// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService manages portable libraries: reporting the current/recent
 * libraries, and creating/opening/migrating them. It is the ONE service that is
 * never gated — it is how the user gets a library open in the first place.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the running application version (for Settings → About).
 * @returns {$CancellablePromise<string>}
 */
export function AppVersion() {
    return $Call.ByID(1928401332);
}

/**
 * Create creates a new library at path (or opens it if one already exists there)
 * and opens it. path must be an existing directory.
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenResultDTO>}
 */
export function Create(path) {
    return $Call.ByID(3043023337, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Current returns the open library, or nil when none is open (the frontend
 * redirects to Welcome on nil).
 * @returns {$CancellablePromise<$models.CurrentLibraryDTO | null>}
 */
export function Current() {
    return $Call.ByID(333806998).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ForceOpen opens the library at path, breaking an existing lock. It is the
 * user-confirmed override for a lock conflict.
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenResultDTO>}
 */
export function ForceOpen(path) {
    return $Call.ByID(588766464, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * LegacyStatus reports whether a pre-library catalog exists to migrate.
 * @returns {$CancellablePromise<$models.LegacyStatusDTO>}
 */
export function LegacyStatus() {
    return $Call.ByID(4094524180).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * MigrateLegacy installs the pre-library per-machine catalog into targetRoot and
 * opens it. targetRoot must be an existing directory with no library yet.
 * @param {string} targetRoot
 * @returns {$CancellablePromise<$models.OpenResultDTO>}
 */
export function MigrateLegacy(targetRoot) {
    return $Call.ByID(969238033, targetRoot).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Open opens the existing library at path. It validates that a catalog exists
 * there and returns a clear error otherwise.
 * @param {string} path
 * @returns {$CancellablePromise<$models.OpenResultDTO>}
 */
export function Open(path) {
    return $Call.ByID(2255004805, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PickLibraryFolder opens a native directory chooser for a library root.
 * @returns {$CancellablePromise<string>}
 */
export function PickLibraryFolder() {
    return $Call.ByID(3434768979);
}

/**
 * Recent returns the recently opened libraries (most recent first).
 * @returns {$CancellablePromise<$models.RecentLibraryDTO[]>}
 */
export function Recent() {
    return $Call.ByID(2116018466).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SetCurrent records the currently open library. main.go calls it after a
 * successful open (including the startup open) so Current() reflects reality.
 * @param {$models.CurrentLibraryDTO | null} c
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrent(c) {
    return $Call.ByID(3342758592, c);
}

// Private type creation functions
const $$createType0 = $models.OpenResultDTO.createFrom;
const $$createType1 = $models.CurrentLibraryDTO.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.LegacyStatusDTO.createFrom;
const $$createType4 = $models.RecentLibraryDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
