// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService searches, enumerates, and exports persisted log entries for the
 * Logs page.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Export writes all log entries matching the filters (ignoring pagination) to a
 * user-chosen file in json or csv format via a native save dialog and returns
 * the written path. It returns "" when the user cancels the dialog.
 */
export function Export(query: string, level: string, subsystem: string, fromISO: string, toISO: string, format: string): $CancellablePromise<string> {
    return $Call.ByID(43858206, query, level, subsystem, fromISO, toISO, format);
}

/**
 * Search returns a page of log entries matching the filters, newest first.
 */
export function Search(query: string, level: string, subsystem: string, fromISO: string, toISO: string, page: number, pageSize: number): $CancellablePromise<$models.PageResult<$models.LogEntryDTO>> {
    return $Call.ByID(1748940228, query, level, subsystem, fromISO, toISO, page, pageSize);
}

/**
 * Subsystems returns the distinct subsystem names present in the log, sorted.
 */
export function Subsystems(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2833846240);
}
