// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService searches, enumerates, and exports persisted log entries for the
 * Logs page.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Export writes all log entries matching the filters (ignoring pagination) to a
 * user-chosen file in json or csv format via a native save dialog and returns
 * the written path. It returns "" when the user cancels the dialog.
 * @param {string} query
 * @param {string} level
 * @param {string} subsystem
 * @param {string} fromISO
 * @param {string} toISO
 * @param {string} format
 * @returns {$CancellablePromise<string>}
 */
export function Export(query, level, subsystem, fromISO, toISO, format) {
    return $Call.ByID(43858206, query, level, subsystem, fromISO, toISO, format);
}

/**
 * Search returns a page of log entries matching the filters, newest first.
 * @param {string} query
 * @param {string} level
 * @param {string} subsystem
 * @param {string} fromISO
 * @param {string} toISO
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<$models.PageResult<$models.LogEntryDTO>>}
 */
export function Search(query, level, subsystem, fromISO, toISO, page, pageSize) {
    return $Call.ByID(1748940228, query, level, subsystem, fromISO, toISO, page, pageSize).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Subsystems returns the distinct subsystem names present in the log, sorted.
 * @returns {$CancellablePromise<string[]>}
 */
export function Subsystems() {
    return $Call.ByID(2833846240).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LogEntryDTO.createFrom;
const $$createType1 = $models.PageResult.createFrom($$createType0);
const $$createType2 = $Create.Array($Create.Any);
