// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderService manages configured backup destinations (BackupProvider rows)
 * and reports the plugins available to back them. Provider CRUD is performed
 * directly over GORM (repo has no provider repository); the registry is used to
 * validate a provider's config via a plugin Initialize probe and to enumerate
 * available plugins with their capabilities.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add validates configJSON against the named plugin (via an Initialize probe)
 * and, on success, creates an enabled provider.
 * @param {string} pluginName
 * @param {string} configJSON
 * @returns {$CancellablePromise<$models.ProviderDTO>}
 */
export function Add(pluginName, configJSON) {
    return $Call.ByID(302596964, pluginName, configJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AvailablePlugins lists the registered plugins with their capabilities.
 * @returns {$CancellablePromise<$models.PluginDTO[]>}
 */
export function AvailablePlugins() {
    return $Call.ByID(17692200).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Bind wires the ProviderService to an open library's catalog in place.
 * @param {$models.AppCore | null} core
 * @returns {$CancellablePromise<void>}
 */
export function Bind(core) {
    return $Call.ByID(3786291646, core);
}

/**
 * List returns every configured provider (including disabled ones).
 * @returns {$CancellablePromise<$models.ProviderDTO[]>}
 */
export function List() {
    return $Call.ByID(1616182161).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetGate injects the shared library gate. Called once by main.go after
 * construction; never called in unit tests (leaving the service ungated).
 * @param {$models.LibraryGate | null} gate
 * @returns {$CancellablePromise<void>}
 */
export function SetGate(gate) {
    return $Call.ByID(1863971588, gate);
}

/**
 * Update revalidates configJSON against the provider's plugin and persists the
 * new config and enabled flag.
 * @param {string} id
 * @param {string} configJSON
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.ProviderDTO>}
 */
export function Update(id, configJSON, enabled) {
    return $Call.ByID(4278627748, id, configJSON, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProviderDTO.createFrom;
const $$createType1 = $models.PluginDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
