// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService reads and writes application settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAll returns the typed settings with defaults applied and the read-only
 * MetadataAvailable flag populated.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function GetAll() {
    return $Call.ByID(2916482902).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Update persists the writable settings. Changing MasterLibraryRoot revalidates
 * that the path exists and is a directory before storing it (an empty root is
 * allowed — the library has not been chosen yet). MetadataAvailable is read-only
 * and ignored. Changes to worker/retry/concurrency counts take effect on the
 * next application start (the running Manager/Pipeline are configured at boot).
 * @param {$models.Settings} $in
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function Update($in) {
    return $Call.ByID(794792368, $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
