// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourcesService lists volumes, identifies import sources, and evaluates
 * safe-to-erase.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EvaluateSafeToErase walks the volume at mountPoint, decides whether it is safe
 * to erase, persists the conclusion on the source (when sourceID is set), and
 * returns the report.
 * @param {string} sourceID
 * @param {string} mountPoint
 * @returns {$CancellablePromise<$models.SafeToEraseDTO>}
 */
export function EvaluateSafeToErase(sourceID, mountPoint) {
    return $Call.ByID(778222795, sourceID, mountPoint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * IdentifyVolume identifies the volume at mountPoint, persists the resulting
 * source (creating a new record or updating the matched one and its LastSeen),
 * emits source:identified, and returns the match with confidence and reasons.
 * @param {string} mountPoint
 * @returns {$CancellablePromise<$models.MatchDTO>}
 */
export function IdentifyVolume(mountPoint) {
    return $Call.ByID(2439323266, mountPoint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListKnownSources returns the most recently seen persisted sources.
 * @returns {$CancellablePromise<$models.SourceDTO[]>}
 */
export function ListKnownSources() {
    return $Call.ByID(3024950359).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListVolumes enumerates and describes every mounted volume under /Volumes.
 * @returns {$CancellablePromise<$models.VolumeDTO[]>}
 */
export function ListVolumes() {
    return $Call.ByID(3325610759).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartWatching runs the volume watcher until ctx is cancelled, emitting
 * volume:mounted / volume:unmounted for each change. It is invoked once from
 * main.go in a background goroutine; the watcher establishes its baseline from
 * the volumes already mounted at start (which produce no events).
 * @returns {$CancellablePromise<void>}
 */
export function StartWatching() {
    return $Call.ByID(385547173);
}

// Private type creation functions
const $$createType0 = $models.SafeToEraseDTO.createFrom;
const $$createType1 = $models.MatchDTO.createFrom;
const $$createType2 = $models.SourceDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.VolumeDTO.createFrom;
const $$createType5 = $Create.Array($$createType4);
